/*!
 * Controls.js - winxp.js
 * http://controlsjs.com/
 *
 * Copyright (c) 2014 Position s.r.o.  All rights reserved.
 *
 * This version of Controls.js is licensed under the terms of GNU General Public License v3.
 * http://www.gnu.org/licenses/gpl-3.0.html
 *
 * The commercial license can be purchased at Controls.js website.
 */








if(typeof ngUserControls==="undefined")ngUserControls=[];
var mbIconInformation="info",mbIconWarning="warn",mbIconQuestion="question",mbIconError="err",WinXPControls={ControlImages:["winxp_base.png?7","winxp_hbox.png?5","winxp_vbox.png?5"],Images:{CheckBox:{L:1,T:25,oL:17,SL:33,oSL:49,GL:65,oGL:81,DL:97,DSL:113,W:13,H:16},CheckBoxLeft:{L:1,T:25,oL:17,SL:33,oSL:49,GL:65,oGL:81,DL:97,DSL:113,W:15,H:16},CheckBoxRight:{L:-1,T:25,oL:15,SL:31,oSL:47,GL:63,oGL:79,DL:95,DSL:111,W:15,H:16},Radio:{L:129,T:25,oL:145,SL:161,oSL:177,DL:209,DSL:193,W:13,H:16},RadioLeft:{L:129,
T:25,oL:145,SL:161,oSL:177,DL:209,DSL:193,W:15,H:16},RadioRight:{L:127,T:25,oL:143,SL:159,oSL:175,DL:207,DSL:191,W:15,H:16},Button:{LeftImg:{L:0,T:1,oL:12,W:4,H:23,SL:24,DL:47},MiddleImg:{L:0,T:253,ST:277,DT:301,H:23,Src:1,oT:326},RightImg:{L:8,T:1,oL:19,W:4,H:23,SL:31,DL:54},MenuRightImg:{L:6,T:42,oL:23,SL:40,oSL:58,DL:76,W:11,H:23},MenuRightBtnImg:{L:1,T:42,oL:18,SL:35,oSL:53,DL:71,W:16,H:23}},DefButton:{LeftImg:{L:58,T:1,oL:12,SL:24,DL:47,W:4,H:23,oSL:36},MiddleImg:{L:0,T:374,oT:326,ST:277,oST:350,
DT:301,H:23,Src:1},RightImg:{L:65,T:1,oL:19,SL:31,DL:54,W:4,H:23,oSL:43}},Edit:{LeftImg:{L:70,T:2,W:2,H:21,DL:86},MiddleImg:{L:0,T:486,DT:532,H:21,Src:1},RightImg:{L:75,T:2,W:2,H:21,DL:91},LeftImgReq:{L:78,T:2,W:2,H:21,DL:86},MiddleImgReq:{L:0,T:509,DT:532,H:21,Src:1},RightImgReq:{L:83,T:2,W:2,H:21,DL:91},ArrowLeft:{L:28,T:82,W:9,H:21,oL:79,DL:130},ArrowRight:{L:40,T:82,W:9,H:21,oL:91,DL:142},ArrowDown:{L:0,T:80,W:13,H:21,oL:51,DL:102},ArrowUp:{L:14,T:80,W:13,H:21,oL:65,DL:116}},SubMenu:{L:330,T:54,
DT:71,W:10,H:16},MenuCheckBox:{L:359,T:-14,oST:42,ST:56,DT:-14,DST:73,W:14,H:14},MenuRadio:{L:374,T:-14,oST:42,ST:56,DT:-14,DST:73,W:14,H:14},SubMenuWhite:{L:330,T:40,DT:71,W:10,H:16},MenuCheckBoxWhite:{L:359,T:-14,ST:42,DT:-14,DST:73,W:14,H:14},MenuRadioWhite:{L:374,T:-14,ST:42,DT:-14,DST:73,W:14,H:14},GroupBox:{LeftTop:{L:361,T:-5,W:5,H:11},Top:{L:0,T:48,H:8,Src:1},RightTop:{L:369,T:-5,W:5,H:11},Left:{L:14,T:0,W:1,Src:2},Right:{L:14,T:0,W:1,Src:2},LeftBottom:{L:361,T:37,W:5,H:4},Bottom:{L:0,T:62,
H:1,Src:1},RightBottom:{L:369,T:37,W:5,H:4}},GroupBoxNoText:{LeftTop:{L:361,T:2,W:5,H:4},Top:{L:0,T:62,H:1,Src:1},RightTop:{L:369,T:2,W:5,H:4},Left:{L:14,T:0,W:1,Src:2},Right:{L:14,T:0,W:1,Src:2},LeftBottom:{L:361,T:37,W:5,H:4},Bottom:{L:0,T:62,H:1,Src:1},RightBottom:{L:369,T:37,W:5,H:4}},Memo:{LeftTop:{L:70,T:2,W:3,H:3,DL:86},Top:{L:0,T:84,H:3,DT:104,Src:1},RightTop:{L:74,T:2,W:3,H:3,DL:90},Left:{L:21,T:0,W:3,DL:41,Src:2},Right:{L:26,T:0,W:3,DL:46,Src:2},LeftBottom:{L:70,T:20,W:3,H:3,DL:86},Bottom:{L:0,
T:89,H:3,DT:109,Src:1},RightBottom:{L:74,T:20,W:3,H:3,DL:90}},MemoReq:{LeftTop:{L:78,T:2,W:3,H:3,DL:86},Top:{L:0,T:94,H:3,DT:104,Src:1},RightTop:{L:82,T:2,W:3,H:3,DL:90},Left:{L:31,T:0,W:3,DL:41,Src:2},Right:{L:36,T:0,W:3,DL:46,Src:2},LeftBottom:{L:78,T:20,W:3,H:3,DL:86},Bottom:{L:0,T:99,H:3,DT:109,Src:1},RightBottom:{L:82,T:20,W:3,H:3,DL:90}},PagesBoxUp:{LeftTop:{L:361,T:-17,W:5,H:23},LeftTop2:{L:361,T:-15,W:1,H:23},Top:{L:0,T:36,H:23,Src:1},RightTop:{L:369,T:-17,W:5,H:23},RightTop2:{L:373,T:-15,
W:1,H:23},Left:{L:14,T:0,W:1,Src:2},Right:{L:14,T:0,W:1,Src:2},LeftBottom:{L:361,T:37,W:5,H:4},Bottom:{L:0,T:59,H:4,Src:1},RightBottom:{L:369,T:37,W:5,H:4}},PagesBoxDown:{LeftTop:{L:361,T:2,W:5,H:4},Top:{L:0,T:55,H:4,Src:1},RightTop:{L:369,T:2,W:5,H:4},Left:{L:14,T:0,W:1,Src:2},Right:{L:14,T:0,W:1,Src:2},LeftBottom:{L:361,T:37,W:5,H:23},LeftBottom2:{L:361,T:35,W:5,H:23},Bottom:{L:0,T:59,H:23,Src:1},RightBottom:{L:369,T:37,W:5,H:23},RightBottom2:{L:373,T:35,W:1,H:23}},PagesUp:new Array({LeftImg:{L:361,
SL:346,DSL:346,T:2,W:5,H:20},MiddleImg:{L:0,T:444,H:20,Src:1,ST:398,DST:398},RightImg:{L:369,SL:350,DSL:350,T:2,W:5,H:20},Separator:{L:340,T:2,W:6,H:20}}),PagesDown:new Array({LeftImg:{L:361,SL:346,DSL:346,T:21,W:5,H:20},MiddleImg:{L:0,T:444,H:20,Src:1,ST:421,DST:421},RightImg:{L:369,SL:350,DSL:350,T:21,W:5,H:20},Separator:{L:340,T:21,W:6,H:20}}),ProgressBar:{LeftImg:{L:118,T:2,W:4,H:17},MiddleImg:{L:0,T:602,H:17,Src:1},RightImg:{L:133,T:2,W:3,H:17},BarImg:{L:123,T:2,W:8,H:17}},TreeImgPlusMinus:{L:242,
T:26,W:17,H:16,SL:226},TreeImgTriangle:{L:260,T:26,W:15,H:16,SL:276},TreeImgFolder:{L:309,T:26,W:20,H:16,SL:290},DropDown:{L:137,T:0,oL:154,DL:171,W:16,H:21},Elipsis:{L:188,T:0,oL:207,DL:226,W:18,H:21},Search:{L:245,T:0,oL:264,DL:283,W:18,H:21},Calendar:{L:301,T:-2,W:19,H:21,DL:320},VSplitMover:{L:94,T:0,W:8,Src:2},VSplitMoverLeft:{L:101,T:0,W:8,Src:2},VSplitMoverRight:{L:87,T:0,W:8,Src:2},VSplit:{L:401,T:16,DL:408,W:8,H:43},VSplitNone:{L:-8,T:0,W:8,H:1},HSplitMover:{L:0,T:238,H:8,Src:1},HSplitMoverTop:{L:0,
T:245,H:8,Src:1},HSplitMoverBottom:{L:0,T:231,H:8,Src:1},HSplit:{L:379,T:0,DT:7,W:43,H:8},HSplitNone:{L:0,T:-8,W:1,H:8},PgListPgNo:{LeftImg:{L:94,T:2,DL:100,W:2,H:20},MiddleImg:{L:0,T:556,DL:0,H:20,Src:1},RightImg:{L:97,T:2,DL:103,W:2,H:20}},Window:{LeftTop:{L:83,T:139,W:5,H:29},Top:{L:0,T:0,H:3,Src:1},RightTop:{L:159,T:139,W:5,H:29},Left:{L:0,T:0,W:3,Src:2},Right:{L:5,T:0,W:3,Src:2},LeftBottom:{L:0,T:139,W:15,H:3},Bottom:{L:0,T:31,H:3,Src:1},RightBottom:{L:4,T:144,W:15,H:3}},WinCloseBtn:{L:90,T:40,
oL:113,W:23,H:24},WinMinBtn:{L:136,T:40,oL:159,W:23,H:24},WinMaxBtn:{L:182,T:40,oL:205,SL:228,oSL:251,W:23,H:24},WinRestoreBtn:{L:228,T:40,oL:251,W:23,H:24},WinHelpBtn:{L:273,T:40,oL:296,W:23,H:24},WindowCaption:{LeftImg:{L:83,T:139,W:40,H:29},MiddleImg:{L:0,T:0,H:29,Src:1},RightImg:{L:124,T:139,W:40,H:29}},ArrowDown:{L:0,T:86,W:13,H:9,oL:51,DL:102},ArrowUp:{L:14,T:86,W:13,H:9,oL:65,DL:116},ArrowLeft:{L:29,T:86,W:9,H:13,oL:80,DL:131},ArrowRight:{L:40,T:86,W:9,H:13,oL:91,DL:142},PagingFirst:{L:-1,
T:66,oL:83,DL:167,W:18,H:18},PagingPrev:{L:20,T:66,oL:104,DL:188,W:18,H:18},PagingNext:{L:39,T:66,oL:123,DL:207,W:18,H:18},PagingLast:{L:60,T:66,oL:144,DL:228,W:18,H:18},DlgIcons:{info:{L:251,T:127,W:32,H:32},question:{L:285,T:127,W:32,H:32},err:{L:319,T:127,W:32,H:32},warn:{L:353,T:127,W:32,H:32}},MiniDlgIcons:{info:{L:250,T:66,W:20,H:20},question:{L:270,T:66,W:20,H:20},err:{L:291,T:66,W:20,H:20},warn:{L:311,T:66,W:20,H:20}},Hint:{LeftTop:{L:20,T:139,W:30,H:18},Top:{L:0,T:114,H:5,Src:1},RightTop:{L:51,
T:139,W:30,H:18},Left:{L:51,T:0,W:7,Src:2},Right:{L:64,T:0,W:14,Src:2},LeftBottom:{L:20,T:158,W:30,H:30},Bottom:{L:0,T:149,H:15,Src:1},RightBottom:{L:51,T:158,W:30,H:30}},HintAnchors:{topleft:{L:15,T:-11,HX:22,HY:0,Img:{L:350,T:89,W:29,H:16}},topright:{R:22,T:-11,HX:6,HY:0,Img:{L:318,T:89,W:29,H:16}},bottomright:{R:22,B:-2,HX:10,HY:15,Img:{L:314,T:106,W:34,H:17}},bottomleft:{L:15,B:-2,HX:22,HY:15,Img:{L:350,T:106,W:34,H:17}},lefttop:{L:-9,T:13,HX:0,HY:22,Img:{L:237,T:91,W:16,H:29}},leftbottom:{L:-9,
B:23,HX:0,HY:6,Img:{L:255,T:91,W:16,H:29}},righttop:{R:-3,T:13,HX:15,HY:22,Img:{L:293,T:91,W:17,H:34}},rightbottom:{R:-3,B:22,HX:15,HY:10,Img:{L:274,T:87,W:17,H:34}}},TextHint:{LeftTop:{L:178,T:139,W:30,H:15},Top:{L:0,T:187,H:5,Src:1},RightTop:{L:210,T:139,W:30,H:15},Left:{L:51,T:0,W:7,Src:2},Right:{L:64,T:0,W:14,Src:2},LeftBottom:{L:178,T:156,W:30,H:25},Bottom:{L:0,T:214,H:15,Src:1},RightBottom:{L:210,T:156,W:30,H:25}},TextHintAnchors:{topleft:{L:6,T:-15,HX:0,HY:0},bottomleft:{L:6,B:-5,HX:0,HY:0},
topright:{R:15,T:-15,HX:0,HY:0},bottomright:{R:15,B:-5,HX:0,HY:0}},BtnArrowUp:{SL:122,T:104,oSL:148,L:174,oL:200,W:25,H:14},BtnArrowDown:{SL:122,T:119,oSL:148,L:174,oL:200,W:25,H:14},BtnArrowLeft:{L:1,T:104,oL:31,SL:61,oSL:92,W:14,H:25},BtnArrowRight:{L:16,T:104,oL:46,SL:76,oSL:107,W:14,H:25},DropPanel:{Left:{L:79,T:0,W:7,Src:2},Right:{L:79,T:0,W:7,Src:2},BottomButton:{Left:{L:85,T:172,W:6,H:14},Middle:{L:0,T:164,H:14,Src:1},Right:{L:95,T:172,W:6,H:14}},TopButton:{Left:{L:112,T:173,W:6,H:14},Middle:{L:0,
T:172,H:14,Src:1},Right:{L:104,T:173,W:6,H:14}}},Close:{L:205,T:87,oL:215,SL:215,DL:225,W:10,H:10}},OnControlCreated:function(o,h){switch(o.Type){case "stdGroup":case "stdGroupBox":if(ng_EmptyVar(h.Frame))h.Frame=h.Text==""&&!h.OnGetText?this.Images.GroupBoxNoText:this.Images.GroupBox;break;case "stdCheckBox":if(h.TextAlign=="right"||h.TextAlign=="center"){h.TextAlign="right";if(ng_EmptyVar(h.LeftImg))h.LeftImg=this.Images.CheckBoxLeft;if(!h.OnGetClassName)h.OnGetClassName=function(){return"BtnLeft"}}else{h.TextAlign=
"left";if(ng_EmptyVar(h.RightImg))h.RightImg=this.Images.CheckBoxRight;if(!h.OnGetClassName)h.OnGetClassName=function(){return"BtnRight"}}break;case "stdRadioButton":if(h.TextAlign=="right"||h.TextAlign=="center"){h.TextAlign="right";if(ng_EmptyVar(h.LeftImg))h.LeftImg=this.Images.RadioLeft;if(!h.OnGetClassName)h.OnGetClassName=function(){return"BtnLeft"}}else{h.TextAlign="left";if(ng_EmptyVar(h.RightImg))h.RightImg=this.Images.RadioRight;if(!h.OnGetClassName)h.OnGetClassName=function(){return"BtnRight"}}break;
case "stdPages":if(h.PagesVAlign=="bottom"){if(ng_EmptyVar(h.Frame)){h.Frame=ng_CopyVar(this.Images.PagesBoxDown);if(h.PagesVisible)if(h.PagesAlign=="right")h.Frame.RightBottom=h.Frame.RightBottom2;else h.Frame.LeftBottom=h.Frame.LeftBottom2}if(ng_EmptyVar(h.PageImages)){h.PageImages=this.Images.PagesDown;h.RowOverlap=1}}else{if(ng_EmptyVar(h.Frame)){h.Frame=ng_CopyVar(this.Images.PagesBoxUp);if(h.PagesVisible)if(h.PagesAlign=="right")h.Frame.RightTop=h.Frame.RightTop2;else h.Frame.LeftTop=h.Frame.LeftTop2}if(ng_EmptyVar(h.PageImages)){h.PageImages=
this.Images.PagesUp;h.RowOverlap=1}}break}},OnInit:function(){function o(a,b,c){if(typeof a.className==="undefined")a.className="wxpGroupBox";return ngCreateControlAsType(a,"ngGroup",b,c)}function h(a,b,c){if(typeof a.className==="undefined")a.className="wxpEdit";if(typeof a.DropDown!=="undefined"&&typeof a.DropDown.className==="undefined")a.DropDown.className="wxpDropDown";(a=ngCreateControlAsType(a,"ngEdit",b,c))&&l.stdEdit_AddProperties(a);return a}function u(a,b,c,g){if(typeof a.className==="undefined")a.className=
"wxpEdit";if(typeof a.DropDown!=="undefined"&&typeof a.DropDown.className==="undefined")a.DropDown.className="wxpDropDown";a=ngCreateControlAsType(a,ngVal(g,"stdEdit"),b,c);if(!a)return a;var d=new ngButton;d.LeftImg=f.Elipsis;d.OnClick=function(e){var i=e.Owner?ngVal(e.Owner.Parent,null):null;i&&i.OnElipsis&&i.OnElipsis(e,i.GetText())};a.Buttons=new Array(d);a.Elipsis=function(){d.Click()};return a}function v(a,b,c,g){if(typeof a.className==="undefined")a.className="wxpEdit";if(typeof a.DropDown!==
"undefined"&&typeof a.DropDown.className==="undefined")a.DropDown.className="wxpDropDown";b=ngCreateControlAsType(a,ngVal(g,"stdEdit"),b,c);if(!b)return b;if(typeof a.DropDown!=="undefined")b.Suggestion=true;var d=new ngButton;d.LeftImg=f.Search;d.Default=true;d.OnClick=function(e){var i=e.Owner?ngVal(e.Owner.Parent,null):null;i&&i.OnSearch&&i.OnSearch(e,i.GetText())};b.Buttons=new Array(d);b.Search=function(e){typeof e!=="undefined"&&this.SetText(e);d.Click()};return b}function q(a,b,c,g){if(typeof a.className===
"undefined")a.className="wxpEdit";if(typeof a.DropDown!=="undefined"&&typeof a.DropDown.className==="undefined")a.DropDown.className="wxpDropDown";b=ngCreateControlAsType(a,ngVal(g,"ngEditNum"),b,c);if(!b)return b;l.stdEdit_AddProperties(b);a=ngVal(a.Arrows,"leftright");if(a!="none"){if(b.ButtonUp)b.ButtonUp.LeftImg=a=="leftright"?f.Edit.ArrowRight:f.Edit.ArrowUp;if(b.ButtonDown)b.ButtonDown.LeftImg=a=="leftright"?f.Edit.ArrowLeft:f.Edit.ArrowDown}return b}function r(a,b,c,g){ng_MergeDef(a,{className:"wxpEdit",
Data:{TextAlign:"center"},DropDown:null});a=ngDropDown_Create(a,b,c,ngVal(g,"ngEdit"));if(!a)return a;l.stdEdit_AddProperties(a);a.GetColor=function(){var d=this.GetText();if(d.length>0&&d[0]=="#")d=d.substring(2,d.length);return d};b=a.DropDownButton;b.Bounds.W=29;b.AutoSize=false;b.OnGetText=function(){return'<div style="margin:3px; line-height: 0px; font-size: 0px; position: absolute;left:0px;top:0px;width: 23px; height:13px; border: 1px solid '+(this.Enabled?"black":"#A0A0A0")+"; background-color: #"+
(this.Enabled?this.Parent.GetColor():"CCCCCC")+'"></div>'};a.OnTextChanged=function(d){d.DropDownButton.Update()};return a}function n(a,b,c,g,d){if(typeof a.className==="undefined")a.className="wxpEdit";b=ngDropDown_Create(a,b,c,ngVal(g,"ngEdit"),d);if(!b)return b;l.stdEdit_AddProperties(b);b.DropDownButton.LeftImg=f.DropDown;if(typeof a.DropDown.className==="undefined")a.DropDown.className="wxpDropDown";return b}function w(a,b,c,g){if(typeof a.className==="undefined")a.className="wxpMemo";var d=
ngCreateControlAsType(a,ngVal(g,"ngMemo"),b,c);if(d){a=ngVal(d.Invalid,false);d.Frame=a?f.MemoReq:f.Memo;d.SetInvalid=function(e,i){d.Frame=e?f.MemoReq:f.Memo;d.Invalid=e;ngVal(i,true)&&d.Update()};return d}}for(var s=ngLibPath("ng_winxp"),k=0;k<this.ControlImages.length;k++)this.ControlImages[k]=s+this.ControlImages[k];var f=this.Images,l=this;ngRegisterControlType("stdPanel",function(a,b,c){return ngCreateControlAsType(a,"ngPanel",b,c)});ngRegisterControlType("stdFrame",function(a,b,c){return ngCreateControlAsType(a,
"ngFrame",b,c)});ngRegisterControlType("stdAlignPanel",function(a,b,c){return ngCreateControlAsType(a,"ngAlignPanel",b,c)});ngRegisterControlType("stdAlignFrame",function(a,b,c){return ngCreateControlAsType(a,"ngAlignFrame",b,c)});ngRegisterControlType("stdText",function(a,b,c){if(typeof a.className==="undefined")a.className="wxpText";return ngCreateControlAsType(a,"ngText",b,c)});ngRegisterControlType("stdImage",function(a,b,c){if(typeof a.className==="undefined")a.className="wxpImage";return ngCreateControlAsType(a,
"ngImage",b,c)});ngRegisterControlType("stdCheckBox",function(a,b,c){if(typeof a.className==="undefined")a.className="wxpCheckBox";return ngCreateControlAsType(a,"ngCheckBox",b,c)});ngRegisterControlType("stdRadioButton",function(a,b,c){if(typeof a.className==="undefined")a.className="wxpRadio";return ngCreateControlAsType(a,"ngRadioButton",b,c)});ngRegisterControlType("stdButton",function(a,b,c){if(typeof a.className==="undefined")a.className="wxpButton";if(b=ngCreateControlAsType(a,"ngButton",b,
c))if(ngVal(b.Default,false)&&typeof a.Menu!=="object"){b.LeftImg=f.DefButton.LeftImg;b.MiddleImg=f.DefButton.MiddleImg;b.RightImg=f.DefButton.RightImg}else{b.LeftImg=f.Button.LeftImg;b.MiddleImg=f.Button.MiddleImg;b.RightImg=typeof a.Menu==="object"?f.Button.MenuRightImg:f.Button.RightImg}return b});ngRegisterControlType("stdFlatButton",function(a,b,c){if(typeof a.className==="undefined")a.className="wxpFlatButton";a=ngCreateControlAsType(a,"ngButton",b,c);if(!a)return a;a.AddEvent("DoUpdate",function(g){var d=
g.className,e=d.indexOf(" ");if(this.Enabled){if(e>=0)d=d.substring(0,e);if(this.Checked)d=d+" "+d+"Checked";g.className=d}else{if(e>=0)d=d.substring(0,e);g.className=d+" "+d+"Disabled"}return true});return a});ngRegisterControlType("stdLabel",function(a,b,c){if(typeof a.className==="undefined")a.className="wxpLabel";return ngCreateControlAsType(a,"ngButton",b,c)});ngRegisterControlType("stdLink",function(a,b,c){if(typeof a.className==="undefined")a.className="wxpLink";return ngCreateControlAsType(a,
"ngButton",b,c)});ngRegisterControlType("stdGroup",o);ngRegisterControlType("stdGroupBox",o);this.stdEdit_AddProperties=function(a){var b=ngVal(a.Invalid,false);a.LeftImg=b?f.Edit.LeftImgReq:f.Edit.LeftImg;a.MiddleImg=b?f.Edit.MiddleImgReq:f.Edit.MiddleImg;a.RightImg=b?f.Edit.RightImgReq:f.Edit.RightImg;a.SetInvalid=function(c,g){if(c){a.LeftImg=f.Edit.LeftImgReq;a.MiddleImg=f.Edit.MiddleImgReq;a.RightImg=f.Edit.RightImgReq}else{a.LeftImg=f.Edit.LeftImg;a.MiddleImg=f.Edit.MiddleImg;a.RightImg=f.Edit.RightImg}a.Invalid=
c;if(ngVal(g,true)){a.LeftImg&&ngc_ChangeImage(ngpg_ImgDrawProps(a.ID+"_IL",0,a.Enabled,a.LeftImg));a.MiddleImg&&ngc_ChangeImageS(ngpg_ImgDrawProps(a.ID+"_IM",0,a.Enabled,a.MiddleImg));a.RightImg&&ngc_ChangeImage(ngpg_ImgDrawProps(a.ID+"_IR",0,a.Enabled,a.RightImg))}}};ngRegisterControlType("stdEdit",h);ngRegisterControlType("stdEditBox",h);ngRegisterControlType("stdEditBoxBtn",function(a,b,c){return u(a,b,c)});ngRegisterControlType("stdSearchBox",function(a,b,c){return v(a,b,c)});ngRegisterControlType("stdEditNum",
function(a,b,c){return q(a,b,c)});ngRegisterControlType("stdEditBoxNum",function(a,b,c){return q(a,b,c)});ngRegisterControlType("stdColorEdit",function(a,b,c){return r(a,b,c)});ngRegisterControlType("stdColorEditBox",function(a,b,c){return r(a,b,c)});ngRegisterControlType("stdDropDown",function(a,b,c){return n(a,b,c,"ngEdit",false)});ngRegisterControlType("stdDropDownList",function(a,b,c){return n(a,b,c,"ngEdit",true)});ngRegisterControlType("stdMemo",function(a,b,c){return w(a,b,c)});ngRegisterControlType("stdPages",
function(a,b,c){if(typeof a.className==="undefined")a.className="wxpPages";return ngCreateControlAsType(a,"ngPages",b,c)});ngRegisterControlType("stdToolBar",function(a,b,c){if(typeof a.className==="undefined")a.className="wxpToolBar";return ngCreateControlAsType(a,"ngToolBar",b,c)});ngRegisterControlType("stdWebBrowser",function(a,b,c){return ngCreateControlAsType(a,"ngWebBrowser",b,c)});ngRegisterControlType("stdProgressBar",function(a,b,c){if(typeof a.className==="undefined")a.className="wxpProgressBar";
a=ngCreateControlAsType(a,"ngProgressBar",b,c);if(!a)return a;a.LeftImg=f.ProgressBar.LeftImg;a.MiddleImg=f.ProgressBar.MiddleImg;a.RightImg=f.ProgressBar.RightImg;a.BarImg=f.ProgressBar.BarImg;return a});ngRegisterControlType("stdProgressDot",function(a,b,c){ng_MergeDef(a,{className:"wxpLabel",Data:{TextAlign:"center"}});ng_PreloadImage(s+"loading.gif");(a=ngCreateControlAsType(a,"ngButton",b,c))&&a.AddEvent(function(g){g=ngTxt(g.Text);if(g!="")g='&nbsp;<span style="line-height: 16px">'+g+"</span>";
return'<img src="'+s+'loading.gif" align="top" />'+g},"OnGetText");return a});if(ngUserControls.list){k=function(a,b,c){if(typeof a.className==="undefined")a.className="wxpListBox";b=ngCreateControlAsType(a,"ngList",b,c);if(!b)return b;b.AddEvent("DoUpdate",function(g){var d=g.className,e=d.indexOf(" ");if(this.Enabled){if(e>=0)g.className=d.substring(0,e)}else if(e<0)g.className=d+" "+d+"Disabled";return true});b.OnGetCheckImg=function(g,d){if(typeof d.Checked==="undefined"&&!g.ShowCheckboxes)return null;
if(typeof d.RadioGroup!=="undefined")return f.RadioLeft;return f.CheckBoxLeft};switch(ngVal(a.TreeImg,a.Type=="stdTreeList"?"plusminus":"")){case "triangle":b.TreeImg=f.TreeImgTriangle;break;case "folder":b.TreeImg=f.TreeImgFolder;break;case "plusminus":b.TreeImg=f.TreeImgPlusMinus;break}return b};ngRegisterControlType("stdList",k);ngRegisterControlType("stdListBox",k);ngRegisterControlType("stdTreeList",k);this.stdPageListPagingControlsDef=function(){return{FirstPage:{Type:"stdFlatButton",Data:{ToolBarHPadding:5,
Img:f.PagingFirst,Text:""}},PrevPage:{Type:"stdFlatButton",Data:{ToolBarHPadding:5,Img:f.PagingPrev,Text:""}},PageNo:{Type:"stdEdit",W:30,className:"wxpPgListPgNo",Data:{ToolBarHPadding:5,LeftImg:f.PgListPgNo.LeftImg,MiddleImg:f.PgListPgNo.MiddleImg,RightImg:f.PgListPgNo.RightImg,Text:"1",TextAlign:"center"}},Page0:{Type:"stdFlatButton",Data:{ToolBarHPadding:5,MinWidth:18,Text:"1",TextAlign:"center"}},NextPage:{Type:"stdFlatButton",Data:{Img:f.PagingNext,Text:"",ImgAlign:"right",ToolBarHPadding:5}},
LastPage:{Type:"stdFlatButton",Data:{Img:f.PagingLast,ImgAlign:"right",Text:""}}}};var p=function(a,b,c,g,d){ng_MergeDef(a,{className:"wxpListBox",Controls:{List:{Type:ngVal(d,"stdList"),style:{border:"0px"}},Loading:{Type:"stdProgressDot",L:10,T:g==="ngDataSet"||g==="ngDBDataSet"||a.Controls&&a.Controls.List&&a.Controls.List.Data&&a.Controls.List.Data.Columns&&a.Controls.List.Data.Columns.length>0?31:10,Data:{Visible:false}},Paging:{className:"wxpPageListPaging",Controls:l.stdPageListPagingControlsDef()}}});
a=ngCreateControlAsType(a,ngVal(g,"ngPageList"),b,c);if(!a)return a;a.AddEvent("DoUpdate",function(e){var i=e.className,j=i.indexOf(" ");if(this.Enabled){if(j>=0)e.className=i.substring(0,j)}else if(j<0)e.className=i+" "+i+"Disabled";return true});return a};ngRegisterControlType("stdPageList",function(a,b,c){return p(a,b,c,"ngPageList")});ngRegisterControlType("stdPageTreeList",function(a,b,c){return p(a,b,c,"ngPageList","stdTreeList")})}if(ngUserControls.panels){ngRegisterControlType("stdSplitPanel",
function(a,b,c){if(typeof a.className==="undefined")a.className="wxpSplitPanel";if(b=ngCreateControlAsType(a,"ngSplitPanel",b,c)){c=b.PanelAlign=="left"||b.PanelAlign=="right";a=ngVal(a.Mover,"handle");switch(a){case "both":b.MoverMiddleImg=c?f.VSplitMover:f.HSplitMover;break;case "controls1":b.MoverMiddleImg=c?b.PanelAlign=="left"?f.VSplitMoverLeft:f.VSplitMoverRight:b.PanelAlign=="top"?f.HSplitMoverTop:f.HSplitMoverBottom;break;case "controls2":b.MoverMiddleImg=c?b.PanelAlign=="left"?f.VSplitMoverRight:
f.VSplitMoverLeft:b.PanelAlign=="top"?f.HSplitMoverBottom:f.HSplitMoverTop;break}b.HandleImg=a=="none"?c?f.VSplitNone:f.HSplitNone:c?f.VSplit:f.HSplit}return b});ngRegisterControlType("stdDropPanel",function(a,b,c){if(typeof a.className==="undefined")a.className="wxpDropPanel";b=ngCreateControlAsType(a,"ngDropPanel",b,c);ng_MergeDef(a,{ControlsPanel:{Type:"ngGroup",ControlsPanel:{style:{backgroundColor:"#FFFFFF"}},Data:{Frame:{Left:f.DropPanel.Left,Right:f.DropPanel.Right}}},Button:{Data:{OnGetImg:function(g,
d){var e=null;g=g.Owner&&typeof g.Owner.Bounds.T=="undefined";switch(d){case -1:e=g?f.BtnArrowDown:f.BtnArrowUp;break;case 0:e=g?f.DropPanel.TopButton.Left:f.DropPanel.BottomButton.Left;break;case 1:e=g?f.DropPanel.TopButton.Middle:f.DropPanel.BottomButton.Middle;break;case 2:e=g?f.DropPanel.TopButton.Right:f.DropPanel.BottomButton.Right;break}return ngVal(e,null)}}}});return b})}if(ngUserControls.window){k=function(a,b,c){var g=a.Type=="stdDialog";if(typeof a.className==="undefined")a.className=
g?"wxpDialog":"wxpWindow";var d=ngCreateControlAsType(a,"ngWindow",b,c);if(!d)return d;d.Frame=f.Window;d.CaptionImg=f.WindowCaption;if(g){d.Modal=true;d.Visible=false;d.Sizeable=false;d.Centered=true}if(ngVal(a.CloseBtn,g?true:false)){b=new ngButton;d.CloseButton=b;b.LeftImg=f.WinCloseBtn;b.OnClick=function(e){(e=e.Owner?ngVal(e.Owner.Parent,null):null)&&e.Close&&e.Close(e)};if(!d.Buttons)d.Buttons=[];d.Buttons[d.Buttons.length]=b}if(ngVal(a.HelpBtn,false)){b=new ngButton;d.HelpButton=b;b.LeftImg=
f.WinHelpBtn;b.OnClick=function(e){(e=e.Owner?ngVal(e.Owner.Parent,null):null)&&e.OnHelp&&e.OnHelp(e)};if(!d.Buttons)d.Buttons=[];d.Buttons[d.Buttons.length]=b}if(ngVal(a.MaxBtn,false)){b=new ngButton;d.MaxButton=b;d.OnDblClick=function(e){e.win&&e.win.MaxButton&&e.win.MaxButton.Click()};d.AddEvent(function(){var e=d.IsMaximized()?1:0;d.MaxButton&&d.MaxButton.Checked!=e&&d.MaxButton.Check(e);return true},"DoUpdate");b.LeftImg=f.WinMaxBtn;b.OnClick=function(e){var i=e.Owner?ngVal(e.Owner.Parent,null):
null;if(i){e.Owner.Check(i.IsMaximized()?0:1);if(e.Owner.Checked)i.Maximize&&i.Maximize(i);else i.Restore&&i.Restore(i)}};if(!d.Buttons)d.Buttons=[];d.Buttons[d.Buttons.length]=b}if(ngVal(a.MinBtn,false)){b=new ngButton;d.MinButton=b;b.LeftImg=f.WinMinBtn;d.AddEvent(function(){var e=d.IsMinimized()?1:0;d.MinButton&&d.MinButton.Checked!=e&&d.MinButton.Check(e);return true},"DoUpdate");b.OnClick=function(e){var i=e.Owner?ngVal(e.Owner.Parent,null):null;if(i){e.Owner.Check(i.IsMinimized()?0:1);if(e.Owner.Checked)i.Minimize&&
i.Minimize(i);else i.Restore&&i.Restore(i)}};if(!d.Buttons)d.Buttons=[];d.Buttons[d.Buttons.length]=b}return d};ngRegisterControlType("stdWindow",k);ngRegisterControlType("stdDialog",k);ngRegisterControlType("stdHint",function(a,b,c){if(typeof a.className==="undefined")a.className="wxpHint";if(a=ngCreateControlAsType(a,"ngHint",b,c)){a.Frame=ng_CopyVar(f.Hint);a.Anchors=ng_CopyVar(f.HintAnchors)}return a});ngRegisterControlType("stdTextHint",function(a,b,c){ng_MergeDef(a,{className:"wxpTextHint",
Controls:{Hint:{Type:"stdText",L:5,T:2}}});if(a=ngCreateControlAsType(a,"ngTextHint",b,c)){a.Frame=ng_CopyVar(f.TextHint);a.Anchors=ng_CopyVar(f.TextHintAnchors)}return a})}if(ngUserControls.dialogs){ngRegisterControlType("stdMessageDlg",function(a,b,c){ng_MergeDef(a,{DialogType:"stdDialog",Controls:{Message:{Type:"stdText"},Content:{Type:"ngPanel",L:15,R:15,H:15},Buttons:{Type:"ngToolBar",H:23,Data:{HPadding:10},Controls:{OK:{Type:"stdButton",W:80},Yes:{Type:"stdButton",W:80},No:{Type:"stdButton",
W:80},Cancel:{Type:"stdButton",W:80}}}}});if(typeof a.DlgCheckBox!=="undefined"){ng_MergeDef(a,{Controls:{Content:{Controls:{CheckBox:{Type:"stdCheckBox",L:0,B:10,Data:a.DlgCheckBox}}}}});a.Controls.Content.H+=25}if(a.DialogType=="stdMessageDlg")a.DialogType="stdDialog";return ngCreateControlAsType(a,"ngMessageDlg",b,c)});ngRegisterControlType("dlgMessageBox",function(a,b,c){delete a.DialogType;a.DlgButtons=ngVal(a.DlgButtons,mbOK);a.DlgIcon=ngVal(a.DlgIcon,mbIconInformation);var g=null;if(typeof a.DlgIcon===
"object")g=a.DlgIcon;else if(typeof a.DlgIcon!=="undefined")g=ngVal(f.DlgIcons[a.DlgIcon],null);if(g){ng_MergeDef(a,{Data:{},Controls:{Message:{L:15+g.W+10,T:25,Data:{MinHeight:typeof a.DlgCheckBox!=="undefined"?g.H>=30?g.H-30:0:g.H-10}},Icon:{Type:"stdImage",L:15,T:15,W:g.W,H:g.H,Data:{Img:g}},Content:{H:10,Controls:{}}}});if(a.Controls.Content.Controls.Check)a.Controls.Content.Controls.Check.L=g.W+10}return ngCreateControlAsType(a,"stdMessageDlg",b,c)});k=function(a,b,c){delete a.DialogType;a.DlgAllowEmpty=
ngVal(a.DlgAllowEmpty,false);var g={DialogType:"stdMessageDlg",DlgButtons:mbOK|mbCancel,Data:{},Controls:{Message:{Data:{MinWidth:250}},Content:{H:30,Controls:{Edit:{Type:"stdEdit",L:0,T:2,R:0,Data:{}}}},Buttons:{Controls:{OK:{Data:{}}}}}},d=g.Controls.Content.Controls.Edit;switch(a.Type){case "dlgMemoBox":d.Type="stdMemo";d.H=100;g.Controls.Content.H=110;break;case "dlgDropDownBox":case "dlgDropDownListBox":d.Type=a.Type=="dlgDropDownBox"?"stdDropDown":"stdDropDownList";d.DropDown={Type:"stdList",
Data:{}};if(typeof a.DlgItems!=="undefined")d.DropDown.Data.Items=a.DlgItems;break}if(typeof a.DlgHint!=="undefined")d.Data.Hint=a.DlgHint;if(!a.DlgAllowEmpty){d.Data.OnTextChanged=function(e){e.Owner.OK.SetEnabled(e.GetText()!="");return true};g.Controls.Buttons.Controls.OK.Data.Enabled=false}ng_MergeDef(a,g);b=ngCreateControlAsType(a,"stdMessageDlg",b,c);a.Type!="dlgDropDownListBox"&&b.AddEvent("OnVisibleChanged",function(e){var i,j=e.Controls.Edit;i=j.OnGetHint?ngVal(j.OnGetHint(j),""):j.Hint;
e.Visible&&i==""&&j.SetFocus()});return b};ngRegisterControlType("dlgInputBox",k);ngRegisterControlType("dlgDropDownBox",k);ngRegisterControlType("dlgDropDownListBox",k);ngRegisterControlType("dlgMemoBox",k);ngRegisterControlType("dlgListBox",function(a,b,c){delete a.DialogType;a.DlgAllowEmpty=ngVal(a.DlgAllowEmpty,false);var g={DialogType:"stdMessageDlg",DlgButtons:mbOK|mbCancel,Data:{},Controls:{Message:{Data:{MinWidth:300}},Content:{H:265,Controls:{List:{Type:"stdList",L:0,T:2,R:0,H:250,Data:{SelectType:nglSelectSingle}}}},
Buttons:{Controls:{OK:{Data:{}}}}}},d=g.Controls.Content.Controls.List;if(typeof a.DlgItems!=="undefined")d.Data.Items=a.DlgItems;if(!a.DlgAllowEmpty){d.Data.OnSelectChanged=function(e){e.Owner.OK.SetEnabled&&e.Owner.OK.SetEnabled(e.SelCount>0);return true};g.Controls.Buttons.Controls.OK.Data.Enabled=false}ng_MergeDef(a,g);a=ngCreateControlAsType(a,"stdMessageDlg",b,c);a.AddEvent("OnVisibleChanged",function(e){e.Visible&&e.Controls.List.SetFocus()});return a});ngRegisterControlType("dlgProgressBox",
function(a,b,c){delete a.DialogType;ng_MergeDef(a,{DlgButtons:mbNone,Data:{},Controls:{Message:{Data:{MinWidth:230}},Content:{H:30,Controls:{Progress:{Type:"stdProgressBar",L:0,T:5,R:0}}}}});return ngCreateControlAsType(a,"stdMessageDlg",b,c)});ngRegisterControlType("dlgWaitBox",function(a,b,c){delete a.DialogType;ng_MergeDef(a,{DlgButtons:mbNone,Data:{},Controls:{Message:{L:40,Data:{}},Progress:{Type:"stdProgressDot",L:15,T:15},Content:{Data:{Visible:false}}}});return ngCreateControlAsType(a,"stdMessageDlg",
b,c)});ngRegisterControlType("dlgAbout",function(a,b,c){var g={DialogType:"dlgMessageBox",DlgIcon:null,Controls:{Message:{className:"wxpAboutMessage",Data:{MinWidth:260}},Content:{Controls:{AppInfo:{Type:"stdTreeList",style:{border:"0px"},TreeImg:"triangle",Data:{DefaultIndent:0}}}}}};if(typeof a.DlgIcon==="object"&&a.DlgIcon)g.Controls.Message.Data.MinWidth-=a.DlgIcon.W+10;ng_MergeDef(a,g);return ngCreateControlAsType(a,"ngAboutDlg",b,c)})}if(ngUserControls.calendar){ngRegisterControlType("stdCalendar",
function(a,b,c){if(typeof a.className==="undefined")a.className="wxpCalendar";a=ngCreateControlAsType(a,"ngCalendar",b,c);if(!a)return a;a.PrevMonBtn.LeftImg=f.ArrowLeft;a.PrevMonBtn.Text="";a.NextMonBtn.LeftImg=f.ArrowRight;a.NextMonBtn.Text="";a.PrevYearBtn.LeftImg=f.ArrowLeft;a.PrevYearBtn.Text="";a.NextYearBtn.LeftImg=f.ArrowRight;a.NextYearBtn.Text="";for(b=0;b<a.FastButtons.length;b++){c=a.FastButtons[b];c.LeftImg=f.Button.LeftImg;c.MiddleImg=f.Button.MiddleImg;c.RightImg=f.Button.RightImg;
c.className="wxpButton"}return a});var x=function(a,b,c,g){ng_MergeDef(a,{className:"wxpEdit",DropDown:{className:"wxpCalendar wxpDropDown",Type:"stdCalendar",style:{padding:"10px"}}});a=n(a,b,c,ngVal(g,"ngEditDate"),false);if(!a)return a;l.stdEdit_AddProperties(a);a.DropDownButton.LeftImg=f.Calendar;a.DropDownButton.Alt=ngTxt("calendar");return a};ngRegisterControlType("stdEditDate",function(a,b,c){return x(a,b,c)});var z=function(a,b,c,g){var d=1;ng_MergeDef(a,{className:"wxpEdit",Data:{},Events:{OnDropDown:function(e,
i){if(!i.Items.length){i.BeginUpdate();e=[];for(var j=0;j<24;j++)for(var t=0;t<60;t+=d){var y=new Date(0,0,0,j,t,0);e.push({Text:ng_FormatTime(y,ng_TimeFormat(false,true)),Time:y})}i.AddItems(e);i.EndUpdate()}return true},OnListItemChanged:function(e,i,j){e.SetDate(j.Time);e.HideDropDown&&e.HideDropDown();return false}},DropDown:{className:"wxpDropDown",Type:"stdList"}});d=ngVal(a.DropDown.HourDivider,2);if(d<=0)d=1;d=60/d;b=ngCreateControlAsType(a,ngVal(g,"ngEditTime"),b,c);if(!b)return b;if(a.Type==
"ngDropDownList")b.DropDownType=ngeDropDownList;ngDropDown_Add(b);l.stdEdit_AddProperties(b);b.DropDownButton.LeftImg=f.DropDown;if(typeof a.DropDown.className==="undefined")a.DropDown.className="wxpDropDown";return b};ngRegisterControlType("stdEditTime",function(a,b,c){return z(a,b,c)})}if(ngUserControls.menu){ngRegisterControlType("stdMenu",function(a,b,c){ng_MergeDef(a,{className:"wxpMenu",Data:{SubMenuImg:f.SubMenu,SubMenuDef:{Type:"stdMenu"}}});if(a=ngCreateControlAsType(a,"ngMenu",b,c))a.OnGetCheckImg=
function(g,d){if(typeof d.Checked==="undefined"||!g.ShowCheckboxes)return null;return WinXPControls.Images.MenuCheckBox};return a});ngRegisterControlType("stdMenuBar",function(a,b,c){if(typeof a.className==="undefined")a.className="wxpMenuBar";return ngCreateControlAsType(a,"ngMenuBar",b,c)});ngRegisterControlType("stdMenuBarButton",function(a,b,c){return ngCreateControlAsType(a,"ngMenuBarButton",b,c)});ngRegisterControlType("stdSplitButton",function(a,b,c){if(typeof a.className==="undefined")a.className=
"wxpSplitButton";a=ngCreateControlAsType(a,"ngSplitButton",b,c);if(!a)return a;a.LeftImg=f.Button.LeftImg;a.MiddleImg=f.Button.MiddleImg;a.RightImg=f.Button.MenuRightBtnImg;return a})}if(ngUserControls.viewmodel_controls){var A=function(a,b,c,g){ng_MergeDef(a,{ErrorHint:{Type:"stdTextHint",className:"wxpEditFieldError"}});(a=ngCreateControlAsType(a,ngVal(g,"ngViewModelForm"),b,c))&&a.AddEvent("OnShowErrorMsg",function(d,e){typeof ngMessageDlg==="function"?ngMessageDlg("dlgMessageBox",e,typeof d.Caption===
"undefined"?ngTxt("ngAppName"):ngTxt(d.Caption),null,{DlgIcon:mbIconError}):alert(e);return true});return a};ngRegisterControlType("stdViewModelForm",function(a,b,c){return A(a,b,c)});var m=function(a){ng_MergeDef(a,{Data:{HintX:0},ErrorHint:{Type:"stdTextHint",className:"wxpEditFieldError"}})};ngRegisterControlType("stdEditField",function(a,b,c){m(a);if(typeof a.className==="undefined")a.className="wxpEdit";if(typeof a.DropDown!=="undefined"&&typeof a.DropDown.className==="undefined")a.DropDown.className=
"wxpDropDown";(a=ngCreateControlAsType(a,"ngEditField",b,c))&&l.stdEdit_AddProperties(a);return a});ngRegisterControlType("stdSearchBoxField",function(a,b,c){return v(a,b,c,"stdEditField")});ngRegisterControlType("stdEditBoxBtnField",function(a,b,c){return u(a,b,c,"stdEditField")});ngRegisterControlType("stdEditNumField",function(a,b,c){m(a);return q(a,b,c,"ngEditNumField")});ngRegisterControlType("stdColorEditField",function(a,b,c){m(a);return r(a,b,c,"ngDropDownField")});ngRegisterControlType("stdDropDownField",
function(a,b,c){m(a);return n(a,b,c,"ngDropDownField",false)});ngRegisterControlType("stdDropDownListField",function(a,b,c){m(a);return n(a,b,c,"ngDropDownListField",true)});ngRegisterControlType("stdEditDateField",function(a,b,c){m(a);return x(a,b,c,"ngEditDateField")});ngRegisterControlType("stdEditTimeField",function(a,b,c){m(a);return z(a,b,c,"ngEditTimeField")});ngRegisterControlType("stdMemoField",function(a,b,c){m(a);return w(a,b,c,"ngMemoField")})}ngUserControls.viewmodel_dataset&&ngRegisterControlType("stdDataSet",
function(a,b,c){return p(a,b,c,"ngDataSet")});if(ngUserControls.dbviewmodel){ngRegisterControlType("stdDBViewModelForm",function(a,b,c){if(a=A(a,b,c,"ngDBViewModelForm")){a.AddEvent("OnDeleteQuery",function(g,d,e,i){if(typeof ngMessageDlg==="function"){ngMessageDlg("dlgMessageBox",d,typeof g.Caption==="undefined"?ngTxt("ngAppName"):ngTxt(g.Caption),function(j){if(j.DialogResult==mbYes)typeof e==="function"&&e(g);else typeof i==="function"&&i(g);j.Hide();return true},{DlgIcon:mbIconQuestion,DlgButtons:mbYes|
mbNo|mbDefButton2});return false}else{if(confirm(d))typeof e==="function"&&e(g);else typeof i==="function"&&i(g);return true}});a.AddEvent("OnChangedQuery",function(g,d,e,i){if(typeof ngMessageDlg==="function"){ngMessageDlg("dlgMessageBox",d,typeof g.Caption==="undefined"?ngTxt("ngAppName"):ngTxt(g.Caption),function(j){if(j.DialogResult==mbYes)typeof e==="function"&&e(g);else typeof i==="function"&&i(g);j.Hide();return true},{DlgIcon:mbIconWarning,DlgButtons:mbYes|mbNo|mbDefButton2});return false}else{if(confirm(d))typeof e===
"function"&&e(g);else typeof i==="function"&&i(g);return true}})}return a});ngRegisterControlType("stdDBToolBar",function(a,b,c){ng_MergeDef(a,{W:260,className:"wxpToolBar",Data:{HPadding:5},Controls:{New:{Type:"stdButton",W:60},Delete:{Type:"stdButton",W:60,Data:{ToolBarHPadding:10}},Insert:{Type:"stdButton",W:60},Update:{Type:"stdButton",W:60},Cancel:{Type:"stdButton",W:60}}});return ngCreateControlAsType(a,"ngDBToolBar",b,c)});ngRegisterControlType("stdDBDataSet",function(a,b,c){ng_MergeDef(a,
{Controls:{Paging:{Controls:{NewRecord:{Type:"stdFlatButton",Data:{ToolBarHPadding:5}},LoadRecord:{Type:"stdFlatButton",Data:{ToolBarHPadding:5}},DeleteRecord:{Type:"stdFlatButton",Data:{ToolBarHPadding:10}},Refresh:{Type:"stdFlatButton",Data:{ToolBarHPadding:10}}}}}});return p(a,b,c,"ngDBDataSet")})}}};ngUserControls.winxp=WinXPControls;
