/*!
 * Controls.js - wireframe.js
 * http://controlsjs.com/
 *
 * Copyright (c) 2014 Position s.r.o.  All rights reserved.
 *
 * This version of Controls.js is licensed under the terms of GNU General Public License v3.
 * http://www.gnu.org/licenses/gpl-3.0.html
 *
 * The commercial license can be purchased at Controls.js website.
 */








if(typeof ngUserControls==="undefined")ngUserControls=[];
var WireframeControls={ControlImages:["wireframe_base.png?3","wireframe_h.png?3","wireframe_v.png?3","wireframe_dot.gif?3"],Images:{CheckBox:{L:1,T:30,oL:21,SL:41,oSL:61,GL:81,oGL:101,DL:121,DSL:141,W:16,H:20,DGL:161},CheckBoxLeft:{L:1,T:30,oL:21,SL:41,oSL:61,GL:81,oGL:101,DL:121,DSL:141,W:20,H:20,DGL:161},CheckBoxRight:{L:-3,T:30,oL:17,SL:37,oSL:57,GL:77,oGL:97,DL:117,DSL:137,W:20,H:20,DGL:157},Radio:{L:181,T:30,oL:201,SL:221,oSL:241,DL:261,DSL:281,W:16,H:20},RadioLeft:{L:181,T:30,oL:201,SL:221,
oSL:241,DL:261,DSL:281,W:20,H:20},RadioRight:{L:177,T:30,oL:197,SL:217,oSL:237,DL:257,DSL:277,W:20,H:20},Button:{LeftImg:{L:1,T:1,oL:15,W:6,H:27,SL:29,DL:57,oSL:43},MiddleImg:{L:0,T:0,ST:56,oT:28,DT:112,oST:84,H:27,Src:1},RightImg:{L:8,T:1,oL:22,W:6,H:27,SL:36,DL:64,oSL:50}},DefButton:{LeftImg:{L:71,T:1,oL:15,SL:29,DL:57,W:6,H:27,oSL:43},MiddleImg:{L:0,T:140,oT:28,ST:56,DT:112,oST:84,H:27,Src:1},RightImg:{L:78,T:1,oL:22,SL:36,DL:64,W:6,H:27,oSL:50}},Edit:{LeftImg:{L:85,T:1,W:5,H:27,oL:97,SL:85,oSL:85,
DL:109,oDL:109},MiddleImg:{L:50,T:168,H:27,oT:196,ST:168,oST:168,DT:224,oDT:224,Src:1},RightImg:{L:91,T:1,W:5,H:27,oL:103,SL:91,oSL:91,DL:115,oDL:115},LeftImgReq:{L:121,T:1,W:5,H:27,DL:109},MiddleImgReq:{L:50,T:252,H:27,oT:252,DT:224,oDT:224,Src:1},RightImgReq:{L:127,T:1,W:5,H:27,DL:115},ArrowLeft:{L:140,T:133,W:12,H:26,oL:160,DL:180},ArrowRight:{L:139,T:113,W:12,H:26,oL:159,DL:179},ArrowUp:{L:139,T:94,W:14,H:26,oL:159,DL:179},ArrowDown:{L:140,T:76,W:14,H:26,oL:160,DL:180}},ElipsisButton:{L:457,T:1,
oL:485,DL:513,W:27,H:27},SearchButton:{L:217,T:1,oL:245,DL:273,W:27,H:27},Calendar:{EditButton:{L:301,T:1,oL:329,DL:357,W:27,H:27},ArrowLeft:{L:138,T:137,W:16,H:21,oL:158,DL:178},ArrowRight:{L:138,T:117,W:16,H:21,oL:158,DL:178},Header:{T:280,DT:333,Src:1},Footer:{T:325,DT:378,H:32,Src:1},WeekDays:{T:300,DT:353,H:22,Src:1},ImgDay:{L:-22,T:53,oL:276,DL:-22,W:22,H:22,SL:298,oSL:298},ImgNow:{L:342,T:53,DL:320,W:22,H:22,SL:298,oSL:298},FastButton:{LeftImg:{L:1,T:1,oL:15,W:6,H:27,SL:29,DL:57,oSL:43},MiddleImg:{L:0,
T:0,ST:56,oT:28,DT:112,oST:84,H:27,Src:1},RightImg:{L:8,T:1,oL:22,W:6,H:27,SL:36,DL:64,oSL:50}},Frame:{LeftTop:{L:10,T:110,W:2,H:3,DL:28},Top:{L:0,T:320,H:2,DT:373,Src:1},RightTop:{L:7,T:110,W:2,H:3,DL:24},Left:{L:1,T:0,W:2,DL:9,Src:2},Right:{L:6,T:0,W:2,DL:14,Src:2},LeftBottom:{L:10,T:115,W:2,H:2,DL:28},Bottom:{L:0,T:325,H:2,DT:378,Src:1},RightBottom:{L:7,T:115,W:2,H:2,DL:24}}},ColorPreview:{L:385,T:1,DL:421,W:35,H:27},DropDown:{L:133,T:1,oL:161,DL:189,W:27,H:27},DropDownBox:{LeftTop:{L:10,T:110,
W:2,H:2,DL:28},Top:{L:0,T:320,H:2,DT:373,Src:1},RightTop:{L:7,T:110,W:2,H:2,DL:25},Left:{L:1,T:0,W:2,DL:9,Src:2},Right:{L:6,T:0,W:2,DL:14,Src:2},LeftBottom:{L:10,T:115,W:2,H:2,DL:28},Bottom:{L:0,T:325,H:2,DT:378,Src:1},RightBottom:{L:7,T:115,W:2,H:2,DL:25}},List:{Box:{LeftTop:{L:10,T:110,W:2,H:3,DL:28},Top:{L:0,T:320,H:2,DT:373,Src:1},RightTop:{L:7,T:110,W:2,H:3,DL:24},Left:{L:1,T:0,W:2,DL:9,Src:2},Right:{L:6,T:0,W:2,DL:14,Src:2},LeftBottom:{L:10,T:115,W:2,H:2,DL:28},Bottom:{L:0,T:325,H:2,DT:378,
Src:1},RightBottom:{L:7,T:115,W:2,H:2,DL:24}},BoxCaption:{L:0,T:294,H:28,DT:347,Src:1},TreeImgTriangle:{L:138,T:78,W:16,H:20,DL:178,DSL:178,ST:116,DST:116}},Group:{Box:{LeftTop:{L:10,T:102,W:3,H:11,DL:28},Top:{L:0,T:312,H:11,DT:365,Src:1},RightTop:{L:6,T:102,W:3,H:11,DL:24},Left:{L:1,T:0,W:3,DL:9,Src:2},Right:{L:5,T:0,W:3,DL:13,Src:2},LeftBottom:{L:10,T:114,W:3,H:3,DL:28},Bottom:{L:0,T:324,H:3,DT:377,Src:1},RightBottom:{L:6,T:114,W:3,H:3,DL:24}},BoxNoText:{LeftTop:{L:10,T:110,W:3,H:3,DL:28},Top:{L:0,
T:320,H:3,DT:373,Src:1},RightTop:{L:6,T:110,W:3,H:3,DL:24},Left:{L:1,T:0,W:3,DL:9,Src:2},Right:{L:5,T:0,W:3,DL:13,Src:2},LeftBottom:{L:10,T:114,W:3,H:3,DL:28},Bottom:{L:0,T:324,H:3,DT:377,Src:1},RightBottom:{L:5,T:114,W:3,H:3,DL:24}}},Pages:{BoxUp:{LeftTop:{L:10,T:76,W:2,H:36,DL:28},LeftTop2:{L:10,T:76,W:2,H:36,DL:28},Top:{L:0,T:286,H:36,DT:339,Src:1},RightTop:{L:7,T:76,W:2,H:36,DL:24},RightTop2:{L:7,T:76,W:2,H:36,DL:24},Left:{L:1,T:0,W:2,DL:9,Src:2},Right:{L:6,T:0,W:2,DL:13,Src:2},LeftBottom:{L:10,
T:115,W:2,H:2,DL:28},Bottom:{L:0,T:325,H:2,DT:377,Src:1},RightBottom:{L:7,T:115,W:2,H:2,DL:24}},BoxDown:{LeftTop:{L:10,T:110,W:2,H:2,DL:28},Top:{L:0,T:320,H:2,DT:365,Src:1},RightTop:{L:7,T:110,W:2,H:2,DL:24},Left:{L:1,T:0,W:2,DL:9,Src:2},Right:{L:6,T:0,W:2,DL:13,Src:2},LeftBottom:{L:10,T:115,W:2,H:36,DL:28},LeftBottom2:{L:10,T:115,W:2,H:36,DL:28},Bottom:{L:0,T:325,H:36,DT:377,Src:1},RightBottom:{L:7,T:115,W:2,H:36,DL:24},RightBottom2:{L:7,T:115,W:2,H:36,DL:24}},PagesUp:new Array({LeftImg:{L:37,T:76,
W:8,H:39,SL:57,oL:117,oSL:57,DL:77,DSL:97},MiddleImg:{L:0,T:420,H:39,oT:494,DT:568,ST:644,oST:644,DST:724,Src:1},RightImg:{L:46,T:76,W:10,H:39,SL:66,oL:126,oSL:66,DL:86,DSL:106},Separator:{L:-100,T:-100,W:4,H:39}}),PagesDown:new Array({LeftImg:{L:37,T:116,W:8,H:39,SL:57,oL:117,oSL:57,DL:77,DSL:97},MiddleImg:{L:0,T:454,H:39,oT:528,DT:605,ST:684,oST:684,DST:764,Src:1},RightImg:{L:46,T:116,W:10,H:39,SL:66,oL:126,oSL:66,DL:86,DSL:106},Separator:{L:-100,T:-100,W:4,H:39}})},PagingFirst:{L:1,T:53,oL:93,
DL:185,W:22,H:22},PagingPrev:{L:24,T:53,oL:116,DL:208,W:22,H:22},PagingNext:{L:47,T:53,oL:139,DL:231,W:22,H:22},PagingLast:{L:70,T:53,oL:162,DL:254,W:22,H:22},PagingPage:{L:-22,T:53,oL:276,DL:320,W:22,H:22,SL:298,oSL:298},Window:{Frame:{LeftTop:{L:201,T:85,W:8,H:28,DL:219},Top:{L:0,T:814,H:8,DT:835,Src:1},RightTop:{L:210,T:85,W:8,H:28,DL:228},Left:{L:17,T:0,W:8,DL:29,Src:2},Right:{L:20,T:0,W:8,DL:32,Src:2},LeftBottom:{L:201,T:114,W:8,H:8,DL:219},Bottom:{L:0,T:817,H:8,DT:838,Src:1},RightBottom:{L:210,
T:114,W:8,H:8,DL:228}},Caption:{LeftImg:{L:-100,T:-100,W:8,H:28,DL:218},MiddleImg:{L:0,T:857,H:31,DT:889,Src:1},RightImg:{L:-100,T:-100,W:8,H:28,DL:227}},Buttons:{Close:{L:364,T:53,oL:387,W:24,H:22,DL:410},Minimize:{L:364,T:76,oL:387,W:24,H:22,DL:410},Maximize:{L:364,T:99,oL:387,SL:364,oSL:387,W:24,H:22,ST:122,DL:410,oST:122,DSL:410,DST:122}}},Hint:{Frame:{LeftTop:{L:201,T:85,W:8,H:8,DL:219},Top:{L:0,T:814,H:8,DT:835,Src:1},RightTop:{L:210,T:85,W:8,H:8,DL:228},Left:{L:17,T:0,W:8,DL:29,Src:2},Right:{L:20,
T:0,W:8,DL:32,Src:2},LeftBottom:{L:201,T:114,W:8,H:8,DL:219},Bottom:{L:0,T:817,H:8,DT:838,Src:1},RightBottom:{L:210,T:114,W:8,H:8,DL:228}},Anchors:{topleft:{L:7,T:-32,HX:13,HY:1,Img:{L:237,T:76,W:21,H:40,DL:301}},topcenter:{L:90,T:-32,HX:9,HY:1,Img:{L:259,T:76,W:19,H:40,DL:323}},topright:{R:7,T:-32,HX:8,HY:1,Img:{L:279,T:76,W:21,H:40,DL:343}},bottomleft:{L:7,B:-32,HX:13,HY:39,Img:{L:237,T:117,W:21,H:40,DL:301}},bottomcenter:{L:90,B:-32,HX:9,HY:39,Img:{L:259,T:117,W:19,H:40,DL:323}},bottomright:{R:7,
B:-32,HX:8,HY:39,Img:{L:279,T:117,W:21,H:40,DL:343}},lefttop:{L:-32,T:7,HX:1,HY:13,Img:{L:237,T:158,W:40,H:21,DL:319}},leftcenter:{L:-32,T:55,HX:1,HY:9,Img:{L:237,T:180,W:40,H:19,DL:319}},leftbottom:{L:-32,B:7,HX:1,HY:8,Img:{L:237,T:200,W:40,H:21,DL:319}},righttop:{R:-32,T:7,HX:39,HY:13,Img:{L:278,T:158,W:40,H:21,DL:360}},rightcenter:{R:-32,T:55,HX:39,HY:9,Img:{L:278,T:180,W:40,H:19,DL:360}},rightbottom:{R:-32,B:7,HX:39,HY:8,Img:{L:278,T:200,W:40,H:21,DL:360}}}},TextHint:{Frame:{LeftTop:{L:201,T:132,
W:4,H:4,DL:219},Top:{L:0,T:921,H:4,DT:939,Src:1},RightTop:{L:214,T:132,W:4,H:4,DL:232},Left:{L:41,T:0,W:4,DL:59,Src:2},Right:{L:54,T:0,W:4,DL:72,Src:2},LeftBottom:{L:201,T:145,W:4,H:4,DL:219},Bottom:{L:0,T:934,H:4,DT:952,Src:1},RightBottom:{L:214,T:145,W:4,H:4,DL:232}},Anchors:{topleft:{L:0,T:-19,HX:0,HY:0,Img:{L:401,T:146,W:21,H:27,DT:202}},topright:{R:0,T:-19,HX:21,HY:0,Img:{L:437,T:146,W:21,H:27,DT:202}},left:{L:-19,T:7,HX:0,HY:13,Img:{L:459,T:168,W:27,H:13,DT:226}},right:{R:-19,T:7,HX:27,HY:13,
Img:{L:487,T:168,W:27,H:13,DT:226}},bottomleft:{L:0,B:-19,HX:0,HY:27,Img:{L:401,T:174,W:21,H:27,DT:230}},bottomright:{R:0,B:-19,HX:21,HY:27,Img:{L:437,T:174,W:21,H:27,DT:230}}},NoAnchors:{topleft:{L:-2,T:-16,HX:0,HY:0},topright:{R:15,T:-16,HX:0,HY:0},bottomleft:{L:-2,B:-16,HX:0,HY:0},bottomright:{R:15,B:-16,HX:0,HY:0}}},Memo:{Frame:{LeftTop:{L:85,T:1,W:5,H:5,oL:97,SL:85,oSL:85,DL:109,oDL:109},Top:{L:0,T:168,H:5,oT:196,ST:168,oST:168,DT:224,oDT:224,Src:1},RightTop:{L:91,T:1,W:5,H:5,oL:103,SL:91,oSL:91,
DL:115,oDL:115},Left:{L:77,T:0,W:5,oL:105,SL:77,oSL:77,DL:133,oDL:133,Src:2},Right:{L:99,T:0,W:5,oL:127,SL:99,oSL:99,DL:155,oDL:155,Src:2},LeftBottom:{L:85,T:23,W:5,H:5,oL:97,SL:85,oSL:85,DL:109,oDL:109},Bottom:{L:0,T:190,H:5,oT:218,ST:190,oST:190,DT:246,oDT:246,Src:1},RightBottom:{L:91,T:23,W:5,H:5,oL:103,SL:91,oSL:91,DL:115,oDL:115}},ReqFrame:{LeftTop:{L:121,T:1,W:5,H:5,SL:121,oSL:121,DL:109,oDL:109},Top:{L:0,T:252,H:5,ST:252,oST:252,DT:224,oDT:224,Src:1},RightTop:{L:127,T:1,W:5,H:5,SL:127,oSL:127,
DL:115,oDL:115},Left:{L:161,T:0,W:5,SL:161,oSL:161,DL:133,oDL:133,Src:2},Right:{L:183,T:0,W:5,SL:183,oSL:183,DL:155,oDL:155,Src:2},LeftBottom:{L:121,T:23,W:5,H:5,SL:121,oSL:121,DL:109,oDL:109},Bottom:{L:0,T:274,H:5,ST:274,oST:274,DT:246,oDT:246,Src:1},RightBottom:{L:127,T:23,W:5,H:5,SL:127,oSL:127,DL:115,oDL:115}}},SplitPanel:{VSplit:{L:306,T:222,W:15,H:46,oL:322,SL:322,DL:338},VSplitNone:{L:-3,T:-1,W:3,H:1},HSplit:{L:354,T:222,W:46,H:15,oT:238,ST:238,DT:254},HSplitNone:{L:-1,T:-3,W:1,H:3}},DropPanel:{Left:{L:17,
T:0,W:8,DL:29,Src:2},Right:{L:20,T:0,W:8,DL:32,Src:2},BottomButton:{Left:{L:201,T:114,W:8,H:18,DL:219},Middle:{L:0,T:817,H:18,DT:838,Src:1},Right:{L:210,T:114,W:8,H:18,DL:228}},TopButton:{Left:{L:201,T:75,W:8,H:18,DL:219},Middle:{L:0,T:804,H:18,DT:825,Src:1},Right:{L:210,T:75,W:8,H:18,DL:228}},UpButton:{L:201,T:212,W:35,H:18,oT:230,DT:248,oDT:248,ST:158,oST:176,DST:194,oDST:194},DownButton:{L:201,T:158,W:35,H:18,oT:176,DT:194,oDT:194,ST:212,oST:230,DST:248,oDST:248}},Menu:{MenuButton:{L:136,T:75,
W:20,H:27,DL:176,oDL:176},SplitButton:{L:434,T:89,oL:455,oSL:455,DL:476,W:20,H:27,ST:117,oST:117,DSL:476,DST:117,oDL:476},SubMenu:{L:137,T:116,W:14,H:20,oL:157,DL:177,oDL:177},Caption:{L:0,T:294,H:28,DT:347,Src:1},Separator:{L:0,T:320,H:2,DT:373,Src:1},CheckBox:{L:303,T:30,W:16,H:20,oL:323,SL:341,oSL:361,GL:381,oGL:401,DL:421,DSL:441,DGL:461},Frame:{LeftTop:{L:10,T:110,W:2,H:3,DL:28},Top:{L:0,T:320,H:2,DT:373,Src:1},RightTop:{L:7,T:110,W:2,H:3,DL:24},Left:{L:1,T:0,W:2,DL:9,Src:2},Right:{L:6,T:0,W:2,
DL:14,Src:2},LeftBottom:{L:10,T:115,W:2,H:2,DL:28},Bottom:{L:0,T:325,H:2,DT:378,Src:1},RightBottom:{L:7,T:115,W:2,H:2,DL:24}}},MenuBar:{LeftImg:{L:-6,T:-27,W:6,H:27,oL:15,oT:1,SL:29,ST:1,DL:-6,DT:-27,oSL:43,oST:1},MiddleImg:{L:0,T:-27,ST:56,oT:28,DT:-27,oST:84,H:27,Src:1},RightImg:{L:-6,T:-27,W:6,H:27,oL:22,oT:1,SL:36,ST:1,DL:-6,DT:-27,oSL:50,oST:1}},ProgressBar:{LeftImg:{L:434,T:68,W:2,H:20,DL:442},MiddleImg:{L:0,T:957,H:20,DT:978,Src:1},RightImg:{L:438,T:68,W:3,H:20,DL:446},BarImg:{L:450,T:68,W:10,
H:20,DL:461}},EyeIcon:{L:1,T:157,W:26,H:27,oL:28,DL:55},LockIcon:{L:1,T:185,W:18,H:27,oL:20,DL:39},AimIcon:{L:1,T:213,W:21,H:27,oL:23,DL:45},PulseIcon:{L:1,T:241,W:18,H:27,oL:20,DL:39},ElipsisIcon:{L:95,T:156,W:27,H:27,oT:184,DT:212},SearchIcon:{L:123,T:156,W:27,H:27,oT:184,DT:212},CalendarIcon:{L:95,T:240,W:27,H:27,oL:123,DL:151}},OnControlCreated:function(p,i){switch(p.Type){case "wfrCheckBox":if(i.TextAlign=="right"||i.TextAlign=="center"){i.TextAlign="right";if(ng_EmptyVar(i.LeftImg))i.LeftImg=
this.Images.CheckBoxLeft;if(!i.OnGetClassName)i.OnGetClassName=function(){return"BtnLeft"}}else{i.TextAlign="left";if(ng_EmptyVar(i.RightImg))i.RightImg=this.Images.CheckBoxRight;if(!i.OnGetClassName)i.OnGetClassName=function(){return"BtnRight"}}break;case "wfrRadioButton":if(i.TextAlign=="right"||i.TextAlign=="center"){i.TextAlign="right";if(ng_EmptyVar(i.LeftImg))i.LeftImg=this.Images.RadioLeft;if(!i.OnGetClassName)i.OnGetClassName=function(){return"BtnLeft"}}else{i.TextAlign="left";if(ng_EmptyVar(i.RightImg))i.RightImg=
this.Images.RadioRight;if(!i.OnGetClassName)i.OnGetClassName=function(){return"BtnRight"}}break;case "wfrGroup":case "wfrGroupBox":if(ng_EmptyVar(i.Frame))i.Frame=i.Text==""&&!i.OnGetText?this.Images.Group.BoxNoText:this.Images.Group.Box;break;case "wfrPages":if(i.PagesVAlign=="bottom"){if(ng_EmptyVar(i.Frame)){i.Frame=ng_CopyVar(this.Images.Pages.BoxDown);if(i.PagesVisible)if(i.PagesAlign=="right")i.Frame.RightBottom=i.Frame.RightBottom2;else i.Frame.LeftBottom=i.Frame.LeftBottom2}if(ng_EmptyVar(i.PageImages)){i.PageImages=
this.Images.Pages.PagesDown;i.RowOverlap=1}}else{if(ng_EmptyVar(i.Frame)){i.Frame=ng_CopyVar(this.Images.Pages.BoxUp);if(i.PagesVisible)if(i.PagesAlign=="right")i.Frame.RightTop=i.Frame.RightTop2;else i.Frame.LeftTop=i.Frame.LeftTop2}if(ng_EmptyVar(i.PageImages)){i.PageImages=this.Images.Pages.PagesUp;i.RowOverlap=1}}break}},OnInit:function(){function p(a,b,d){if(typeof a.className==="undefined")a.className=a.Data&&a.Data.Invalid?"wfrEdit wfrEdit_Invalid":"wfrEdit";if(typeof a.DropDown!=="undefined"&&
typeof a.DropDown.className==="undefined")a.DropDown.className="wfrDropDown";(a=ngCreateControlAsType(a,"ngEdit",b,d))&&m.wfrEdit_AddProperties(a);return a}function i(a,b,d,g){if(typeof a.className==="undefined")a.className="wfrEdit";if(typeof a.DropDown!=="undefined"&&typeof a.DropDown.className==="undefined")a.DropDown.className="wfrDropDown";a=ngCreateControlAsType(a,ngVal(g,"wfrEdit"),b,d);if(!a)return a;var c=new ngButton;c.LeftImg=f.ElipsisButton;a.RightImg=null;c.OnClick=function(e){var h=
e.Owner?ngVal(e.Owner.Parent,null):null;h&&h.OnElipsis&&h.OnElipsis(e,h.GetText())};a.Buttons=new Array(c);a.Elipsis=function(){c.Click()};return a}function r(a,b,d,g){if(typeof a.className==="undefined")a.className="wfrEdit";if(typeof a.DropDown!=="undefined"&&typeof a.DropDown.className==="undefined")a.DropDown.className="wfrDropDown";b=ngCreateControlAsType(a,ngVal(g,"ngEditNum"),b,d);if(!b)return b;m.wfrEdit_AddProperties(b);a=ngVal(a.Arrows,"leftright");if(b.ButtonUp)b.ButtonUp.LeftImg=a=="leftright"?
f.Edit.ArrowRight:f.Edit.ArrowUp;if(b.ButtonDown)b.ButtonDown.LeftImg=a=="leftright"?f.Edit.ArrowLeft:f.Edit.ArrowDown;return b}function s(a,b,d,g){ng_MergeDef(a,{className:"wfrEdit",Data:{TextAlign:"center"},DropDown:null});a=ngDropDown_Create(a,b,d,ngVal(g,"ngEdit"));if(!a)return a;m.wfrEdit_AddProperties(a);a.DropDownButton.Img=f.ColorPreview;a.RightImg=null;a.GetColor=function(){var c=this.GetText();if(c.length>0&&c[0]==="#")c=c.substring(2,c.length);return c};a.DropDownButton.OnGetText=function(){var c=
this.Enabled?this.Parent.GetColor():"cccccc";c=c===""?"ffffff":c;this.Elm().style.backgroundColor="#"+c;return""};a.OnTextChanged=function(c){c.DropDownButton.Update()};return a}function n(a,b,d,g,c){if(typeof a.className==="undefined")a.className="wfrEdit";ng_MergeDef(a,{DropDown:{Type:"wfrListBox",Data:{Frame:f.DropDownBox}}});b=ngDropDown_Create(a,b,d,ngVal(g,"ngEdit"),c);if(!b)return b;m.wfrEdit_AddProperties(b);b.DropDownButton.LeftImg=f.DropDown;b.RightImg=null;if(typeof a.DropDown.className===
"undefined")a.DropDown.className="wfrDropDown";return b}function t(a,b,d,g){if(typeof a.className==="undefined")a.className="wfrEdit";if(typeof a.DropDown!=="undefined"&&typeof a.DropDown.className==="undefined")a.DropDown.className="wfrDropDown";b=ngCreateControlAsType(a,ngVal(g,"wfrEdit"),b,d);if(!b)return b;if(typeof a.DropDown!=="undefined")b.Suggestion=true;b.RightImg=null;var c=new ngButton;c.LeftImg=f.SearchButton;c.Default=true;c.OnClick=function(e){var h=e.Owner?ngVal(e.Owner.Parent,null):
null;h&&h.OnSearch&&h.OnSearch(e,h.GetText())};b.Buttons=new Array(c);b.Search=function(e){typeof e!=="undefined"&&this.SetText(e);c.Click()};return b}function u(a,b,d){if(typeof a.className==="undefined")a.className="wfrGroupBox";return ngCreateControlAsType(a,"ngGroup",b,d)}function v(a,b,d,g){if(typeof a.className==="undefined")a.className=a.Data&&a.Data.Invalid?"wfrMemo wfrMemoInvalid":"wfrMemo";var c=ngCreateControlAsType(a,ngVal(g,"ngMemo"),b,d);if(c){a=ngVal(c.Invalid,false);c.Frame=a?f.Memo.ReqFrame:
f.Memo.Frame;c.SetInvalid=function(e,h){c.Frame=e?f.Memo.ReqFrame:f.Memo.Frame;var j=c.Elm();if(j){var o=j.className,w=o.indexOf("_");j.className=w<0?e?"wfrMemo wfrMemoInvalid":"wfrMemo":(e?"wfrMemo wfrMemoInvalid":"wfrMemo")+j.className.substring(w,o.length)}c.Invalid=e;ngVal(h,true)&&c.Update()};c.AddEvent("OnFocus",function(e){if(e=e.Elm())if(e.className.indexOf("_")<0)e.className+="_Focus";return true});c.AddEvent("OnBlur",function(e){if(e=!e.MouseInControl?e.Elm():null){var h=e.className,j=h.indexOf("_");
if(j>=0)e.className=h.substring(0,j)}return true});c.AddEvent("DoMouseLeave",function(){var e=!c.ControlHasFocus?c.Elm():null;if(e){var h=e.className,j=h.indexOf("_");if(j>=0)e.className=h.substring(0,j)}return true});return c}}for(var k=ngLibPath("ng_wireframe"),q=0;q<this.ControlImages.length;q++)this.ControlImages[q]=k+"images/"+this.ControlImages[q];var f=this.Images,m=this;ngRegisterControlType("wfrPanel",function(a,b,d){return ngCreateControlAsType(a,"ngPanel",b,d)});ngRegisterControlType("wfrFrame",
function(a,b,d){return ngCreateControlAsType(a,"ngFrame",b,d)});ngRegisterControlType("wfrAlignPanel",function(a,b,d){return ngCreateControlAsType(a,"ngAlignPanel",b,d)});ngRegisterControlType("wfrAlignFrame",function(a,b,d){return ngCreateControlAsType(a,"ngAlignFrame",b,d)});ngRegisterControlType("wfrToolBar",function(a,b,d){if(typeof a.className==="undefined")a.className="wfrToolBar";return ngCreateControlAsType(a,"ngToolBar",b,d)});ngRegisterControlType("wfrText",function(a,b,d){if(typeof a.className===
"undefined")a.className="wfrText";return ngCreateControlAsType(a,"ngText",b,d)});ngRegisterControlType("wfrButton",function(a,b,d){if(typeof a.className==="undefined")a.className="wfrButton";if(b=ngCreateControlAsType(a,"ngButton",b,d)){if(ngVal(b.Default,false)){b.LeftImg=f.DefButton.LeftImg;b.MiddleImg=f.DefButton.MiddleImg;b.RightImg=f.DefButton.RightImg}else{b.LeftImg=f.Button.LeftImg;b.MiddleImg=f.Button.MiddleImg;b.RightImg=f.Button.RightImg}if(typeof a.Menu==="object"){b.Img=f.Menu.MenuButton;
b.ImgAlign="right"}}return b});ngRegisterControlType("wfrCheckBox",function(a,b,d){if(typeof a.className==="undefined")a.className="wfrCheckBox";return ngCreateControlAsType(a,"ngCheckBox",b,d)});ngRegisterControlType("wfrRadioButton",function(a,b,d){if(typeof a.className==="undefined")a.className="wfrRadio";return ngCreateControlAsType(a,"ngRadioButton",b,d)});ngRegisterControlType("wfrLabel",function(a,b,d){if(typeof a.className==="undefined")a.className="wfrLabel";return ngCreateControlAsType(a,
"ngButton",b,d)});ngRegisterControlType("wfrLink",function(a,b,d){if(typeof a.className==="undefined")a.className="wfrLink";return ngCreateControlAsType(a,"ngButton",b,d)});this.wfrEdit_AddProperties=function(a){var b=ngVal(a.Invalid,false);a.LeftImg=b?f.Edit.LeftImgReq:f.Edit.LeftImg;a.MiddleImg=b?f.Edit.MiddleImgReq:f.Edit.MiddleImg;a.RightImg=b?f.Edit.RightImgReq:f.Edit.RightImg;a.SetInvalid=function(d,g){if(d){if(a.LeftImg)a.LeftImg=f.Edit.LeftImgReq;if(a.MiddleImg)a.MiddleImg=f.Edit.MiddleImgReq;
if(a.RightImg)a.RightImg=f.Edit.RightImgReq}else{if(a.LeftImg)a.LeftImg=f.Edit.LeftImg;if(a.MiddleImg)a.MiddleImg=f.Edit.MiddleImg;if(a.RightImg)a.RightImg=f.Edit.RightImg}a.Elm().className=!d?"wfrEdit":"wfrEdit wfrEdit_Invalid";a.Invalid=d;if(ngVal(g,true)){a.LeftImg&&ngc_ChangeImage(ngpg_ImgDrawProps(a.ID+"_IL",0,a.Enabled,a.LeftImg));a.MiddleImg&&ngc_ChangeImageS(ngpg_ImgDrawProps(a.ID+"_IM",0,a.Enabled,a.MiddleImg));a.RightImg&&ngc_ChangeImage(ngpg_ImgDrawProps(a.ID+"_IR",0,a.Enabled,a.RightImg))}}};
ngRegisterControlType("wfrEdit",p);ngRegisterControlType("wfrEditBox",p);ngRegisterControlType("wfrEditBoxBtn",function(a,b,d){return i(a,b,d)});ngRegisterControlType("wfrEditNum",function(a,b,d){return r(a,b,d)});ngRegisterControlType("wfrEditBoxNum",function(a,b,d){return r(a,b,d)});ngRegisterControlType("wfrColorEdit",function(a,b,d){return s(a,b,d)});ngRegisterControlType("wfrColorEditBox",function(a,b,d){return s(a,b,d)});ngRegisterControlType("wfrDropDown",function(a,b,d){return n(a,b,d,"ngEdit",
false)});ngRegisterControlType("wfrDropDownList",function(a,b,d){return n(a,b,d,"ngEdit",true)});ngRegisterControlType("wfrSearchBox",function(a,b,d){return t(a,b,d)});if(ngUserControls.list){k=function(a,b,d){if(typeof a.className==="undefined")a.className="wfrListBox";b=ngCreateControlAsType(a,"ngList",b,d);if(!b)return b;b.AddEvent("DoUpdate",function(g){var c=g.className,e=c.indexOf(" ");if(this.Enabled){if(e>=0)g.className=c.substring(0,e)}else if(e<0)g.className=c+" "+c+"Disabled";return true});
b.OnGetCheckImg=function(g,c){if(typeof c.Checked==="undefined"&&!g.ShowCheckboxes)return null;if(typeof c.RadioGroup!=="undefined")return f.RadioLeft;return f.CheckBoxLeft};if(a.Type=="wfrTreeList")b.TreeImg=f.List.TreeImgTriangle;b.AddEvent("OnUpdated",function(g){if(g.Columns.length>0&&(typeof g.ShowHeader==="undefined"||g.ShowHeader===true)){var c='url("'+f.List.BoxCaption.Src+'") repeat-x scroll 0px -';c+=g.Enabled?f.List.BoxCaption.T?f.List.BoxCaption.T:0:f.List.BoxCaption.DT?f.List.BoxCaption.DT:
0;c+="px";var e=document.getElementById(g.ID+"_TB");g=document.getElementById(g.ID+"_TH");if(e&&e.children[0])if((e=e.children[0])&&e.nodeName==="THEAD")e.children[0].style.background=c;if(g&&g.children[0])if((e=g.children[0])&&e.nodeName==="THEAD")e.children[0].style.background=c}return true});b.Frame=f.List.Box;return b};ngRegisterControlType("wfrList",k);ngRegisterControlType("wfrListBox",k);ngRegisterControlType("wfrTreeList",k);this.wfrPageListPagingControlsDef=function(){return{FirstPage:{Type:"ngButton",
className:"wfrPgListPagingButton",Data:{ToolBarHPadding:5,Img:f.PagingFirst,Text:""}},PrevPage:{Type:"ngButton",className:"wfrPgListPagingButton",Data:{ToolBarHPadding:5,Img:f.PagingPrev,Text:""}},PageNo:{Type:"wfrEdit",W:30,Data:{ToolBarHPadding:5,Text:"1",TextAlign:"center"}},Page0:{Type:"ngButton",className:"wfrPgListPagingButton",Data:{ToolBarHPadding:5,MinWidth:22,MiddleImg:f.PagingPage,Text:"1",TextAlign:"center"}},NextPage:{Type:"ngButton",className:"wfrPgListPagingButton",Data:{Img:f.PagingNext,
Text:"",ImgAlign:"right",ToolBarHPadding:5}},LastPage:{Type:"ngButton",className:"wfrPgListPagingButton",Data:{Img:f.PagingLast,ImgAlign:"right",Text:""}}}};var x=function(a,b,d,g){ng_MergeDef(a,{className:"wfrListBox",Controls:{List:{Type:a.Type&&a.Type==="wfrPageTreeList"?"wfrTreeList":"wfrList"},Loading:{Type:"wfrProgressDot",L:15,T:g==="ngDataSet"||g==="ngDBDataSet"||a.Controls&&a.Controls.List&&a.Controls.List.Data&&a.Controls.List.Data.Columns&&a.Controls.List.Data.Columns.length>0?43:15,Data:{Visible:false}},
Paging:{H:27,className:"wfrPageListPaging",Controls:m.wfrPageListPagingControlsDef()}}});a=ngCreateControlAsType(a,ngVal(g,"ngPageList"),b,d);if(!a)return a;a.AddEvent("DoUpdate",function(c){var e=c.className,h=e.indexOf(" ");if(this.Enabled){if(h>=0)c.className=e.substring(0,h)}else if(h<0)c.className=e+" "+e+"Disabled";return true});return a};ngRegisterControlType("wfrPageList",function(a,b,d){return x(a,b,d,"ngPageList")});ngRegisterControlType("wfrPageTreeList",function(a,b,d){return x(a,b,d,
"ngPageList")})}ngRegisterControlType("wfrGroup",u);ngRegisterControlType("wfrGroupBox",u);ngRegisterControlType("wfrPages",function(a,b,d){if(typeof a.className==="undefined")a.className="wfrPages";ng_MergeDef(a,{ControlsPanel:{L:5,T:5,R:5,B:5}});return ngCreateControlAsType(a,"ngPages",b,d)});if(ngUserControls.window){k=function(a,b,d){var g=a.Type=="wfrDialog";if(typeof a.className==="undefined")a.className=g?"wfrDialog":"wfrWindow";var c=ngCreateControlAsType(a,"ngWindow",b,d);if(!c)return c;
c.Frame=f.Window.Frame;c.CaptionImg=f.Window.Caption;if(g){c.Modal=true;c.Visible=false;c.Sizeable=false;c.Centered=true}if(ngVal(a.CloseBtn,g?true:false)){b=new ngButton;c.CloseButton=b;b.LeftImg=f.Window.Buttons.Close;b.OnClick=function(e){(e=e.Owner?ngVal(e.Owner.Parent,null):null)&&e.Close&&e.Close(e)};if(!c.Buttons)c.Buttons=[];c.Buttons[c.Buttons.length]=b}if(ngVal(a.MaxBtn,false)){b=new ngButton;c.MaxButton=b;c.OnDblClick=function(e){e.win&&e.win.MaxButton&&e.win.MaxButton.Click()};c.AddEvent(function(){var e=
c.IsMaximized()?1:0;c.MaxButton&&c.MaxButton.Checked!=e&&c.MaxButton.Check(e);return true},"DoUpdate");b.LeftImg=f.Window.Buttons.Maximize;b.OnClick=function(e){var h=e.Owner?ngVal(e.Owner.Parent,null):null;if(h){e.Owner.Check(h.IsMaximized()?0:1);if(e.Owner.Checked)h.Maximize&&h.Maximize(h);else h.Restore&&h.Restore(h)}};if(!c.Buttons)c.Buttons=[];c.Buttons[c.Buttons.length]=b}if(ngVal(a.MinBtn,false)){b=new ngButton;c.MinButton=b;b.LeftImg=f.Window.Buttons.Minimize;c.AddEvent(function(){var e=c.IsMinimized()?
1:0;c.MinButton&&c.MinButton.Checked!=e&&c.MinButton.Check(e);return true},"DoUpdate");b.OnClick=function(e){var h=e.Owner?ngVal(e.Owner.Parent,null):null;if(h){e.Owner.Check(h.IsMinimized()?0:1);if(e.Owner.Checked)h.Minimize&&h.Minimize(h);else h.Restore&&h.Restore(h)}};if(!c.Buttons)c.Buttons=[];c.Buttons[c.Buttons.length]=b}return c};ngRegisterControlType("wfrWindow",k);ngRegisterControlType("wfrDialog",k);ngRegisterControlType("wfrHint",function(a,b,d){if(typeof a.className==="undefined")a.className=
"wfrHint";if(a=ngCreateControlAsType(a,"ngHint",b,d)){a.Frame=ng_CopyVar(f.Hint.Frame);a.Anchors=ng_CopyVar(f.Hint.Anchors)}return a});ngRegisterControlType("wfrTextHint",function(a,b,d){var g=a.Data&&a.Data.showAnchors===false?false:true;ng_MergeDef(a,{className:"wfrTextHint",Data:{showAnchors:g,Frame:f.TextHint.Frame,Anchors:g?f.TextHint.Anchors:f.TextHint.NoAnchors},Controls:{Hint:{Type:"wfrText",L:5,T:2}}});return ngCreateControlAsType(a,"ngTextHint",b,d)})}if(ngUserControls.calendar){ngRegisterControlType("wfrCalendar",
function(a,b,d){ng_MergeDef(a,{className:"wfrCalendar",Data:{Frame:f.Calendar.Frame},Events:{OnUpdated:function(g){var c=document.getElementById(g.ID+"_Head"),e='url("'+f.Calendar.Header.Src+'") repeat-x scroll 0px -',h=g.Enabled?f.Calendar.Header.T?f.Calendar.Header.T:0:f.Calendar.Header.DT?f.Calendar.Header.DT:0;h+=g.YearNavigation?0:+21;e+=h+"px";c.style.background=e;c=document.getElementById(g.ID+"_Foot");e='url("'+f.Calendar.Footer.Src+'") repeat-x scroll 0px -';h=g.Enabled?f.Calendar.Footer.T?
f.Calendar.Footer.T:0:f.Calendar.Footer.DT?f.Calendar.Footer.DT:0;e+=h+"px";h=f.Calendar.Footer.H?f.Calendar.Footer.H:0;c.style.background=e;c.style.height=h+"px";c=document.getElementById(g.ID+"_WeekDays");e='url("'+f.Calendar.WeekDays.Src+'") repeat-x scroll 0px -';h=g.Enabled?f.Calendar.WeekDays.T?f.Calendar.WeekDays.T:0:f.Calendar.WeekDays.DT?f.Calendar.WeekDays.DT:0;e+=h+"px";h=f.Calendar.WeekDays.H?f.Calendar.WeekDays.H:0;c.style.background=e;c.style.height=h+"px";return true}}});a=ngCreateControlAsType(a,
"ngCalendar",b,d);if(!a)return a;a.PrevMonBtn.LeftImg=f.Calendar.ArrowLeft;a.PrevMonBtn.Text="";a.NextMonBtn.LeftImg=f.Calendar.ArrowRight;a.NextMonBtn.Text="";a.PrevYearBtn.LeftImg=f.Calendar.ArrowLeft;a.PrevYearBtn.Text="";a.NextYearBtn.LeftImg=f.Calendar.ArrowRight;a.NextYearBtn.Text="";a.ImgDay=f.Calendar.ImgDay;a.ImgNow=f.Calendar.ImgNow;for(b=0;b<a.FastButtons.length;b++){d=a.FastButtons[b];d.LeftImg=f.Calendar.FastButton.LeftImg;d.MiddleImg=f.Calendar.FastButton.MiddleImg;d.RightImg=f.Calendar.FastButton.RightImg}return a});
var y=function(a,b,d,g){ng_MergeDef(a,{className:"wfrEdit",DropDown:{className:"wfrCalendar",Type:"wfrCalendar"}});a=n(a,b,d,ngVal(g,"ngEditDate"),false);if(!a)return a;a.DropDownButton.LeftImg=f.Calendar.EditButton;a.RightImg=null;return a};ngRegisterControlType("wfrEditDate",function(a,b,d){return y(a,b,d)})}ngRegisterControlType("wfrMemo",function(a,b,d){return v(a,b,d)});if(ngUserControls.panels){ngRegisterControlType("wfrSplitPanel",function(a,b,d){if(typeof a.className==="undefined")a.className=
"wfrSplitPanel";if(b=ngCreateControlAsType(a,"ngSplitPanel",b,d)){d=b.PanelAlign=="left"||b.PanelAlign=="right";a=ngVal(a.Mover,"handle");b.HandleImg=a=="none"?d?f.SplitPanel.VSplitNone:f.SplitPanel.HSplitNone:d?f.SplitPanel.VSplit:f.SplitPanel.HSplit}return b});ngRegisterControlType("wfrDropPanel",function(a,b,d){if(typeof a.className==="undefined")a.className="wfrDropPanel";b=ngCreateControlAsType(a,"ngDropPanel",b,d);ng_MergeDef(a,{ControlsPanel:{Type:"ngGroup",ControlsPanel:{style:{backgroundColor:"#FFFFFF"}},
Data:{Frame:{Left:f.DropPanel.Left,Right:f.DropPanel.Right}}},Button:{Data:{OnGetImg:function(g,c){var e=null;g=g.Owner&&typeof g.Owner.Bounds.T=="undefined";switch(c){case -1:e=g?f.DropPanel.DownButton:f.DropPanel.UpButton;break;case 0:e=g?f.DropPanel.TopButton.Left:f.DropPanel.BottomButton.Left;break;case 1:e=g?f.DropPanel.TopButton.Middle:f.DropPanel.BottomButton.Middle;break;case 2:e=g?f.DropPanel.TopButton.Right:f.DropPanel.BottomButton.Right;break}return ngVal(e,null)}}},Events:{OnDropDown:function(g){if(g=
g.Button){delete ngMouseInControls[g.ID];g.MouseInControl=false}return true}}});return b})}if(ngUserControls.menu){ngRegisterControlType("wfrMenu",function(a,b,d){ng_MergeDef(a,{className:"wfrMenu",Data:{SubMenuImg:f.Menu.SubMenu,SubMenuDef:{Type:"wfrMenu"},Frame:f.Menu.Frame,SeparatorImg:f.Menu.Separator}});a=ngCreateControlAsType(a,"ngMenu",b,d);if(!a)return a;a.OnGetCheckImg=function(g,c){if(typeof c.Checked==="undefined"||!g.ShowCheckboxes)return null;return WireframeControls.Images.Menu.CheckBox};
a.AddEvent("DoUpdate",function(g){var c=g.className,e=c.indexOf(" ");if(this.Enabled){if(e>=0)g.className=c.substring(0,e)}else if(e<0)g.className=c+" "+c+"Disabled";return true});a.AddEvent("OnUpdated",function(g){if(g.Columns.length>0&&g.ShowHeader===true){var c='url("'+f.Menu.Caption.Src+'") repeat-x scroll 0px -';c+=g.Enabled?f.Menu.Caption.T?f.Menu.Caption.T:0:f.Menu.Caption.DT?f.Menu.Caption.DT:0;c+="px";var e=document.getElementById(g.ID+"_TB");g=document.getElementById(g.ID+"_TH");if(e&&e.children[0])if((e=
e.children[0])&&e.nodeName==="THEAD")e.children[0].style.background=c;if(g&&g.children[0])if((e=g.children[0])&&e.nodeName==="THEAD")e.children[0].style.background=c}return true});a.DrawItemText=function(g,c,e,h){var j=this.BaseClassName;if((this.Columns.length>0?ngVal(c.Text[this.Columns[0].ID],""):c.Text)==="-"){c.Visible=false;var o=this.Items[0]==c||this.Items[this.Items.length-1]==c;if(this.OnDrawSeparator)this.OnDrawSeparator(g,c,e,h);else{c="";if(this.SeparatorImg){c="background: url('"+this.SeparatorImg.Src+
"') repeat-x scroll 0px -";c+=this.Enabled?this.SeparatorImg.T?this.SeparatorImg.T:0:this.SeparatorImg.DT?this.SeparatorImg.DT:0;c+="px;"}this.Columns.length>0?g.append('<tr id="'+this.ID+"_"+e+'" class="'+j+'Row" style="'+(o?"display:none;":"")+'"><td colspan="'+this.Columns.length+'" class="'+j+'SeparatorCell"><div class="'+j+'Separator" style="'+c+'">&nbsp;</div></td></tr>'):g.append('<div id="'+this.ID+"_"+e+'" class="'+j+'Separator" style="'+(o?"display:none; ":"")+c+'"></div>')}}else this.DefaultDrawItemText(g,
c,e,h)};return a});ngRegisterControlType("wfrMenuBar",function(a,b,d){if(typeof a.className==="undefined")a.className="wfrMenuBar";return ngCreateControlAsType(a,"ngMenuBar",b,d)});ngRegisterControlType("wfrMenuBarButton",function(a,b,d){a=ngCreateControlAsType(a,"ngMenuBarButton",b,d);if(!a)return a;a.LeftImg=f.MenuBar.LeftImg;a.MiddleImg=f.MenuBar.MiddleImg;a.RightImg=f.MenuBar.RightImg;return a});ngRegisterControlType("wfrSplitButton",function(a,b,d){if(typeof a.className==="undefined")a.className=
"wfrSplitButton";a=ngCreateControlAsType(a,"ngSplitButton",b,d);if(!a)return a;a.LeftImg=f.Button.LeftImg;a.MiddleImg=f.Button.MiddleImg;a.RightImg=f.Menu.SplitButton;return a})}if(ngUserControls.dialogs){ngRegisterControlType("wfrMessageDlg",function(a,b,d){ng_MergeDef(a,{DialogType:"wfrDialog",Controls:{Message:{Type:"wfrText"},Content:{Type:"ngPanel",L:15,R:15,H:15},Buttons:{Type:"wfrToolBar",H:27,Data:{HPadding:10},Controls:{OK:{Type:"wfrButton",W:80},Yes:{Type:"wfrButton",W:80},No:{Type:"wfrButton",
W:80},Cancel:{Type:"wfrButton",W:80}}}}});if(typeof a.DlgCheckBox!=="undefined"){ng_MergeDef(a,{Controls:{Content:{Controls:{CheckBox:{Type:"wfrCheckBox",L:0,B:10,Data:a.DlgCheckBox}}}}});a.Controls.Content.H+=30}if(a.DialogType==="wfrMessageDlg")a.DialogType="wfrDialog";return ngCreateControlAsType(a,"ngMessageDlg",b,d)});ngRegisterControlType("wfrDlgMessageBox",function(a,b,d){delete a.DialogType;a.DlgButtons=ngVal(a.DlgButtons,mbOK);a.DlgIcon=ngVal(a.DlgIcon,null);var g=null;if(typeof a.DlgIcon===
"object")g=a.DlgIcon;else if(typeof a.DlgIcon!=="undefined")g=ngVal(f[a.DlgIcon],null);if(g){ng_MergeDef(a,{Controls:{Message:{L:15+g.W+10,T:25,Data:{MinHeight:typeof a.DlgCheckBox!=="undefined"?g.H>=30?g.H-30:0:g.H-10}},Icon:{Type:"ngImage",L:15,T:20,W:g.W,H:g.H,Data:{Img:g}},Content:{H:20,Controls:{}}}});if(a.Controls.Content.Controls.Check)a.Controls.Content.Controls.Check.L=g.W+10}return ngCreateControlAsType(a,"wfrMessageDlg",b,d)});k=function(a,b,d){delete a.DialogType;a.DlgAllowEmpty=ngVal(a.DlgAllowEmpty,
false);var g={DialogType:"wfrMessageDlg",DlgButtons:mbOK|mbCancel,Controls:{Message:{Data:{MinWidth:250}},Content:{H:40,Controls:{Edit:{Type:"wfrEdit",L:0,T:2,R:0,Data:{}}}},Buttons:{Controls:{OK:{Data:{}}}}}},c=g.Controls.Content.Controls.Edit;switch(a.Type){case "wfrDlgMemoBox":c.Type="wfrMemo";c.H=100;g.Controls.Content.H=120;break;case "wfrDlgDropDownBox":c.Type="wfrDropDown";c.DropDown={Type:"wfrList",Data:{}};if(typeof a.DlgItems!=="undefined")c.DropDown.Data.Items=a.DlgItems;break;case "wfrDlgDropDownListBox":c.Type=
"wfrDropDownList";c.DropDown={Type:"wfrList",Data:{}};if(typeof a.DlgItems!=="undefined")c.DropDown.Data.Items=a.DlgItems;break;case "wfrDlgDropDownTreeListBox":c.Type="wfrDropDownList";c.DropDown={Type:"wfrTreeList",Data:{}};if(typeof a.DlgItems!=="undefined")c.DropDown.Data.Items=a.DlgItems;break}if(typeof a.DlgHint!=="undefined")c.Data.Hint=a.DlgHint;if(!a.DlgAllowEmpty){c.Data.OnTextChanged=function(e){e.Owner.OK.SetEnabled(e.GetText()!=="");return true};g.Controls.Buttons.Controls.OK.Data.Enabled=
false}ng_MergeDef(a,g);b=ngCreateControlAsType(a,"wfrMessageDlg",b,d);a.Type!=="wfrDlgDropDownListBox"&&a.Type!=="wfrDlgDropDownTreeListBox"&&b.AddEvent("OnVisibleChanged",function(e){var h,j=e.Controls.Edit;h=j.OnGetHint?ngVal(j.OnGetHint(j),""):j.Hint;e.Visible&&h==""&&j.SetFocus()});return b};ngRegisterControlType("wfrDlgInputBox",k);ngRegisterControlType("wfrDlgDropDownBox",k);ngRegisterControlType("wfrDlgDropDownListBox",k);ngRegisterControlType("wfrDlgDropDownTreeListBox",k);ngRegisterControlType("wfrDlgMemoBox",
k);ngRegisterControlType("wfrDlgListBox",function(a,b,d){delete a.DialogType;a.DlgAllowEmpty=ngVal(a.DlgAllowEmpty,false);var g={DialogType:"wfrMessageDlg",DlgButtons:mbOK|mbCancel,Data:{},Controls:{Message:{Data:{MinWidth:300}},Content:{H:265,Controls:{List:{Type:"wfrList",L:0,T:2,R:0,H:250,Data:{SelectType:nglSelectSingle}}}},Buttons:{Controls:{OK:{Data:{}}}}}},c=g.Controls.Content.Controls.List;if(typeof a.DlgItems!=="undefined")c.Data.Items=a.DlgItems;if(!a.DlgAllowEmpty){c.Data.OnSelectChanged=
function(e){e.Owner.OK.SetEnabled&&e.Owner.OK.SetEnabled(e.SelCount>0);return true};g.Controls.Buttons.Controls.OK.Data.Enabled=false}ng_MergeDef(a,g);a=ngCreateControlAsType(a,"wfrMessageDlg",b,d);a.AddEvent("OnVisibleChanged",function(e){e.Visible&&e.Controls.List.SetFocus()});return a});ngRegisterControlType("wfrDlgProgressBox",function(a,b,d){delete a.DialogType;ng_MergeDef(a,{DlgButtons:mbNone,Data:{},Controls:{Message:{Data:{MinWidth:250}},Content:{H:30,Controls:{Progress:{Type:"wfrProgressBar",
L:0,T:5,R:0}}}}});return ngCreateControlAsType(a,"wfrMessageDlg",b,d)});ngRegisterControlType("wfrDlgWaitBox",function(a,b,d){delete a.DialogType;ng_MergeDef(a,{DlgButtons:mbNone,Data:{},Controls:{Message:{L:45,Data:{}},Progress:{Type:"wfrProgressDot",L:15,T:13},Content:{Data:{Visible:false}}}});return ngCreateControlAsType(a,"wfrMessageDlg",b,d)});ngRegisterControlType("wfrDlgAbout",function(a,b,d){var g={DialogType:"wfrDlgMessageBox",DlgIcon:null,Controls:{Message:{className:"wfrAboutMessage",Data:{MinWidth:260}},
Content:{H:220,Controls:{AppInfo:{Type:"wfrTreeList",H:200,TreeImg:"triangle",Data:{Frame:null,DefaultIndent:0}}}},Buttons:{H:47,Data:{VAlign:"bottom"}}}};if(typeof a.DlgIcon==="object"&&a.DlgIcon)g.Controls.Message.Data.MinWidth-=a.DlgIcon.W+10;ng_MergeDef(a,g);return ngCreateControlAsType(a,"ngAboutDlg",b,d)})}ngRegisterControlType("wfrProgressBar",function(a,b,d){if(typeof a.className==="undefined")a.className="wfrProgressBar";ng_MergeDef(a,{Data:{LeftImg:f.ProgressBar.LeftImg,MiddleImg:f.ProgressBar.MiddleImg,
RightImg:f.ProgressBar.RightImg,BarImg:f.ProgressBar.BarImg}});return ngCreateControlAsType(a,"ngProgressBar",b,d)});ngRegisterControlType("wfrProgressDot",function(a,b,d){ng_MergeDef(a,{className:"wfrLabel",Data:{TextAlign:"center"}});(a=ngCreateControlAsType(a,"ngButton",b,d))&&a.AddEvent(function(g){g=ngTxt(g.Text);if(g!=="")g='&nbsp;<span style="line-height: 22px">'+g+"</span>";return'<img src="'+WireframeControls.ControlImages[3]+'" align="top" />'+g},"OnGetText");return a});if(ngUserControls.viewmodel_controls){var z=
function(a,b,d,g){ng_MergeDef(a,{ErrorHint:{Type:"wfrTextHint",className:"wfrEditFieldError"}});(a=ngCreateControlAsType(a,ngVal(g,"ngViewModelForm"),b,d))&&a.AddEvent("OnShowErrorMsg",function(c,e){typeof ngMessageDlg==="function"?ngMessageDlg("dlgMessageBox",e,typeof c.Caption==="undefined"?ngTxt("ngAppName"):ngTxt(c.Caption),null,{DlgIcon:mbIconError}):alert(e);return true});return a};ngRegisterControlType("wfrViewModelForm",function(a,b,d){return z(a,b,d)});var l=function(a){ng_MergeDef(a,{Data:{HintX:10,
HintY:17},ErrorHint:{Type:"wfrTextHint",className:"wfrEditFieldError",Data:{Anchor:"topleft|bottomleft|left"}}})};ngRegisterControlType("wfrEditField",function(a,b,d){l(a);if(typeof a.className==="undefined")a.className="wfrEdit";if(typeof a.DropDown!=="undefined"&&typeof a.DropDown.className==="undefined")a.DropDown.className="wfrDropDown";(a=ngCreateControlAsType(a,"ngEditField",b,d))&&m.wfrEdit_AddProperties(a);return a});ngRegisterControlType("wfrSearchBoxField",function(a,b,d){return t(a,b,d,
"wfrEditField")});ngRegisterControlType("wfrEditBoxBtnField",function(a,b,d){return i(a,b,d,"wfrEditField")});ngRegisterControlType("wfrEditNumField",function(a,b,d){l(a);return r(a,b,d,"ngEditNumField")});ngRegisterControlType("wfrColorEditField",function(a,b,d){l(a);return s(a,b,d,"ngDropDownField")});ngRegisterControlType("wfrDropDownField",function(a,b,d){l(a);return n(a,b,d,"ngDropDownField",false)});ngRegisterControlType("wfrDropDownListField",function(a,b,d){l(a);return n(a,b,d,"ngDropDownListField",
true)});ngRegisterControlType("wfrEditDateField",function(a,b,d){l(a);return y(a,b,d,"ngEditDateField")});ngRegisterControlType("wfrEditTimeField",function(a,b,d){l(a);return Create_wfrEditTime(a,b,d,"ngEditTimeField")});ngRegisterControlType("wfrMemoField",function(a,b,d){l(a);return v(a,b,d,"ngMemoField")})}}};ngUserControls.wfs=WireframeControls;
