/*!
 * Controls.js - wineight.js
 * http://controlsjs.com/
 *
 * Copyright (c) 2014 Position s.r.o.  All rights reserved.
 *
 * This version of Controls.js is licensed under the terms of GNU General Public License v3.
 * http://www.gnu.org/licenses/gpl-3.0.html
 *
 * The commercial license can be purchased at Controls.js website.
 */








if(typeof ngUserControls==="undefined")ngUserControls=[];
var WE_DARK=0,WE_LIGHT=1,WinEightControls={Theme:WE_LIGHT,ColorScheme:"Green",BackgroundColor:"Auto",InvTheme:function(l){return ngVal(l,this.Theme)===WE_DARK?WE_LIGHT:WE_DARK},ControlImages:["img/we_base.png?1","img/we_hbox.png?1","img/we_vbox.png?1","img/we_icons.png?1","img/progressline_black.gif?1","img/progressline_white.gif?1","img/progressring_black.gif?1","img/progressring_white.gif?1","img/progressdot_black.gif?1","img/progressdot_white.gif?1"],Images:{ToggleSwitchLight:{L:0,T:122,W:50,H:19,
SL:102,DL:204,DSL:255,oL:51,oSL:153},ToggleSwitchDark:{L:0,T:147,W:50,H:19,SL:102,DL:204,DSL:255,oL:51,oSL:153},CheckBoxLeftLight:{L:0,T:5,W:31,H:32,SL:64,DL:0,DSL:128,GL:160,oL:32,oSL:96,oGL:193},CheckBoxLeftDark:{L:224,T:5,W:31,H:32,SL:288,DL:224,DSL:353,GL:385,oL:256,oSL:320,oGL:417},CheckBoxRightLight:{L:-10,T:5,W:31,H:32,SL:54,DL:-10,DSL:118,GL:150,oL:22,oSL:86,oGL:183},CheckBoxRightDark:{L:214,T:5,W:31,H:32,SL:278,DL:214,DSL:343,GL:375,oL:246,oSL:310,oGL:407},ListCheckBoxLight:{L:0,T:4,W:27,
H:34,SL:64,DL:0,DSL:128,GL:160},ListCheckBoxDark:{L:224,T:4,W:27,H:34,SL:288,DL:224,DSL:353,GL:385,oL:0,oSL:64,oGL:160},RadioLeftLight:{L:0,T:39,W:32,H:32,SL:68,DL:0,DSL:136,oL:34,oSL:102},RadioLeftDark:{L:170,T:39,W:32,H:32,SL:238,DL:170,DSL:306,oL:204,oSL:272},RadioRightLight:{L:-9,T:39,W:32,H:32,SL:59,DL:-9,DSL:127,oL:25,oSL:93},RadioRightDark:{L:161,T:39,W:32,H:32,SL:229,DL:161,DSL:297,oL:195,oSL:263},ListRadioLight:{L:0,T:38,W:28,H:34,SL:68,DL:0,DSL:136},ListRadioDark:{L:170,T:38,W:28,H:34,SL:238,
DL:170,DSL:306,oL:0,oSL:68},TreeImgDark:{ST:768,W:22,H:34,SL:43,DL:77,DSL:76,Src:3,L:44,T:865,DT:865,DST:768,oL:11,oSL:9,oST:768},TreeImgLight:{ST:768,W:22,H:34,SL:10,DL:77,DSL:76,Src:3,L:11,T:865,DT:865,DST:768},TreeImgSelLight:{ST:768,W:22,H:34,SL:43,DL:77,DSL:76,Src:3,L:44,T:865,DT:865,DST:768},DropDownTreeImgDark:{ST:768,W:22,H:34,SL:43,DL:77,DSL:76,Src:3,L:44,T:865,DT:865,DST:768,oL:11,oSL:9,oST:768},DropDownTreeImgLight:{ST:768,W:22,H:34,SL:10,DL:77,DSL:76,Src:3,L:11,T:865,DT:865,DST:768,oL:44,
oSL:43,oST:768},AboutTreeImgDark:{ST:775,W:22,H:19,SL:43,DL:77,DSL:76,Src:3,L:44,T:872,DT:872,DST:775},AboutTreeImgLight:{ST:775,W:22,H:19,SL:10,DL:77,DSL:76,Src:3,L:11,T:872,DT:872,DST:775},AppButtonLight:{L:0,T:79,SL:68,DL:136,W:33,H:32,oL:34,oSL:102},AppButtonDark:{L:170,T:79,SL:238,DL:136,W:33,H:32,oL:204,oSL:272},ButtonLight:{MiddleImg:{L:0,T:-32,H:32,DT:264,Src:1,oT:297,ST:330,oST:429},MenuRightImg:{L:1,T:243,W:27,H:32,SL:89,DL:59,oL:29,oSL:119},MenuRightBtnImg:{L:0,T:243,W:28,H:32,SL:88,DL:58,
oL:28,oSL:118}},ButtonDark:{LeftImg:{L:0,T:198,W:2,H:32,DT:264,Src:1,oT:198,ST:198,oST:463},MiddleImg:{L:0,T:363,H:32,DT:264,Src:1,oT:396,ST:198,oST:463},RightImg:{L:0,T:198,W:2,H:32,DT:264,Src:1,oT:198,ST:198,oST:463},MenuRightImg:{L:149,T:243,W:27,H:32,DL:59,oL:179,SL:209,oSL:239},MenuRightBtnImg:{L:148,T:243,W:28,H:32,DL:58,oL:178,SL:208,oSL:238}},GroupBox:{Top:{L:0,T:-29,H:29,Src:1}},GroupBoxNoText:{Top:{L:0,T:0,H:2,DT:99,Src:1},Left:{L:15,T:0,W:2,DL:107,Src:2},Right:{L:15,T:0,W:2,DL:107,Src:2},
Bottom:{L:0,T:0,H:2,DT:99,Src:1}},EditLight:{LeftImg:{L:0,T:207,W:15,H:32,SL:64,DL:96,oL:32,oSL:64},LeftImgBtn:{L:0,T:207,W:2,H:32,SL:64,DL:96,oL:32,oSL:64},MiddleImg:{L:0,T:0,H:32,ST:66,DT:99,Src:1,oT:33,oST:66},RightImg:{L:16,T:207,W:15,H:32,SL:80,DL:112,oL:48,oSL:80},RightImgBtn:{L:29,T:207,W:2,H:32,SL:93,DL:125,oL:61,oSL:93},LeftImgReq:{L:128,T:207,W:15,H:32,DL:96,oL:161},LeftImgBtnReq:{L:128,T:207,W:2,H:32,DL:96,oL:161},MiddleImgReq:{L:0,T:132,H:32,DT:99,Src:1,oT:165},RightImgReq:{L:144,T:207,
W:15,H:32,DL:112,oL:177},RightImgBtnReq:{L:157,T:207,W:2,H:32,DL:125,oL:190}},EditDark:{LeftImg:{L:0,T:198,H:32,DT:264,Src:1,oT:231,ST:198,oST:198,W:15},LeftImgBtn:{L:0,T:198,H:32,DT:264,Src:1,oT:231,ST:198,oST:198,W:2},MiddleImg:{L:0,T:198,H:32,DT:264,Src:1,oT:231,ST:198,oST:198},RightImg:{L:0,T:198,H:32,DT:264,Src:1,oT:231,ST:198,oST:198,W:15},RightImgBtn:{L:0,T:198,H:32,DT:264,Src:1,oT:231,ST:198,oST:198,W:2},LeftImgReq:{L:128,T:207,W:15,H:32,DL:193,oL:161,SL:128,oSL:128},LeftImgBtnReq:{L:128,
T:207,W:2,H:32,DL:193,oL:161,SL:128,oSL:128},MiddleImgReq:{L:0,T:132,H:32,DT:264,Src:1,oT:165,ST:132,oST:132},RightImgReq:{L:144,T:207,W:15,H:32,DL:193,oL:177,SL:144,oSL:144},RightImgBtnReq:{L:157,T:207,W:2,H:32,DL:193,oL:190,SL:157,oSL:157}},DropDown:{L:0,T:864,W:33,H:32,oL:0,DL:67,Src:3,SL:34,oSL:33},EditEllipsis:{L:0,T:65,SL:33,DL:66,W:33,H:32,Src:3},EditSearch:{L:0,T:160,SL:33,DL:66,W:33,H:32,Src:3},EditArrowRight:{L:0,T:32,SL:33,DL:66,W:33,H:32,Src:3},EditArrowLeft:{L:0,T:0,SL:33,DL:66,W:33,
H:32,Src:3},MemoLight:{LeftTop:{L:0,T:207,W:15,H:13,SL:64,DL:96,oL:32,oSL:64},Top:{L:0,T:0,H:13,ST:66,DT:99,Src:1,oT:33,oST:66},RightTop:{L:16,T:207,W:15,H:13,SL:80,DL:112,oL:48,oSL:80},Left:{L:15,T:0,W:15,SL:77,DL:107,Src:2,oL:45,oSL:77},Right:{L:2,T:0,W:15,SL:64,DL:94,Src:2,oL:32,oSL:64},LeftBottom:{L:0,T:226,W:15,H:13,SL:64,DL:96,oL:32,oSL:64},Bottom:{L:0,T:19,H:13,ST:85,DT:118,Src:1,oT:52,oST:85},RightBottom:{L:16,T:226,W:15,H:13,SL:80,DL:112,oL:48,oSL:80}},MemoReqLight:{LeftTop:{L:128,T:207,
W:15,H:13,DL:96,oL:161,SL:128,oSL:128},Top:{L:0,T:132,H:13,DT:99,Src:1,oT:165,ST:132,oST:132},RightTop:{L:144,T:207,W:15,H:13,DL:112,oL:177,SL:144,oSL:144},Left:{L:139,T:0,W:15,DL:45,Src:2,oL:169,SL:139,oSL:139},Right:{L:126,T:0,W:15,DL:94,Src:2,oL:156,SL:126,oSL:126},LeftBottom:{L:128,T:226,W:15,H:13,DL:96,oL:161,SL:128,oSL:128},Bottom:{L:0,T:151,H:13,DT:118,Src:1,oT:184,ST:151,oST:151},RightBottom:{L:144,T:226,W:15,H:13,DL:112,oL:177,SL:144,oSL:144}},MemoDark:{LeftTop:{L:0,T:199,W:15,H:13,DT:101,
Src:1,oT:231,ST:199,oST:199},Top:{L:0,T:199,H:13,DT:101,Src:1,oT:231,ST:199,oST:199},RightTop:{L:0,T:199,W:15,H:13,DT:101,Src:1,oT:231,ST:199,oST:199},Left:{L:0,T:0,W:15,DL:109,Src:2,oL:48,SL:0,oSL:0},Right:{L:0,T:0,W:15,DL:110,Src:2,oL:47,SL:0,oSL:0},LeftBottom:{L:0,T:217,W:15,H:13,DT:116,Src:1,oT:250,ST:217,oST:217},Bottom:{L:0,T:217,H:13,DT:116,Src:1,oT:250,ST:217,oST:217},RightBottom:{L:0,T:217,W:15,H:13,DT:116,Src:1,oT:250,ST:217,oST:217}},MemoReqDark:{LeftTop:{L:128,T:207,W:15,H:13,DL:193,oL:161,
SL:128,oSL:128},Top:{L:0,T:132,H:13,DT:101,Src:1,oT:165,ST:132,oST:132},RightTop:{L:144,T:207,W:15,H:13,DL:193,oL:177,SL:144,oSL:144},Left:{L:139,T:0,W:15,DL:109,Src:2,oL:169,SL:139,oSL:139},Right:{L:126,T:0,W:15,DL:110,Src:2,oL:156,SL:126,oSL:126},LeftBottom:{L:128,T:226,W:15,H:13,DL:193,oL:161,SL:128,oSL:128},Bottom:{L:0,T:151,H:13,DT:116,Src:1,oT:184,ST:151,oST:151},RightBottom:{L:144,T:226,W:15,H:13,DL:193,oL:177,SL:144,oSL:144}},PagesBoxUpLight:{Top:{L:0,T:-30,H:32,Src:1},Left:{L:15,T:0,W:2,
Src:2},Right:{L:15,T:0,W:2,Src:2},Bottom:{L:0,T:0,H:2,Src:1}},PagesBoxUpDark:{Top:{L:0,T:496,H:32,Src:1},Left:{L:0,T:0,W:2,Src:2},Right:{L:0,T:0,W:2,Src:2},Bottom:{L:0,T:2,H:2,Src:1}},PagesUpLight:[{LeftImg:{L:-14,T:207,SL:257,W:14,H:32,oL:227,oT:209,oSL:257,DL:-14,oST:207,DSL:257},MiddleImg:{L:0,T:-32,ST:624,H:32,Src:1,oT:661,oST:624,DT:-32,DST:624},RightImg:{L:-14,T:207,SL:272,W:14,H:32,oL:227,oT:209,oSL:272,DL:-14,oST:207,DSL:272}}],PagesUpDark:[{MiddleImg:{L:0,T:-32,ST:198,H:32,Src:1,oT:693,DT:-32,
oST:198,DST:198}}],PagesBoxDownLight:{Top:{L:0,T:0,H:2,Src:1},Left:{L:15,T:0,W:2,Src:2},Right:{L:15,T:0,W:2,Src:2},Bottom:{L:0,T:559,H:32,Src:1}},PagesBoxDownDark:{Top:{L:0,T:2,H:2,Src:1},Left:{L:0,T:0,W:2,Src:2},Right:{L:0,T:0,W:2,Src:2},Bottom:{L:0,T:526,H:32,Src:1}},PagesDownLight:[{LeftImg:{L:-14,T:207,SL:287,W:14,H:32,oL:227,oT:205,oSL:287,DL:-14,oST:207,DSL:287},MiddleImg:{L:0,T:-32,ST:594,H:32,Src:1,oST:594,oT:658,DT:-32,DST:594},RightImg:{L:-14,T:207,SL:302,W:14,H:32,oL:227,oT:205,oSL:302,
DL:-14,oST:207,DSL:302}}],PagesDownDark:[{MiddleImg:{L:0,T:-32,ST:198,H:32,Src:1,oT:693,DT:-32,oST:198,DST:198}}],Sections:[{MiddleImg:{L:0,T:-32,H:32,Src:1}}],ProgressBar:{MiddleImg:{L:0,T:-6,H:6,Src:1},BarImg:{L:0,T:-6,H:6,Src:1}},VSplitLight:{L:383,T:74,W:16,H:36,oL:318,DL:-16},VSplitDark:{L:383,T:112,W:16,H:36,oL:318,DL:-16},HSplitLight:{L:405,T:84,W:36,H:16,oL:340,DL:-36},HSplitDark:{L:405,T:122,W:36,H:16,oL:340,DL:-36},DropPanelButtonLight:{L:0,T:74,DL:66,W:33,H:20,Src:3},DropPanelButtonDark:{L:33,
T:74,DL:66,W:33,H:20,Src:3},DropPanelButtonMiddleLight:{L:0,T:-20,oT:660,oST:660,H:20,Src:1},DropPanelButtonMiddleDark:{L:0,T:-20,oT:693,oST:693,H:20,Src:1},PagingFirstLight:{L:0,T:896,W:32,H:32,Src:3,SL:33,DL:67},PagingPrevLight:{L:0,T:800,W:32,H:32,Src:3,SL:33,DL:67},PagingNextLight:{L:0,T:768,W:32,H:32,Src:3,SL:33,DL:67},PagingLastLight:{L:0,T:928,W:32,H:32,Src:3,SL:33,DL:67},PagingFirstDark:{L:33,T:896,W:32,H:32,Src:3,SL:0,DL:67},PagingPrevDark:{L:33,T:800,W:32,H:32,Src:3,SL:0,DL:67},PagingNextDark:{L:33,
T:768,W:32,H:32,Src:3,SL:0,DL:67},PagingLastDark:{L:33,T:928,W:32,H:32,Src:3,SL:0,DL:67},WindowLight:{LeftTop:{L:-1,T:-1,W:10,H:15,Src:2},Top:{L:0,T:592,H:15,Src:1},RightTop:{L:292,T:206,W:10,H:15},RightTopBtn:{L:-34,T:-26,W:34,H:26},Left:{L:-1,T:0,W:10,Src:2},Right:{L:187,T:0,W:10,Src:2},LeftBottom:{L:-1,T:406,W:10,H:15,Src:2},Bottom:{L:0,T:643,H:15,Src:1},RightBottom:{L:262,T:225,W:10,H:15}},WindowDark:{LeftTop:{L:210,T:207,W:10,H:15},Top:{L:0,T:527,H:15,Src:1},RightTop:{L:215,T:207,W:10,H:15},
RightTopBtn:{L:0,T:2,W:34,H:26,Src:1},Left:{L:195,T:0,W:10,Src:2},Right:{L:-9,T:0,W:10,Src:2},LeftBottom:{L:210,T:224,W:10,H:15},Bottom:{L:0,T:512,H:15,Src:1},RightBottom:{L:215,T:224,W:10,H:15}},WindowCaptionLight:{LeftImg:{L:-1,T:-1,W:10,H:15,Src:2},MiddleImg:{L:0,T:579,H:41,Src:1},RightImg:{L:-10,T:-15,W:10,H:15},RightImgBtn:{L:603,T:567,W:34,H:41,Src:1}},WindowCaptionDark:{MiddleImg:{L:0,T:-45,H:41,Src:1},RightImgBtn:{L:0,T:2,W:34,H:26,Src:1}},WinCloseBtnLight:{L:107,T:171,W:34,H:26,oL:107,oT:278,
DL:-107},WinCloseBtnDark:{L:245,T:171,W:34,H:26,oL:247,oT:278,DL:-245},WinMaxBtnLight:{L:174,T:171,W:34,H:26,SL:210,DL:-34,oL:177,oT:278,oSL:212,oST:278},WinMaxBtnDark:{L:36,T:171,W:34,H:26,SL:72,DL:-34,oL:36,oT:278,oSL:72,oST:278},WinMinBtnLight:{L:140,T:171,W:34,H:26,DL:-34,oL:142,oT:278},WinMinBtnDark:{L:2,T:171,W:34,H:26,DL:-34,oL:2,oT:278},Hint:{Top:{L:0,T:0,H:2,Src:1},Left:{L:15,T:0,W:2,Src:2},Right:{L:15,T:0,W:2,Src:2},Bottom:{L:0,T:30,H:2,Src:1}},HintAnchors:{topleft:{L:12,T:-8,HX:7,HY:1,
Img:{L:331,T:214,W:16,H:10}},topright:{R:12,T:-8,HX:7,HY:1,Img:{L:331,T:214,W:16,H:10}},bottomright:{R:12,B:-8,HX:7,HY:8,Img:{L:357,T:214,W:16,H:10}},bottomleft:{L:12,B:-8,HX:7,HY:8,Img:{L:357,T:214,W:16,H:10}},lefttop:{L:-8,T:12,HX:1,HY:7,Img:{L:403,T:214,W:10,H:16}},leftbottom:{L:-8,B:12,HX:1,HY:7,Img:{L:403,T:214,W:10,H:16}},righttop:{R:-8,T:12,HX:8,HY:7,Img:{L:383,T:214,W:10,H:16}},rightbottom:{R:-8,B:12,HX:8,HY:7,Img:{L:383,T:214,W:10,H:16}}},TextHint:{LeftTop:{L:0,T:207,W:7,H:6},Top:{L:0,T:0,
H:6,Src:1},RightTop:{L:24,T:207,W:7,H:6},Left:{L:15,T:0,W:7,Src:2},Right:{L:10,T:0,W:7,Src:2},LeftBottom:{L:0,T:233,W:7,H:6},Bottom:{L:0,T:26,H:6,Src:1},RightBottom:{L:24,T:233,W:7,H:6}},TextHintAnchors:{topleft:{L:12,T:-8,HX:7,HY:1,Img:{L:331,T:214,W:16,H:10}},topright:{R:12,T:-8,HX:7,HY:1,Img:{L:331,T:214,W:16,H:10}},bottomright:{R:12,B:-8,HX:7,HY:8,Img:{L:357,T:214,W:16,H:10}},bottomleft:{L:12,B:-8,HX:7,HY:8,Img:{L:357,T:214,W:16,H:10}}},CalendarMonPrevLight:{L:0,T:800,W:32,H:32,Src:3,SL:33,DL:66},
CalendarMonNextLight:{L:0,T:768,W:32,H:32,Src:3,SL:33,DL:66},CalendarYearPrevLight:{L:0,T:809,W:32,H:13,Src:3,SL:33,DL:66},CalendarYearNextLight:{L:0,T:777,W:32,H:13,Src:3,SL:33,DL:66},CalendarMonPrevDark:{L:33,T:800,W:32,H:32,Src:3,SL:0,DL:66},CalendarMonNextDark:{L:33,T:768,W:32,H:32,Src:3,SL:0,DL:66},CalendarYearPrevDark:{L:33,T:809,W:32,H:13,Src:3,SL:0,DL:66},CalendarYearNextDark:{L:33,T:777,W:32,H:13,Src:3,SL:0,DL:66},CalendarImgDayLight:{L:-33,T:297,W:33,H:33,oL:0,oSL:0,DL:-33,Src:1},CalendarImgDayDark:{L:0,
T:-33,W:33,H:33,Src:1,oT:693,DT:-33},SubMenuLight:{L:0,T:768,W:32,H:32,Src:3,SL:33,DL:66,oL:33},SubMenuDark:{L:33,T:768,W:32,H:32,Src:3,SL:0,DL:66,oL:0},MenuCheckBoxLight:{L:-33,T:241,W:33,H:32,DL:-33,SL:322,oSL:382,DSL:352},MenuCheckBoxDark:{L:-33,T:241,W:33,H:32,DL:-33,SL:382,oSL:322,DSL:352},AppIcons:[{Empty:-1,Minus:0,Plus:1,Ellipsis:2,Layers:3,Routing:4,Search:5,Close:6,Pan:7,DrawCircle:8,DrawLine:9,DrawArea:10,DrawPoint:11,SelectObjects:12,Refresh:13,MeasureRadius:14,MeasureLine:15,MeasureArea:16,
OK:17,Back:18,Forward:19,Up:20,Down:21,Erase:22,Calendar:23,Next:24,Prev:25,PageUp:26,PageDown:27,First:28,Last:29},{}],AppMenuIcons:[{},{}]},AppIcon:function(l,j){l=this.Images.AppIcons[ngVal(j,this.Theme)][l];if(typeof l==="undefined")l=null;return l},AppMenuIcon:function(l,j){l=this.Images.AppMenuIcons[ngVal(j,this.Theme)][l];if(typeof l==="undefined")l=null;return l},OnInit:function(){function l(a){return ngVal(a.ColorScheme,n.ColorScheme)}function j(a){return ngVal(a.Theme,n.Theme)}function x(a,
b,c,d,h,e){if(typeof a.className==="undefined")a.className=(j(a)?"weCheckBoxLight":"weCheckBoxDark")+(typeof a.ColorScheme!=="undefined"?" we"+a.ColorScheme+"Text":"");a.OnCreated=ngAddEvent(a.OnCreated,function(f){if(f.TextAlign=="right"||f.TextAlign=="center"){f.TextAlign="right";if(ng_EmptyVar(f.LeftImg))f.LeftImg=d}else{f.TextAlign="left";if(ng_EmptyVar(f.RightImg))f.RightImg=h}});return ngCreateControlAsType(a,ngVal(e,"ngCheckBox"),b,c)}function L(a,b,c){var d=j(a);if(typeof a.className==="undefined")a.className=
(d?"weButtonLight":"weButtonDark")+(typeof a.ColorScheme==="undefined"?"":" we"+a.ColorScheme);a.OnCreated=ngAddEvent(a.OnCreated,function(h){if(ngVal(h.Default,false)){var e=h.Elm();if(e){e.className=e.className.replace(/Button/,"ButtonDefault");h.BaseClassName=h.BaseClassName.replace(/Button/,"ButtonDefault")}}});if(b=ngCreateControlAsType(a,"ngButton",b,c))if(d){b.MiddleImg=g.ButtonLight.MiddleImg;if(typeof a.Menu==="object")b.RightImg=g.ButtonLight.MenuRightImg}else{b.LeftImg=g.ButtonDark.LeftImg;
b.MiddleImg=g.ButtonDark.MiddleImg;b.RightImg=typeof a.Menu==="object"?g.ButtonDark.MenuRightImg:g.ButtonDark.RightImg}return b}function M(a,b,c){var d=j(a),h=d?g.AppButtonLight:g.AppButtonDark,e=g.AppIcons[d];ng_MergeDef(a,{className:d?"weAppButtonLight":"weAppButtonDark",W:h.W});typeof a.Menu==="object"&&a.Menu&&ng_MergeDef(a,{Data:{MenuVAlign:"bottom",MenuHAlign:"center",MenuOverlapY:10},Menu:{}});if(a=ngCreateControlAsType(a,"ngButton",b,c)){a.OnGetImg=function(f,i){var k;switch(i){case 0:k=f.LeftImg;
break;case 1:k=f.MiddleImg;break;case 2:k=f.RightImg;break;case -1:k=f.Img;(f=f.AppImages)||(f=e);if(typeof k==="string")k=f[k];break}return k};a.MiddleImg=h}return a}function C(a,b,c){if(typeof a.className==="undefined")a.className=(j(a)?"weGroupBoxLight":"weGroupBoxDark")+" we"+l(a)+"Text";b=ngCreateControlAsType(a,"ngGroup",b,c);a.OnCreated=ngAddEvent(a.OnCreated,function(d){if(d&&ng_EmptyVar(d.Frame))d.Frame=d.Text==""&&!d.OnGetText?g.GroupBoxNoText:g.GroupBox});return b}function o(a){if(a.DropDown&&
typeof a.DropDown==="object"){var b=a.DropDown;if(typeof b.Theme==="undefined")b.Theme=WE_LIGHT;var c=j(b);if(typeof b.className==="undefined")b.className=c?"weDropDownLight we"+l(a)+"DropDown":"weDropDownDark";if(b.Type==="weTreeList"){if(typeof b.OverrideEvents==="undefined")b.OverrideEvents={};b.OverrideEvents.OnGetTreeImg=function(d){return typeof d.TreeImg!=="undefined"?d.TreeImg:c?g.DropDownTreeImgLight:g.DropDownTreeImgDark}}}}function D(a,b,c){var d=j(a);if(typeof a.className==="undefined")a.className=
d?"weEditLight":"weEditDark";o(a);(b=ngCreateControlAsType(a,"ngEdit",b,c))&&n.weEdit_AddProperties(a,b,d);return b}function E(a,b,c,d){var h=j(a);if(typeof a.className==="undefined")a.className=h?"weEditLight":"weEditDark";o(a);a=ngCreateControlAsType(a,ngVal(d,"weEdit"),b,c);if(!a)return a;var e=new ngButton;e.LeftImg=g.EditEllipsis;e.OnClick=function(f){var i=f.Owner?ngVal(f.Owner.Parent,null):null;i&&i.OnEllipsis&&i.OnEllipsis(f,i.GetText())};a.Buttons=new Array(e);a.Ellipsis=function(){e.Click()};
a.OnEllipsis=null;return a}function F(a,b,c,d){var h=j(a);if(typeof a.className==="undefined")a.className=h?"weEditLight":"weEditDark";o(a);var e=ngCreateControlAsType(a,ngVal(d,"weEdit"),b,c);if(!e)return e;if(typeof a.DropDown!=="undefined")e.Suggestion=true;var f=new ngButton;f.LeftImg=g.EditSearch;f.Default=true;f.OnClick=function(i){var k=i.Owner?ngVal(i.Owner.Parent,null):null;k&&k.OnSearch&&k.OnSearch(i,k.GetText())};e.Buttons=[f];e.Search=function(i){typeof i!=="undefined"&&e.SetText(i);f.Click()};
return e}function y(a,b,c,d){var h=j(a);if(typeof a.className==="undefined")a.className=h?"weEditLight":"weEditDark";o(a);b=ngCreateControlAsType(a,ngVal(d,"ngEditNum"),b,c);if(!b)return b;n.weEdit_AddProperties(a,b,h);b.TextAlign="center";if(b.ButtonUp)b.ButtonUp.LeftImg=g.EditArrowRight;if(b.ButtonDown){b.ButtonDown.LeftImg=g.EditArrowLeft;b.ButtonDown.ButtonAlign="left"}return b}function z(a,b,c,d){var h=j(a);ng_MergeDef(a,{className:h?"weEditLight":"weEditDark",Data:{TextAlign:"center"},DropDown:null});
o(a);b=ngDropDown_Create(a,b,c,ngVal(d,"ngEdit"));if(!b)return b;n.weEdit_AddProperties(a,b,h);b.GetColor=function(){var e=this.GetText();if(e.length>0&&e[0]=="#")e=e.substring(2,e.length);return e};a=b.DropDownButton;a.Bounds.W=33;a.AutoSize=false;a.OnGetText=function(){return'<div style="margin:2px; line-height: 0px; font-size: 0px; position: absolute;left:0px;top:0px;width:28px; height:28px; background-color: #'+(this.Enabled?this.Parent.GetColor():"D6D6D6")+'"></div>'};b.OnTextChanged=function(e){e.DropDownButton.Update()};
return b}function t(a,b,c,d,h){var e=j(a);if(typeof a.className==="undefined")a.className=e?"weEditLight":"weEditDark";b=ngDropDown_Create(a,b,c,ngVal(d,"ngEdit"),h);if(!b)return b;n.weEdit_AddProperties(a,b,e);b.DropDownButton.LeftImg=g.DropDown;o(a);return b}function G(a,b,c,d){var h=j(a);if(typeof a.className==="undefined")a.className=h?"weMemoLight":"weMemoDark";var e=ngCreateControlAsType(a,ngVal(d,"ngMemo"),b,c);if(e){e.AddEvent("OnFocus",function(f){if(f=f.Elm()){var i=f.className;if(i.indexOf(" ")<
0)f.className=i+" "+i+"Focus"}return true});e.AddEvent("OnBlur",function(f){if(f=!f.MouseInControl?f.Elm():null){var i=f.className,k=i.indexOf(" ");if(k>=0)f.className=i.substring(0,k)}return true});e.AddEvent("DoMouseLeave",function(){var f=!e.ControlHasFocus?e.Elm():null;if(f){var i=f.className,k=i.indexOf(" ");if(k>=0)f.className=i.substring(0,k)}return true});a=ngVal(e.Invalid,false);e.Frame=h?a?g.MemoReqLight:g.MemoLight:a?g.MemoReqDark:g.MemoDark;e.SetInvalid=function(f,i){e.Frame=h?f?g.MemoReqLight:
g.MemoLight:f?g.MemoReqDark:g.MemoDark;e.Invalid=f;ngVal(i,true)&&e.DoUpdateImages()};return e}}function N(a,b,c){var d=j(a);if(typeof a.className==="undefined")a.className=(d?"wePagesLight":"wePagesDark")+" we"+l(a)+"Text";b=ngCreateControlAsType(a,"ngPages",b,c);if(!b)return null;b.PagesIndent=20;a.OnCreated=ngAddEvent(a.OnCreated,function(h){if(h.PagesVAlign=="bottom"){if(ng_EmptyVar(h.Frame))h.Frame=ng_CopyVar(d?g.PagesBoxDownLight:g.PagesBoxDownDark);if(ng_EmptyVar(h.PageImages)){h.PageImages=
d?g.PagesDownLight:g.PagesDownDark;h.RowOverlap=1}}else{if(ng_EmptyVar(h.Frame))h.Frame=ng_CopyVar(d?g.PagesBoxUpLight:g.PagesBoxUpDark);if(ng_EmptyVar(h.PageImages)){h.PageImages=d?g.PagesUpLight:g.PagesUpDark;h.RowOverlap=1}}});return b}function A(a,b,c,d,h,e){ng_MergeDef(a,{className:e?"weLabelLight":"weLabelDark",Data:{TextAlign:"center"}});d=u[d];ng_PreloadImage(d);(a=ngCreateControlAsType(a,"ngButton",b,c))&&a.AddEvent(function(f){f=ngTxt(f.Text);if(f!="")f='&nbsp;<span style="line-height: '+
h+'px">'+f+"</span>";return'<img src="'+d+'" align="top" />'+f},"OnGetText");return a}var n=this,s=ngLibPath("ng_wineight"),u=this.ControlImages,g=this.Images;ngApp.AddEvent("OnRunInternalFinished",function(){var a=n.BackgroundColor;if(typeof a==="undefined"||a==="Auto")a=n.Theme?"#FFFFFF":"#000000";if(a!=="None"){n.BackgroundColor=a;var b=ngApp.Elm();if(b)if(a.charAt(0)=="#")b.style.backgroundColor=a;else b.className=b.className+" we"+a}});for(var p=0;p<u.length;p++)u[p]=s+u[p];for(p in g.AppIcons[0]){s=
g.AppIcons[0][p];g.AppIcons[0][p]={L:33,T:s*32,SL:0,DL:66,W:33,H:32,Src:3};g.AppIcons[1][p]={L:0,T:s*32,SL:33,DL:66,W:33,H:32,Src:3};g.AppMenuIcons[0][p]={L:33,T:s*32,oL:0,DL:66,W:33,H:32,Src:3};g.AppMenuIcons[1][p]={L:0,T:s*32,oL:33,DL:66,W:33,H:32,Src:3}}ngRegisterControlType("wePanel",function(a,b,c){if(typeof a.className==="undefined")a.className="wePanel";return ngCreateControlAsType(a,"ngPanel",b,c)});ngRegisterControlType("weFrame",function(a,b,c){if(typeof a.className==="undefined")a.className=
"wePanel";return ngCreateControlAsType(a,"ngFrame",b,c)});ngRegisterControlType("weColorPanel",function(a,b,c){if(typeof a.className==="undefined")a.className="we"+l(a);return ngCreateControlAsType(a,"ngPanel",b,c)});ngRegisterControlType("weColorFrame",function(a,b,c){if(typeof a.className==="undefined")a.className="we"+l(a);return ngCreateControlAsType(a,"ngFrame",b,c)});ngRegisterControlType("weText",function(a,b,c){if(typeof a.className==="undefined")a.className=(j(a)?"weTextLight":"weTextDark")+
(typeof a.ColorScheme!=="undefined"?" we"+a.ColorScheme+"Text":"");return ngCreateControlAsType(a,"ngText",b,c)});ngRegisterControlType("weSmallText",function(a,b,c){if(typeof a.className==="undefined")a.className=(j(a)?"weSmallTextLight":"weSmallTextDark")+(typeof a.ColorScheme!=="undefined"?" we"+a.ColorScheme+"Text":"");return ngCreateControlAsType(a,"ngText",b,c)});ngRegisterControlType("weCaption",function(a,b,c){if(typeof a.className==="undefined")a.className=(j(a)?"weCaptionLight":"weCaptionDark")+
" we"+l(a)+"Text";return ngCreateControlAsType(a,"ngButton",b,c)});ngRegisterControlType("weTitle",function(a,b,c){if(typeof a.className==="undefined")a.className=(j(a)?"weTitleLight":"weTitleDark")+" we"+l(a)+"Text";return ngCreateControlAsType(a,"ngButton",b,c)});ngRegisterControlType("weImage",function(a,b,c){if(typeof a.className==="undefined")a.className="weImage";return ngCreateControlAsType(a,"ngImage",b,c)});ngRegisterControlType("weCheckBox",function(a,b,c){var d=j(a);return x(a,b,c,d?g.CheckBoxLeftLight:
g.CheckBoxLeftDark,d?g.CheckBoxRightLight:g.CheckBoxRightDark)});ngRegisterControlType("weRadioButton",function(a,b,c){var d=j(a);if(typeof a.className==="undefined")a.className=d?"weRadioLight":"weRadioDark";return x(a,b,c,d?g.RadioLeftLight:g.RadioLeftDark,d?g.RadioRightLight:g.RadioRightDark,"ngRadioButton")});ngRegisterControlType("weToggleSwitch",function(a,b,c){var d=j(a);if(typeof a.className==="undefined")a.className=(d?"weToggleSwitchLight":"weToggleSwitchDark")+(!d&&typeof a.ColorScheme===
"undefined"?"":" we"+l(a));d=d?g.ToggleSwitchLight:g.ToggleSwitchDark;var h=x(a,b,c,d,d);if(h){h.OnGetText=function(){return""};h.AddEvent("DoAcceptGestures",function(e,f){f.swipeleft=true;f.swiperight=true});h.AddEvent("DoGesture",function(e){if(e.Gesture==="swipeleft"){h.Check(0);delete e.Gestures.tap;return true}if(e.Gesture==="swiperight"){h.Check(1);delete e.Gestures.tap;return true}return false})}return h});ngRegisterControlType("weButton",function(a,b,c){return L(a,b,c)});ngRegisterControlType("weAppButton",
function(a,b,c){return M(a,b,c)});ngRegisterControlType("weLabel",function(a,b,c){if(typeof a.className==="undefined")a.className=(j(a)?"weLabelLight":"weLabelDark")+(typeof a.ColorScheme!=="undefined"?" we"+a.ColorScheme+"Text":"");return ngCreateControlAsType(a,"ngButton",b,c)});ngRegisterControlType("weLink",function(a,b,c){if(typeof a.className==="undefined")a.className=(j(a)?"weLinkLight":"weLinkDark")+" we"+l(a)+"Text";return ngCreateControlAsType(a,"ngButton",b,c)});ngRegisterControlType("weGroup",
C);ngRegisterControlType("weGroupBox",C);this.weEdit_AddProperties=function(a,b,c){var d=c?g.EditLight:g.EditDark,h=ngVal(b.Invalid,false),e=false,f=false;a.OnCreated=ngAddEvent(a.OnCreated,function(i){if(i.Buttons)for(var k,m=0;m<i.Buttons.length&&(!e||!f);m++){k=i.Buttons[m];k=ngVal(k.ButtonAlign,"");if(k=="left")e=true;else f=true}i.LeftImg=e?h?d.LeftImgBtnReq:d.LeftImgBtn:h?d.LeftImgReq:d.LeftImg;i.MiddleImg=h?d.MiddleImgReq:d.MiddleImg;i.RightImg=f?h?d.RightImgBtnReq:d.RightImgBtn:h?d.RightImgReq:
d.RightImg});b.SetInvalid=function(i,k){if(i){b.LeftImg=e?d.LeftImgBtnReq:d.LeftImgReq;b.MiddleImg=d.MiddleImgReq;b.RightImg=f?d.RightImgBtnReq:d.RightImgReq}else{b.LeftImg=e?d.LeftImgBtn:d.LeftImg;b.MiddleImg=d.MiddleImg;b.RightImg=f?d.RightImgBtn:d.RightImg}b.Invalid=i;if(ngVal(k,true)){b.LeftImg&&ngc_ChangeImage(ngpg_ImgDrawProps(b.ID+"_IL",0,b.Enabled,b.LeftImg));b.MiddleImg&&ngc_ChangeImageS(ngpg_ImgDrawProps(b.ID+"_IM",0,b.Enabled,b.MiddleImg));b.RightImg&&ngc_ChangeImage(ngpg_ImgDrawProps(b.ID+
"_IR",0,b.Enabled,b.RightImg))}}};ngRegisterControlType("weEdit",function(a,b,c){return D(a,b,c)});ngRegisterControlType("weEditBox",function(a,b,c){return D(a,b,c)});ngRegisterControlType("weEditBoxBtn",function(a,b,c){return E(a,b,c)});ngRegisterControlType("weSearchBox",function(a,b,c){return F(a,b,c)});ngRegisterControlType("weEditNum",function(a,b,c){return y(a,b,c)});ngRegisterControlType("weEditBoxNum",function(a,b,c){return y(a,b,c)});ngRegisterControlType("weColorEdit",function(a,b,c){return z(a,
b,c)});ngRegisterControlType("weColorEditBox",function(a,b,c){return z(a,b,c)});ngRegisterControlType("weDropDown",function(a,b,c){return t(a,b,c,"ngEdit")});ngRegisterControlType("weDropDownList",function(a,b,c){return t(a,b,c,"ngEdit",true)});ngRegisterControlType("weMemo",function(a,b,c){return G(a,b,c)});ngRegisterControlType("wePages",function(a,b,c){return N(a,b,c)});ngRegisterControlType("weSections",function(a,b,c){if(typeof a.className==="undefined")a.className=(j(a)?"weSectionsLight":"weSectionsDark")+
" we"+l(a)+"Text";if(a=ngCreateControlAsType(a,"ngPages",b,c))a.PageImages=g.Sections;return a});ngRegisterControlType("weToolBar",function(a,b,c){if(typeof a.className==="undefined")a.className="weToolBar"+(typeof a.ColorScheme==="undefined"?"":" we"+a.ColorScheme);return ngCreateControlAsType(a,"ngToolBar",b,c)});ngRegisterControlType("weProgressBar",function(a,b,c){if(typeof a.className==="undefined")a.className="weProgressBar";b=ngCreateControlAsType(a,"ngProgressBar",b,c);if(!b)return b;b.Smooth=
true;b.MiddleImg=g.ProgressBar.MiddleImg;b.BarImg=ng_CopyVar(g.ProgressBar.BarImg);b.BarImg.Attrs='class="we'+(j(a)?l(a):"White")+'"';return b});ngRegisterControlType("weProgressRing",function(a,b,c){var d=j(a);return A(a,b,c,d?6:7,40,d)});ngRegisterControlType("weProgressDot",function(a,b,c){var d=j(a);return A(a,b,c,d?8:9,22,d)});ngRegisterControlType("weProgressLine",function(a,b,c){var d=j(a);return A(a,b,c,d?4:5,40,d)});if(ngUserControls.list){var B=function(a,b,c){var d=j(a);if(typeof a.className===
"undefined")a.className=d?"weListBoxLight we"+l(a)+"ListBox":"weListBoxDark";b=ngCreateControlAsType(a,"ngList",b,c);if(!b)return b;b.AddEvent("DoUpdate",function(e){var f=e.className,i=f.indexOf(" "),k=this.BaseClassName+"Disabled",m=f.indexOf(k);if(this.Enabled){if(m>=0){f=f.substring(m+k.length,f.length);e.className=this.BaseClassName+(f.length>0?" "+f:"")}}else if(m<0)e.className=this.BaseClassName+" "+k+(i>=0?f.substring(i,f.length):"");return true});var h=a.Type==="weTreeList";delete b.CheckImg;
delete b.TreeImg;b.OnGetCheckImg=function(e,f,i){if(typeof f.Checked==="undefined"&&!e.ShowCheckboxes)return null;if(typeof e.CheckImg!=="undefined")return e.CheckImg;if(typeof f.RadioGroup!=="undefined")return d||e.Enabled&&e.selected[i]?g.ListRadioLight:g.ListRadioDark;return d||e.Enabled&&e.selected[i]?g.ListCheckBoxLight:g.ListCheckBoxDark};if(h){b.DefaultIndent=27;b.OnGetTreeImg=function(e,f,i){return typeof e.TreeImg!=="undefined"?e.TreeImg:d?e.selected[i]?g.TreeImgSelLight:g.TreeImgLight:e.selected[i]?
g.TreeImgLight:g.TreeImgDark}}b.AddEvent("OnRedrawSelected",function(e,f,i,k){if(f=e.ItemById(k)){if(!d&&(typeof f.Checked!=="undefined"||e.ShowCheckboxes))(i=typeof f.RadioGroup!=="undefined"?e.selected[k]?g.ListRadioLight:g.ListRadioDark:e.selected[k]?g.ListCheckBoxLight:g.ListCheckBoxDark)&&ngc_ChangeImage(ngl_CheckImgDrawProps(e.ID+"_"+k+"C",f.Checked,e.Enabled,i));if(h)if(i=d?e.selected[k]?g.TreeImgSelLight:g.TreeImgLight:e.selected[k]?g.TreeImgLight:g.TreeImgDark){var m=false;for(f=f;!m&&f;){m=
ngVal(f.Collapsed,false);f=f.Parent}ngc_ChangeImage(ngl_TreeImgDrawProps(e.ID+"_"+k+"T",m,e.Enabled,i))}}});return b};ngRegisterControlType("weList",function(a,b,c){return B(a,b,c)});ngRegisterControlType("weListBox",function(a,b,c){return B(a,b,c)});ngRegisterControlType("weTreeList",function(a,b,c){return B(a,b,c)});this.wePageListPagingControlsDef=function(a,b){return{FirstPage:{Type:"weButton",Theme:b,Data:{ToolBarHPadding:5,Img:b?g.PagingFirstLight:g.PagingFirstDark,Text:""}},PrevPage:{Type:"weButton",
Theme:b,Data:{ToolBarHPadding:5,Img:b?g.PagingPrevLight:g.PagingPrevDark,Text:""}},PageNo:{Type:"weEdit",Theme:b,W:64,Data:{ToolBarHPadding:5,Text:"1",TextAlign:"center"}},Page0:{Type:"weButton",Theme:b,className:(b?"wePageButtonLight":"wePageButtonDark")+(typeof a.ColorScheme==="undefined"?"":" we"+a.ColorScheme),Data:{ToolBarHPadding:5,Text:"1",TextAlign:"center"}},NextPage:{Type:"weButton",Theme:b,Data:{Img:b?g.PagingNextLight:g.PagingNextDark,Text:"",ImgAlign:"right",ToolBarHPadding:5}},LastPage:{Type:"weButton",
Theme:b,Data:{Img:b?g.PagingLastLight:g.PagingLastDark,ImgAlign:"right",Text:""}}}};var v=function(a,b,c,d,h){var e=j(a);ng_MergeDef(a,{className:e?"weListBoxLight":"weListBoxDark",Controls:{List:{Type:ngVal(h,"weList"),Theme:e},Loading:{Type:"weProgressDot",Theme:e,L:10,T:d==="ngDataSet"||d==="ngDBDataSet"||a.Controls&&a.Controls.List&&a.Controls.List.Data&&a.Controls.List.Data.Columns&&a.Controls.List.Data.Columns.length>0?55:8,Data:{Visible:false}},Paging:{className:e?"wePageListPagingLight":"wePageListPagingDark",
H:32,Controls:n.wePageListPagingControlsDef(a,e)}}});return ngCreateControlAsType(a,ngVal(d,"ngPageList"),b,c)};ngRegisterControlType("wePageList",function(a,b,c){return v(a,b,c,"ngPageList")});ngRegisterControlType("wePageTreeList",function(a,b,c){return v(a,b,c,"ngPageList","weTreeList")})}if(ngUserControls.panels){ngRegisterControlType("weAlignPanel",function(a,b,c){if(typeof a.className==="undefined")a.className=typeof a.ColorScheme==="undefined"?"wePanel":"we"+a.ColorScheme;return ngCreateControlAsType(a,
"ngAlignPanel",b,c)});ngRegisterControlType("weAlignFrame",function(a,b,c){if(typeof a.className==="undefined")a.className=typeof a.ColorScheme==="undefined"?"wePanel":"we"+a.ColorScheme;return ngCreateControlAsType(a,"ngAlignFrame",b,c)});var O=function(a,b,c){var d=j(a);if(typeof a.className==="undefined")a.className=(d?"weSplitPanelLight":"weSplitPanelDark")+" we"+l(a)+"Split";if(a=ngCreateControlAsType(a,"ngSplitPanel",b,c))a.HandleImg=a.PanelAlign=="left"||a.PanelAlign=="right"?d?g.VSplitLight:
g.VSplitDark:d?g.HSplitLight:g.HSplitDark;return a};ngRegisterControlType("weSplitPanel",function(a,b,c){return O(a,b,c)});var P=function(a,b,c){if(typeof a.Theme==="undefined")a.Theme=n.InvTheme();var d=j(a);if(typeof a.className==="undefined")a.className=(d?"weDropPanelLight":"weDropPanelDark")+(typeof a.ColorScheme==="undefined"?"":" we"+a.ColorScheme);b=ngCreateControlAsType(a,"ngDropPanel",b,c);ng_MergeDef(a,{H:72,Button:{Data:{MiddleImg:d?g.DropPanelButtonMiddleLight:g.DropPanelButtonMiddleDark,
Img:d?g.DropPanelButtonLight:g.DropPanelButtonDark,TextAlign:"right",ImgIndent:20}}});if(typeof a.W==="undefined"&&typeof a.CW==="undefined"&&(typeof a.L==="undefined"||typeof a.R==="undefined")){if(typeof a.L==="undefined")a.L=0;if(typeof a.R==="undefined")a.R=0}return b};ngRegisterControlType("weDropPanel",function(a,b,c){return P(a,b,c)})}if(ngUserControls.window){var H=function(a,b,c){var d=a.Type==="weDialog",h=j(a);if(typeof a.className==="undefined")a.className=(d?"weDialog":"weWindow")+(h?
"Light":"Dark")+" we"+l(a)+" we"+l(a)+"Text";var e=ngCreateControlAsType(a,"ngWindow",b,c);if(!e)return e;b=ngVal(a.CloseBtn,d?true:false);e.Frame=h?g.WindowLight:g.WindowDark;e.CaptionImg=h?g.WindowCaptionLight:g.WindowCaptionDark;e.MinimizedBounds={H:42};if(b){e.Frame.RightTop=e.Frame.RightTopBtn;e.CaptionImg.RightImg=e.CaptionImg.RightImgBtn}if(d){e.Modal=true;e.Visible=false;e.Sizeable=false;e.Centered=true}if(b){d=new ngButton;e.CloseButton=d;d.LeftImg=h?g.WinCloseBtnLight:g.WinCloseBtnDark;
d.OnClick=function(f){(f=f.Owner?ngVal(f.Owner.Parent,null):null)&&f.Close&&f.Close(f)};if(!e.Buttons)e.Buttons=[];e.Buttons[e.Buttons.length]=d}if(ngVal(a.MaxBtn,false)){d=new ngButton;e.MaxButton=d;e.OnDblClick=function(f){f.win&&f.win.MaxButton&&f.win.MaxButton.Click()};e.AddEvent(function(){var f=e.IsMaximized()?1:0;e.MaxButton&&e.MaxButton.Checked!=f&&e.MaxButton.Check(f);return true},"DoUpdate");d.LeftImg=h?g.WinMaxBtnLight:g.WinMaxBtnDark;d.OnClick=function(f){var i=f.Owner?ngVal(f.Owner.Parent,
null):null;if(i){f.Owner.Check(i.IsMaximized()?0:1);if(f.Owner.Checked)i.Maximize&&i.Maximize(i);else i.Restore&&i.Restore(i)}};if(!e.Buttons)e.Buttons=[];e.Buttons[e.Buttons.length]=d}if(ngVal(a.MinBtn,false)){d=new ngButton;e.MinButton=d;d.LeftImg=h?g.WinMinBtnLight:g.WinMinBtnDark;e.AddEvent(function(){var f=e.IsMinimized()?1:0;e.MinButton&&e.MinButton.Checked!=f&&e.MinButton.Check(f);return true},"DoUpdate");d.OnClick=function(f){var i=f.Owner?ngVal(f.Owner.Parent,null):null;if(i){f.Owner.Check(i.IsMinimized()?
0:1);if(f.Owner.Checked)i.Minimize&&i.Minimize(i);else i.Restore&&i.Restore(i)}};if(!e.Buttons)e.Buttons=[];e.Buttons[e.Buttons.length]=d}return e};ngRegisterControlType("weWindow",function(a,b,c){return H(a,b,c)});ngRegisterControlType("weDialog",function(a,b,c){return H(a,b,c)});ngRegisterControlType("weHint",function(a,b,c){if(typeof a.className==="undefined")a.className="weHint";if(a=ngCreateControlAsType(a,"ngHint",b,c)){a.Frame=ng_CopyVar(g.Hint);a.Anchors=ng_CopyVar(g.HintAnchors)}return a});
ngRegisterControlType("weTextHint",function(a,b,c){ng_MergeDef(a,{className:"weTextHint",Controls:{Hint:{Type:"weText",L:5,T:2,Theme:WE_LIGHT}}});if(a=ngCreateControlAsType(a,"ngTextHint",b,c)){a.Frame=ng_CopyVar(g.TextHint);a.Anchors=ng_CopyVar(g.TextHintAnchors)}return a})}if(ngUserControls.dialogs){var Q=function(){if(ngVal(this.ControlsPanel,false)){var a=this.Elm();if(a){var b=a.offsetParent;if(b&&b==document.body)b=null;b=b?ng_ClientHeight(b):ng_WindowHeight();ng_OuterWidth(a);ng_ClientWidth(this.ControlsPanel.Elm());
ng_SetClientHeight(a,b);var c=0,d=0,h=d=0,e=ngVal(this.Controls.Message,null),f=ngVal(this.Controls.Content,null),i=ngVal(this.Controls.Buttons,null),k=this.ControlsPanel.ChildControls;if(typeof k!=="undefined"){h=d=1E4;for(var m,q=0;q<k.length;q++)if(k[q]!=i){a=k[q].Elm();m=ng_GetCurrentStylePx(a,"left");if(m<d)d=m;if(k[q]!=f){a=ng_GetCurrentStylePx(a,"top");if(a<h)h=a}}}if((a=e?e.Elm():null)&&e.Visible)c=ng_GetCurrentStylePx(a,"top")+ng_OuterHeight(a);if((a=f?f.Elm():null)&&f.Visible){f.SetBounds({T:c});
c+=ng_OuterHeight(a)}if(a=i?i.Elm():null){k=i.ChildControls;if(i.Visible&&typeof k!=="undefined"&&k.length>0){d=ng_OuterWidth(a);if(i.CenterButtons){a.style.marginLeft=-Math.round(d/2)+"px";i.SetBounds({L:"50%",T:c})}else i.SetBounds({T:c});c+=ng_OuterHeight(a);i.SetVisible(true)}else i.SetVisible(false)}c+=h;if(c<mbMinimalHeight)c=mbMinimalHeight;this.SetClientRect({H:c});if(this.Bounds.H>b)this.Bounds.H=b;if(this.Bounds.H<this.MinHeight)this.MinHeight=this.Bounds.H;this.SetBounds();this.Update()}}},
R=function(a,b,c){var d=j(a),h=c;if(h&&h==document.body)h=null;var e="25%";if((h?ng_ClientWidth(h):ng_WindowWidth())<600)e="10px";ng_MergeDef(a,{DialogType:"weDialog",L:0,W:"100%",CloseBtn:false,Data:{Frame:{},CaptionImg:{LeftImg:null,MiddleImg:null,RightImg:null},CalcAutoSize:Q,CheckBounds:function(){return false}},Events:{OnGetText:function(){return""}},Controls:{Title:{Type:"weCaption",Theme:d,ColorScheme:d===WE_DARK?"White":undefined,L:e,T:27,Events:{OnGetText:function(f){return f.Owner.Owner.Text}}},
Message:{Type:"weText",Theme:d,L:e,R:e,T:67},Content:{Type:"ngPanel",L:e,R:e,H:15},Buttons:{Type:"ngToolBar",L:e,R:e,H:32,Data:{HAlign:"right",CenterButtons:false,Vertical:false,HPadding:10},Controls:{OK:{Type:"weButton",Theme:d,W:90},Yes:{Type:"weButton",Theme:d,W:90},No:{Type:"weButton",Theme:d,W:90},Cancel:{Type:"weButton",Theme:d,W:90}}}}});if(typeof a.DlgCheckBox!=="undefined"){ng_MergeDef(a,{Controls:{Content:{Controls:{CheckBox:{Type:"weCheckBox",Theme:d,L:0,B:10,Data:a.DlgCheckBox}}}}});a.Controls.Content.H+=
21}if(a.DialogType==="weMessageDlg")a.DialogType="weDialog";return ngCreateControlAsType(a,"ngMessageDlg",b,c)};ngRegisterControlType("weMessageDlg",function(a,b,c){return R(a,b,c)});var S=function(a,b,c){delete a.DialogType;a.DlgButtons=ngVal(a.DlgButtons,mbOK);return ngCreateControlAsType(a,"weMessageDlg",b,c)};ngRegisterControlType("weDlgMessageBox",function(a,b,c){return S(a,b,c)});var w=function(a,b,c){var d=j(a);delete a.DialogType;a.DlgAllowEmpty=ngVal(a.DlgAllowEmpty,false);d={DialogType:"weMessageDlg",
DlgButtons:mbOK|mbCancel,Data:{},Controls:{Message:{Data:{MinWidth:250}},Content:{H:68,Controls:{Edit:{Type:"weEdit",Theme:d,L:0,T:6,R:0,Data:{}}}},Buttons:{Controls:{OK:{Data:{}}}}}};var h=d.Controls.Content.Controls.Edit;switch(a.Type){case "weDlgMemoBox":h.Type="weMemo";h.H=100;d.Controls.Content.H=132;break;case "weDlgDropDownBox":case "weDlgDropDownListBox":h.Type=a.Type==="weDlgDropDownBox"?"weDropDown":"weDropDownList";h.DropDown={Type:"weList",Theme:WE_LIGHT,Data:{}};if(typeof a.DlgItems!==
"undefined")h.DropDown.Data.Items=a.DlgItems;break}if(typeof a.DlgHint!=="undefined")h.Data.Hint=a.DlgHint;if(!a.DlgAllowEmpty){h.Data.OnTextChanged=function(e){e.Owner.OK.SetEnabled(e.GetText()!="");return true};d.Controls.Buttons.Controls.OK.Data.Enabled=false}ng_MergeDef(a,d);(b=ngCreateControlAsType(a,"weMessageDlg",b,c))&&a.Type!="weDlgDropDownListBox"&&b.AddEvent("OnVisibleChanged",function(e){var f,i=e.Controls.Edit;f=i.OnGetHint?ngVal(i.OnGetHint(i),""):i.Hint;e.Visible&&f==""&&i.SetFocus()});
return b};ngRegisterControlType("weDlgInputBox",function(a,b,c){return w(a,b,c)});ngRegisterControlType("weDlgDropDownBox",function(a,b,c){return w(a,b,c)});ngRegisterControlType("weDlgDropDownListBox",function(a,b,c){return w(a,b,c)});ngRegisterControlType("weDlgMemoBox",function(a,b,c){return w(a,b,c)});var T=function(a,b,c){var d=j(a);delete a.DialogType;a.DlgAllowEmpty=ngVal(a.DlgAllowEmpty,false);d={DialogType:"weMessageDlg",DlgButtons:mbOK|mbCancel,Data:{},Controls:{Message:{Data:{MinWidth:300}},
Content:{H:276,Controls:{List:{Type:"weList",Theme:d,L:0,T:6,R:0,H:250,Data:{SelectType:nglSelectSingle}}}},Buttons:{Controls:{OK:{Data:{}}}}}};var h=d.Controls.Content.Controls.List;if(typeof a.DlgItems!=="undefined")h.Data.Items=a.DlgItems;if(!a.DlgAllowEmpty){h.Data.OnSelectChanged=function(e){e.Owner.OK.SetEnabled&&e.Owner.OK.SetEnabled(e.SelCount>0);return true};d.Controls.Buttons.Controls.OK.Data.Enabled=false}ng_MergeDef(a,d);(a=ngCreateControlAsType(a,"weMessageDlg",b,c))&&a.AddEvent("OnVisibleChanged",
function(e){e.Visible&&e.Controls.List.SetFocus()});return a};ngRegisterControlType("weDlgListBox",function(a,b,c){return T(a,b,c)});var U=function(a,b,c){var d=j(a);delete a.DialogType;ng_MergeDef(a,{DlgButtons:mbNone,Data:{},Controls:{Title:null,Message:{Data:{MinWidth:230}},Content:{H:16,Controls:{Progress:{Type:"weProgressBar",Theme:d,L:0,T:5,R:0}}}}});return ngCreateControlAsType(a,"weMessageDlg",b,c)};ngRegisterControlType("weDlgProgressBox",function(a,b,c){return U(a,b,c)});var V=function(a,
b,c){var d=j(a);delete a.DialogType;ng_MergeDef(a,{DlgButtons:mbNone,Data:{},Controls:{Title:null,Content:{Controls:{Progress:{Type:"weProgressLine",Theme:d,L:-45,T:5}}}}});return ngCreateControlAsType(a,"weMessageDlg",b,c)};ngRegisterControlType("weDlgWaitBox",function(a,b,c){return V(a,b,c)});var W=function(a,b,c){var d=j(a),h=c;if(h&&h==document.body)h=null;var e="25%";if((h?ng_ClientWidth(h):ng_WindowWidth())<600)e="10px";h={DialogType:"weDlgMessageBox",DlgIcon:null,Controls:{Title:null,Message:{className:(d?
"weAboutMessageLight":"weAboutMessageDark")+(d?" we"+l(a)+"Text":""),Data:{MinWidth:260}},Content:{H:190,Controls:{AppInfo:{className:(d?"weTextListBoxLight":"weTextListBoxDark")+" weAboutList",Type:"weListBox",Theme:d,H:150,Data:{DefaultIndent:0},OverrideEvents:{OnGetTreeImg:function(f,i,k){return f.selected[k]&&!d||!f.selected[k]&&d?g.AboutTreeImgLight:g.AboutTreeImgDark}}}}},Buttons:{R:e}}};if(typeof a.DlgIcon==="object"&&a.DlgIcon)h.Controls.Message.Data.MinWidth-=a.DlgIcon.W+10;ng_MergeDef(a,
h,true);return ngCreateControlAsType(a,"ngAboutDlg",b,c)};ngRegisterControlType("weDlgAbout",function(a,b,c){return W(a,b,c)})}if(ngUserControls.calendar){var X=function(a,b,c){var d=j(a);if(typeof a.className==="undefined")a.className=d?"weCalendarLight we"+l(a)+"Calendar":"weCalendarDark";a=ngCreateControlAsType(a,"ngCalendar",b,c);if(!a)return a;a.PrevMonBtn.Img=d?g.CalendarMonPrevLight:g.CalendarMonPrevDark;a.PrevMonBtn.Text="";a.NextMonBtn.Img=d?g.CalendarMonNextLight:g.CalendarMonNextDark;a.NextMonBtn.Text=
"";a.PrevYearBtn.Img=d?g.CalendarYearPrevLight:g.CalendarYearPrevDark;a.PrevYearBtn.Text="";a.NextYearBtn.Img=d?g.CalendarYearNextLight:g.CalendarYearNextDark;a.NextYearBtn.Text="";a.ImgDay=d?g.CalendarImgDayLight:g.CalendarImgDayDark;for(b=0;b<a.FastButtons.length;b++){c=a.FastButtons[b];if(d)c.MiddleImg=g.ButtonLight.MiddleImg;else{c.LeftImg=g.ButtonDark.LeftImg;c.MiddleImg=g.ButtonDark.MiddleImg;c.RightImg=g.ButtonDark.RightImg}c.className="weButton"+(d?"Light":"Dark")+" weCalBtn"}return a};ngRegisterControlType("weCalendar",
function(a,b,c){return X(a,b,c)});var I=function(a,b,c,d){var h=j(a);ng_MergeDef(a,{className:h?"weEditLight":"weEditDark",DropDown:{Type:"weCalendar",style:{padding:"10px"}}});o(a);var e=j(a.DropDown);a.DropDown.className=(e?"weCalendarLight we"+l(a)+"Calendar ":"weCalendarDark ")+a.DropDown.className;b=t(a,b,c,ngVal(d,"ngEditDate"),false);if(!b)return b;n.weEdit_AddProperties(a,b,h);b.DropDownButton.LeftImg=g.AppIcons[1].Calendar;b.DropDownButton.Alt=ngTxt("calendar");return b};ngRegisterControlType("weEditDate",
function(a,b,c){return I(a,b,c)});var J=function(a,b,c,d){var h=j(a),e=1;ng_MergeDef(a,{className:h?"weEditLight":"weEditDark",Data:{},Events:{OnDropDown:function(f,i){if(!i.Items.length){i.BeginUpdate();f=[];for(var k=0;k<24;k++)for(var m=0;m<60;m+=e){var q=new Date(0,0,0,k,m,0);f.push({Text:ng_FormatTime(q,ng_TimeFormat(false,true)),Time:q})}i.AddItems(f);i.EndUpdate()}return true},OnListItemChanged:function(f,i,k){f.SetDate(k.Time);f.HideDropDown&&f.HideDropDown();return false}},DropDown:{Type:"weList"}});
o(a);e=ngVal(a.DropDown.HourDivider,2);if(e<=0)e=1;e=60/e;b=ngCreateControlAsType(a,ngVal(d,"ngEditTime"),b,c);if(!b)return b;if(a.Type=="ngDropDownList")b.DropDownType=ngeDropDownList;ngDropDown_Add(b);n.weEdit_AddProperties(a,b,h);b.DropDownButton.LeftImg=g.DropDown;o(a);return b};ngRegisterControlType("weEditTime",function(a,b,c){return J(a,b,c)})}if(ngUserControls.menu){var Y=function(a,b,c){if(typeof a.Theme==="undefined")a.Theme=WE_LIGHT;var d=j(a);ng_MergeDef(a,{className:d?"weMenuLight we"+
l(a)+"Menu":"weMenuDark",Data:{SubMenuImg:d?g.SubMenuLight:g.SubMenuDark,SubMenuDef:{Type:"weMenu"}}});if(a=ngCreateControlAsType(a,"ngMenu",b,c)){a.OnGetCheckImg=function(h,e){if(typeof e.Checked==="undefined"||!h.ShowCheckboxes)return null;return d?g.MenuCheckBoxLight:g.MenuCheckBoxDark};a.OnGetItemImg=function(h,e){var f=h.MenuImages;f||(f=g.AppMenuIcons[d]);e=e.Image;if(typeof e==="string")e=f[e];if(typeof e==="undefined")e=h.ItemImg;if(typeof e==="string")e=f[e];return e}}return a};ngRegisterControlType("weMenu",
function(a,b,c){return Y(a,b,c)});ngRegisterControlType("weMenuBar",function(a,b,c){if(typeof a.className==="undefined")a.className=j(a)?"weMenuBarLight we"+l(a)+"MenuBar":"weMenuBarDark"+(typeof a.ColorScheme==="undefined"?"":" we"+a.ColorScheme);return ngCreateControlAsType(a,"ngMenuBar",b,c)});ngRegisterControlType("weMenuBarButton",function(a,b,c){return ngCreateControlAsType(a,"ngMenuBarButton",b,c)});var Z=function(a,b,c){var d=j(a);if(typeof a.className==="undefined")a.className=d?"weSplitButtonLight":
"weSplitButtonDark";a=ngCreateControlAsType(a,"ngSplitButton",b,c);if(!a)return a;if(d){a.MiddleImg=g.ButtonLight.MiddleImg;a.RightImg=g.ButtonLight.MenuRightBtnImg}else{a.LeftImg=g.ButtonDark.LeftImg;a.MiddleImg=g.ButtonDark.MiddleImg;a.RightImg=g.ButtonDark.MenuRightBtnImg}return a};ngRegisterControlType("weSplitButton",function(a,b,c){return Z(a,b,c)})}if(ngUserControls.viewmodel_controls){var K=function(a,b,c,d){if(typeof a.className==="undefined")a.className=typeof a.ColorScheme==="undefined"?
"wePanel":"we"+a.ColorScheme;ng_MergeDef(a,{ErrorHint:{Type:"weTextHint"}});(a=ngCreateControlAsType(a,ngVal(d,"ngViewModelForm"),b,c))&&a.AddEvent("OnShowErrorMsg",function(h,e){typeof ngMessageDlg==="function"?ngMessageDlg("weDlgMessageBox",e,typeof h.Caption==="undefined"?ngTxt("ngAppName"):ngTxt(h.Caption),null):alert(e);return true});return a};ngRegisterControlType("weViewModelForm",function(a,b,c){return K(a,b,c)});var r=function(a,b){ng_MergeDef(a,{className:b?"weEditLight":"weEditDark",Data:{HintX:19,
HintY:27},ErrorHint:{Type:"weTextHint"}})},$=function(a,b,c){var d=j(a);r(a,d);o(a);(b=ngCreateControlAsType(a,"ngEditField",b,c))&&n.weEdit_AddProperties(a,b,d);return b};ngRegisterControlType("weEditField",function(a,b,c){return $(a,b,c)});ngRegisterControlType("weSearchBoxField",function(a,b,c){return F(a,b,c,"weEditField")});ngRegisterControlType("weEditBoxBtnField",function(a,b,c){return E(a,b,c,"weEditField")});ngRegisterControlType("weEditNumField",function(a,b,c){r(a,j(a));return y(a,b,c,
"ngEditNumField")});ngRegisterControlType("weColorEditField",function(a,b,c){r(a,j(a));return z(a,b,c,"ngDropDownField")});ngRegisterControlType("weDropDownField",function(a,b,c){r(a,j(a));return t(a,b,c,"ngDropDownField",false)});ngRegisterControlType("weDropDownListField",function(a,b,c){r(a,j(a));return t(a,b,c,"ngDropDownListField",true)});ngRegisterControlType("weEditDateField",function(a,b,c){r(a,j(a));return I(a,b,c,"ngEditDateField")});ngRegisterControlType("weEditTimeField",function(a,b,
c){r(a,j(a));return J(a,b,c,"ngEditTimeField")});ngRegisterControlType("weMemoField",function(a,b,c){r(a,j(a));return G(a,b,c,"ngMemoField")})}if(ngUserControls.dbviewmodel){ngRegisterControlType("weDBViewModelForm",function(a,b,c){if(a=K(a,b,c,"ngDBViewModelForm")){a.AddEvent("OnDeleteQuery",function(d,h,e,f){if(typeof ngMessageDlg==="function"){ngMessageDlg("weDlgMessageBox",h,typeof d.Caption==="undefined"?ngTxt("ngAppName"):ngTxt(d.Caption),function(i){if(i.DialogResult==mbYes)typeof e==="function"&&
e(d);else typeof f==="function"&&f(d);i.Hide();return true},{DlgButtons:mbYes|mbNo|mbDefButton2},{Theme:WE_LIGHT});return false}else{if(confirm(h))typeof e==="function"&&e(d);else typeof f==="function"&&f(d);return true}});a.AddEvent("OnChangedQuery",function(d,h,e,f){if(typeof ngMessageDlg==="function"){ngMessageDlg("weDlgMessageBox",h,typeof d.Caption==="undefined"?ngTxt("ngAppName"):ngTxt(d.Caption),function(i){if(i.DialogResult==mbYes)typeof e==="function"&&e(d);else typeof f==="function"&&f(d);
i.Hide();return true},{DlgButtons:mbYes|mbNo|mbDefButton2},{Theme:WE_LIGHT});return false}else{if(confirm(h))typeof e==="function"&&e(d);else typeof f==="function"&&f(d);return true}})}return a});var aa=function(a,b,c){var d=j(a);ng_MergeDef(a,{W:260,className:"weToolBar",Data:{HPadding:10},Controls:{New:{Type:"weButton",Theme:d,W:60},Delete:{Type:"weButton",Theme:d,W:60,Data:{ToolBarHPadding:20}},Insert:{Type:"weButton",Theme:d,W:60},Update:{Type:"weButton",Theme:d,W:60},Cancel:{Type:"weButton",
Theme:d,W:60}}});return ngCreateControlAsType(a,"ngDBToolBar",b,c)};ngRegisterControlType("weDBToolBar",function(a,b,c){return aa(a,b,c)});ngRegisterControlType("weDataSet",function(a,b,c){return v(a,b,c,"ngDataSet")});var ba=function(a,b,c){var d=j(a);ng_MergeDef(a,{Controls:{Paging:{Controls:{NewRecord:{Type:"weButton",Theme:d,Data:{ToolBarHPadding:10}},LoadRecord:{Type:"weButton",Theme:d,Data:{ToolBarHPadding:10}},DeleteRecord:{Type:"weButton",Theme:d,Data:{ToolBarHPadding:20}},Refresh:{Type:"weButton",
Theme:d,Data:{ToolBarHPadding:20}}}}}});return v(a,b,c,"ngDBDataSet")};ngRegisterControlType("weDBDataSet",function(a,b,c){return ba(a,b,c)})}}};ngUserControls.wineight=WinEightControls;
