/*!
 * Controls.js - loader-image.js
 * http://controlsjs.com/
 *
 * Copyright (c) 2014 Position s.r.o.  All rights reserved.
 *
 * This version of Controls.js is licensed under the terms of GNU General Public License v3.
 * http://www.gnu.org/licenses/gpl-3.0.html
 *
 * The commercial license can be purchased at Controls.js website.
 */








var ngLibsURL=typeof ngLibsURL!=="undefined"?ngLibsURL:"controls/libs/";if(typeof ngLib==="undefined")ngLib=[];if(typeof ngLib.ng_controls==="undefined")ngLib.ng_controls={path:"ng_controls/"};if(typeof ngLib.ng_basic==="undefined")ngLib.ng_basic={path:"ng_basic/"};if(typeof ngLib.ng_winxp==="undefined")ngLib.ng_winxp={path:"ng_winxp/"};if(typeof ngLib.ng_winwineight==="undefined")ngLib.ng_wineight={path:"ng_wineight/"};if(typeof ngLib.ng_wireframe==="undefined")ngLib.ng_wireframe={path:"ng_wireframe/"};
if(typeof ngLib.lib_knockout==="undefined")ngLib.lib_knockout={path:"lib_knockout/"};if(typeof ngLib.lib_hammerjs==="undefined")ngLib.lib_hammerjs={path:"lib_hammerjs/"};var ngOnAppLoading=typeof ngOnAppLoading==="undefined"?null:ngOnAppLoading,ngOnAppLoaded=typeof ngOnAppLoaded==="undefined"?null:ngOnAppLoaded,ngOnAppCreated=typeof ngOnAppCreated==="undefined"?null:ngOnAppCreated,ngOnAppLoadProgress=typeof ngOnAppLoadProgress==="undefined"?null:ngOnAppLoadProgress,ngOnAppFileLoad=typeof ngOnAppFileLoad==="undefined"?null:ngOnAppFileLoad,ngOnAppFileLoaded=typeof ngOnAppFileLoaded==="undefined"?null:ngOnAppFileLoaded;
function ngCreateHTMLFragment(h){var c=document.createDocumentFragment();if(c){var d=document.createElement("div");for(d.innerHTML=h;d.firstChild;)c.appendChild(d.firstChild)}return c}
function ngLoadApplication(h,c,d){function e(a){var b,l,n;for(var j in a){if(typeof a[j]==="string")a[j]={File:a[j]};if(typeof a[j].Type==="undefined"){b=i(a[j].File);l=b.lastIndexOf("/");if(l<0)l=b.lastIndexOf("\\");n=b.lastIndexOf(".");if(n>l){b=b.substring(n+1).toLowerCase();switch(b){case "js":a[j].Type=1;break;case "css":a[j].Type=0;break;case "png":case "jpg":case "gif":case "jpeg":case "bmp":a[j].Type=2;break}}}switch(a[j].Type){case 0:ngLoadAppCSS(a[j].File,a[j]);break;case 2:ngLoadAppImg(a[j].File,
a[j]);break}}for(j in a)a[j].Type===1&&ngLoadAppScript(a[j].File,a[j],null,a[j].Async)}function g(a){var b=a.indexOf("://");if(b<0)return window.location.hostname;a=a.substring(b+3,a.length);b=a.indexOf("/");if(b>=0)a=a.substring(0,b);b=a.indexOf(":");if(b>=0)a=a.substring(0,b);return a}function i(a){var b=a.indexOf("?");if(b>=0)a=a.substr(0,b);b=a.indexOf("#");if(b>=0)a=a.substr(0,b);return a}function u(a){return U&&V&&g(a)==window.location.hostname?i(a):a}function t(a){if(typeof Windows!=="undefined")MSApp.execUnsafeLocalFunction(function(){window.eval.call(window,
a)});else window.execScript?window.execScript(a):window.eval.call(window,a)}function r(a,b,l,n){x++;if(o&&typeof ngOnAppLoadProgress==="function"){var j=f>0?Math.round(x*100/f):0;if(j>G){ngOnAppLoadProgress(j);G=j}}n||D(a,b,l)}function D(a,b,l){q++;a>=0&&typeof ngOnAppFileLoaded==="function"&&ngOnAppFileLoaded(a,b,l);if(q===f){ngInitializeAppUnits();if(o&&q===f)var n=setTimeout(function(){clearTimeout(n);typeof ngOnAppLoaded==="function"&&ngOnAppLoaded();if(q<f)ngOnAppLoaded=null;else{o=0;if(typeof ngApplication===
"function"){new ngApplication(typeof ngStartParams==="function"?new ngStartParams:{},h&&(typeof h==="object"||h!="")?h:"ngApp",false);if(ngApp&&m!="")ngApp.AppPath=m;typeof ngOnAppCreated==="function"&&ngOnAppCreated(ngApp)}c&&!c(ngApp)||ngApp&&ngApp.Run()}},100)}}if(typeof ngOnAppLoading==="function"&&!ngOnAppLoading())return false;var E=document.getElementsByTagName("head").item(0);if(!E)return false;var v,G=0,F=0,o=1,f=1,x=0,q=0,m="",z="",k={},A=[];v=navigator.userAgent.toLowerCase();var U=typeof window.cordova!==
"undefined",V=v.indexOf("windows phone")!=-1,O=v.indexOf("opera")!=-1,P;if(O)P=parseFloat(window.opera.version());v=document.getElementsByTagName("script");var H,s;H="";for(var J=0;J<v.length;J++)if(typeof v[J].src!=="undefined"){H=v[J].src;s=H.indexOf("apploader=");if(s>=0){s=H.indexOf("?");if(s>=0){m=H.substring(0,s);s=m.lastIndexOf("/");m=s<=0?"":m.substring(0,s+1);break}}}if(m!=""){s=m.indexOf("://");if(s>=0)for(s+=3;s<m.length;s++)if(m.charAt(s)=="/"){z=m.substring(0,s);break}if(m.charAt(m.length-
1)!="/")m+="/"}window.ngInitializeAppUnits=function(){if(typeof ngAppUnits==="object"){for(var a in ngAppUnits)if(typeof ngAppUnits[a].LoadOrder==="undefined")ngAppUnits[a].LoadOrder=F++;ngAppUnits.sort(function(b,l){if(typeof b.Priority==="undefined")b.Priority=0.5;if(typeof l.Priority==="undefined")l.Priority=0.5;if(b.Priority<0)b.Priority=0;if(l.Priority<0)l.Priority=0;if(b.Priority>1)b.Priority=1;if(l.Priority>1)l.Priority=1;if(b.Priority>l.Priority)return-1;if(b.Priority<l.Priority)return 1;
return b.LoadOrder-l.LoadOrder});for(a in ngAppUnits)if(!ngAppUnits[a].Initialized){ngAppUnits[a].Initialized=true;typeof ngAppUnits[a].OnInit==="function"&&ngAppUnits[a].OnInit()}}};window.ngAppURL=function(a){a=u(a);if(a.indexOf("://")>=0||a=="")return a;if(a.charAt(0)=="/")return z+a;return m+a};window.ngLoadAppCSS=function(a,b){if(!(typeof ngOnAppFileLoad==="function"&&!ngOnAppFileLoad(0,a,b))){b=document.createElement("link");b.setAttribute("rel","stylesheet");b.setAttribute("type","text/css");
b.setAttribute("href",ngAppURL(a));E.appendChild(b)}};window.ngLoadAppScript=function(a,b,l,n){function j(I,M,Q,B){function R(K){var w=typeof console!=="undefined"?console:null;w&&w.error('Script "'+I+'" was not loaded!');L(K)}function L(K,w){if(!S){S=true;if(n){typeof w!=="undefined"&&w!==""&&t(w);typeof Q==="function"&&Q(1,I,M);r(1,I,M)}else{K===true&&r(1,I,M,true);var p=A[0];if(!p.Async){if(K===true)return;A.splice(0,1);typeof p.LoadCallback==="function"&&p.LoadCallback(1,p.URL,p.Data);r(1,p.URL,
p.Data)}for(;A.length;){p=A[0];if(!p.Async){j(p.URL,p.Data,p.LoadCallback,false);break}w=p.code;if(typeof w==="undefined")break;w!==""&&t(w);A.splice(0,1);typeof p.LoadCallback==="function"&&p.LoadCallback(1,p.URL,p.Data);D(1,p.URL,p.Data)}}}}var S=false,T=ngAppURL(I);if(B){var y=new XMLHttpRequest;y.onreadystatechange=function(){if(y.readyState==4)if(y.status==200||y.status==304||y.status==0){if(!n)N.code=y.responseText;L(true,y.responseText)}else{if(!n)N.code="";R(true)}};y.open("GET",T,true);y.send()}else{B=
document.createElement("script");B.onload=L;B.onerror=R;B.onreadystatechange=function(){this.readyState!="loaded"&&this.readyState!="complete"||L()};B.setAttribute("src",T);E.appendChild(B)}}var C=window.XMLHttpRequest&&(typeof ngDEBUG==="undefined"||!ngDEBUG)&&(!O||P>=11.1&&window.location.protocol!="file:")&&(typeof Windows!=="undefined"||g(a)==window.location.hostname&&window.location.hostname!="");if(!(typeof ngOnAppFileLoad==="function"&&!ngOnAppFileLoad(1,a,b))){f++;if(!n){var N={URL:a,Data:b,
Async:C,LoadCallback:l};A.push(N);if(!C&&A.length>1)return}j(a,b,l,C)}};window.ngLoadAppImg=function(a,b,l){if(typeof ngOnAppFileLoad==="function"&&!ngOnAppFileLoad(2,a,b))return null;var n=k[a];if(typeof n==="undefined"){n=new Image;f++;var j=false,C=function(){if(!j){j=true;typeof l==="function"&&l(2,a,b);r(2,a,b)}};n.onload=C;n.onfailure=C;n.onerror=C;k[a]=n;n.src=ngAppURL(a)}return n};var W=setTimeout(function(){clearTimeout(W);if(!d){d=[];if(ngAppFiles)for(var a in ngAppFiles)d.push(ngAppFiles[a]);
if(typeof ngDetectDevice==="function"){if(typeof ngDevice==="undefined")ngDevice=ngDetectDevice();if(typeof ngDevice!=="undefined"&&typeof ngAppDeviceFiles!=="undefined"){var b=ngAppDeviceFiles[ngDevice];if(typeof b!=="undefined")for(a in b)d.push(b[a])}}}d&&e(d);r(-1)},100);return true};function ngDeviceReset(h){if(typeof ngDevices==="object"&&ngDevices)if(typeof h==="undefined"||typeof ngDevices[h]==="object"){var c=window.location.href,d=c.indexOf("?"),e=c.indexOf("#"),g="",i="";if(e>=0){i=c.substr(e);c=c.substr(0,e)}if(d>=0){g=c.substr(d+1);c=c.substr(0,d)}d=g.indexOf("appdevice=");if(d>=0){e=g.indexOf("&",d);e=e>=0?g.substr(e+1):"";g=g.substr(0,d);if(typeof h!=="undefined")g+="appdevice="+h;else if(d>0)g=g.substr(0,d-1);if(e!=""){if(g!="")g+="&";g+=e}}else if(typeof h!=="undefined"){if(g!=
"")g+="&";g+="appdevice="+h}if(g!="")c+="?"+g;c+=i;if(window.location.href==c)window.location.reload();else window.location.href=c}}
function ngGetDeviceInfo(){var h=0,c=0;if(typeof window.innerWidth=="number"){h=window.innerWidth;c=window.innerHeight}else if(document.documentElement&&document.documentElement.clientWidth){h=document.documentElement.clientWidth;c=document.documentElement.clientHeight}else if(document.body&&document.body.clientWidth){h=document.body.clientWidth;c=document.body.clientHeight}var d=window.screen.colorDepth;if(typeof d==="undefined")d=24;var e=screen.width;if(typeof e==="undefined")e=h;var g=screen.height;
if(typeof g==="undefined")g=c;var i=window.orientation;if(typeof i==="undefined")i=e>g?90:0;var u=h>c?90:0,t=u==90,r=Math.abs(i%180)==90;return{ScreenWidth:e,ScreenHeight:g,ScreenOrientation:i,ScreenLandscape:r,ScreenPortrait:!r,Width:h,Height:c,Orientation:u,Landscape:t,Portrait:!t,ColorDepth:d,SupportsTouch:"ontouchstart"in window||window.DocumentTouch&&document instanceof DocumentTouch||navigator.msMaxTouchPoints?true:false}}
function ngDetectDevice(){var h;if(typeof ngDevices==="object"&&ngDevices){var c=ngGetDeviceInfo(),d=0,e=1E4,g,i=navigator.userAgent.toLowerCase(),u=function(v,G){var F,o,f,x,q,m=0,z=0;for(var k in G){f=G[k];z++;x=k.substr(0,3);if(x=="Opt"){k=k.substring(3,k.length);x=k.substr(0,3);F=false}else F=true;if(x=="Not"){k=k.substring(3,k.length);x=k.substr(0,3);o=true}else o=false;q=false;switch(x){case "Min":k=k.substring(3,k.length);if(!o&&c[k]>=f||o&&c[k]<f)q=true;break;case "Max":k=k.substring(3,k.length);
if(!o&&c[k]<f||o&&c[k]>=f)q=true;break;default:switch(k){case "IsMobile":F=false;z--;break;case "IExplorer":f=eval("/*@cc_on!@*/false")==f;if(!o==f)q=true;break;case "FireFox":f=i.indexOf("firefox")!=-1==f;if(!o==f)q=true;break;case "Chrome":f=i.indexOf("chrome")!=-1==f;if(!o==f)q=true;break;case "Safari":f=i.indexOf("safari")!=-1==f;if(!o==f)q=true;break;case "Opera":f=i.indexOf("opera")!=-1==f;if(!o==f)q=true;break;case "UserAgent":f=navigator.userAgent.indexOf(f)!=-1;if(!o==f)q=true;break;case "UserAgentIC":f=
i.indexOf(f.toLowerCase())!=-1;if(!o==f)q=true;break;default:if(!o&&c[k]==f||o&&c[k]!=f)q=true;break}break}if(q)m++;else if(F){m=-10000;break}}if(z){if(m>=0&&(m>d||m==d&&z<e)){d=m;e=z;h=v}}else if(typeof g==="undefined")g=v},t,r;for(var D in ngDevices){t=ngDevices[D];r=false;for(var E in t)if(typeof t[E]==="object"){r=true;u(D,t[E])}r||u(D,t)}if(typeof h==="undefined")h=g}return h}function ngLoadAppDeviceCSS(h,c,d){if(!(typeof ngDevice==="undefined"||ngDevice!=h))return ngLoadAppCSS(c,d)}
function ngLoadAppDeviceScript(h,c,d,e,g){if(!(typeof ngDevice==="undefined"||ngDevice!=h))return ngLoadAppScript(c,d,e,g)}function ngLoadAppDeviceImg(h,c,d,e){if(!(typeof ngDevice==="undefined"||ngDevice!=h))return ngLoadAppImg(c,d,e)};var ngLoaderDirection=typeof ngLoaderDirection!=="undefined"?ngLoaderDirection:0;
(function(){function h(){if(e){var i;i=ngLoaderDirection===1||ngLoaderDirection===3?Math.round(g*(d/100)):Math.round(g*(c/100));switch(ngLoaderDirection){default:case 0:e.style.width=i+"px";break;case 1:e.style.height=i+"px";break;case 2:e.style.width=c-i+"px";break;case 3:e.style.height=d-i+"px";break}}}var c=-1,d=-1,e=null,g=0;ngOnAppLoadProgress=function(i){g=i;if(c===-1)if(i=document.getElementById("ngProgress")){var u=document.getElementById("ngImgProgress"),t=document.getElementById("ngProgress1"),
r=document.getElementById("ngProgress2");if(t&&r&&u){c=parseInt(u.width,10);d=parseInt(u.height,10);i.style.marginLeft=-Math.round(c/2)+"px";i.style.marginTop=-Math.round(d/2)+"px";i.style.width=c+"px";i.style.height=d+"px";e=ngLoaderDirection===2||ngLoaderDirection===3?t:r;if(ngLoaderDirection===1||ngLoaderDirection===3){e.style.width=c+"px";e.style.height=ngLoaderDirection===1?"0px":d+"px";e.className="ngLoadVert"}else{e.style.height=d+"px";e.style.width=ngLoaderDirection!==2?"0px":c+"px";e.className=
"ngLoadHorz"}e.style.zIndex=1}i.style.visibility="visible";setTimeout(h,1);return}else d=c=0;setTimeout(h,1)}})();
