/*!
 * Controls.js - loader-percent.js
 * http://controlsjs.com/
 *
 * Copyright (c) 2014 Position s.r.o.  All rights reserved.
 *
 * This version of Controls.js is licensed under the terms of GNU General Public License v3.
 * http://www.gnu.org/licenses/gpl-3.0.html
 *
 * The commercial license can be purchased at Controls.js website.
 */








var ngLibsURL=typeof ngLibsURL!=="undefined"?ngLibsURL:"controls/libs/";if(typeof ngLib==="undefined")ngLib=[];if(typeof ngLib.ng_controls==="undefined")ngLib.ng_controls={path:"ng_controls/"};if(typeof ngLib.ng_basic==="undefined")ngLib.ng_basic={path:"ng_basic/"};if(typeof ngLib.ng_winxp==="undefined")ngLib.ng_winxp={path:"ng_winxp/"};if(typeof ngLib.ng_winwineight==="undefined")ngLib.ng_wineight={path:"ng_wineight/"};if(typeof ngLib.ng_wireframe==="undefined")ngLib.ng_wireframe={path:"ng_wireframe/"};
if(typeof ngLib.lib_knockout==="undefined")ngLib.lib_knockout={path:"lib_knockout/"};if(typeof ngLib.lib_hammerjs==="undefined")ngLib.lib_hammerjs={path:"lib_hammerjs/"};var ngOnAppLoading=typeof ngOnAppLoading==="undefined"?null:ngOnAppLoading,ngOnAppLoaded=typeof ngOnAppLoaded==="undefined"?null:ngOnAppLoaded,ngOnAppCreated=typeof ngOnAppCreated==="undefined"?null:ngOnAppCreated,ngOnAppLoadProgress=typeof ngOnAppLoadProgress==="undefined"?null:ngOnAppLoadProgress,ngOnAppFileLoad=typeof ngOnAppFileLoad==="undefined"?null:ngOnAppFileLoad,ngOnAppFileLoaded=typeof ngOnAppFileLoaded==="undefined"?null:ngOnAppFileLoaded;
function ngCreateHTMLFragment(g){var c=document.createDocumentFragment();if(c){var e=document.createElement("div");for(e.innerHTML=g;e.firstChild;)c.appendChild(e.firstChild)}return c}
function ngLoadApplication(g,c,e){function h(a){var b,k,m;for(var i in a){if(typeof a[i]==="string")a[i]={File:a[i]};if(typeof a[i].Type==="undefined"){b=q(a[i].File);k=b.lastIndexOf("/");if(k<0)k=b.lastIndexOf("\\");m=b.lastIndexOf(".");if(m>k){b=b.substring(m+1).toLowerCase();switch(b){case "js":a[i].Type=1;break;case "css":a[i].Type=0;break;case "png":case "jpg":case "gif":case "jpeg":case "bmp":a[i].Type=2;break}}}switch(a[i].Type){case 0:ngLoadAppCSS(a[i].File,a[i]);break;case 2:ngLoadAppImg(a[i].File,
a[i]);break}}for(i in a)a[i].Type===1&&ngLoadAppScript(a[i].File,a[i],null,a[i].Async)}function d(a){var b=a.indexOf("://");if(b<0)return window.location.hostname;a=a.substring(b+3,a.length);b=a.indexOf("/");if(b>=0)a=a.substring(0,b);b=a.indexOf(":");if(b>=0)a=a.substring(0,b);return a}function q(a){var b=a.indexOf("?");if(b>=0)a=a.substr(0,b);b=a.indexOf("#");if(b>=0)a=a.substr(0,b);return a}function z(a){return U&&V&&d(a)==window.location.hostname?q(a):a}function t(a){if(typeof Windows!=="undefined")MSApp.execUnsafeLocalFunction(function(){window.eval.call(window,
a)});else window.execScript?window.execScript(a):window.eval.call(window,a)}function s(a,b,k,m){w++;if(n&&typeof ngOnAppLoadProgress==="function"){var i=f>0?Math.round(w*100/f):0;if(i>G){ngOnAppLoadProgress(i);G=i}}m||D(a,b,k)}function D(a,b,k){p++;a>=0&&typeof ngOnAppFileLoaded==="function"&&ngOnAppFileLoaded(a,b,k);if(p===f){ngInitializeAppUnits();if(n&&p===f)var m=setTimeout(function(){clearTimeout(m);typeof ngOnAppLoaded==="function"&&ngOnAppLoaded();if(p<f)ngOnAppLoaded=null;else{n=0;if(typeof ngApplication===
"function"){new ngApplication(typeof ngStartParams==="function"?new ngStartParams:{},g&&(typeof g==="object"||g!="")?g:"ngApp",false);if(ngApp&&l!="")ngApp.AppPath=l;typeof ngOnAppCreated==="function"&&ngOnAppCreated(ngApp)}c&&!c(ngApp)||ngApp&&ngApp.Run()}},100)}}if(typeof ngOnAppLoading==="function"&&!ngOnAppLoading())return false;var E=document.getElementsByTagName("head").item(0);if(!E)return false;var u,G=0,F=0,n=1,f=1,w=0,p=0,l="",y="",j={},A=[];u=navigator.userAgent.toLowerCase();var U=typeof window.cordova!==
"undefined",V=u.indexOf("windows phone")!=-1,O=u.indexOf("opera")!=-1,P;if(O)P=parseFloat(window.opera.version());u=document.getElementsByTagName("script");var H,r;H="";for(var J=0;J<u.length;J++)if(typeof u[J].src!=="undefined"){H=u[J].src;r=H.indexOf("apploader=");if(r>=0){r=H.indexOf("?");if(r>=0){l=H.substring(0,r);r=l.lastIndexOf("/");l=r<=0?"":l.substring(0,r+1);break}}}if(l!=""){r=l.indexOf("://");if(r>=0)for(r+=3;r<l.length;r++)if(l.charAt(r)=="/"){y=l.substring(0,r);break}if(l.charAt(l.length-
1)!="/")l+="/"}window.ngInitializeAppUnits=function(){if(typeof ngAppUnits==="object"){for(var a in ngAppUnits)if(typeof ngAppUnits[a].LoadOrder==="undefined")ngAppUnits[a].LoadOrder=F++;ngAppUnits.sort(function(b,k){if(typeof b.Priority==="undefined")b.Priority=0.5;if(typeof k.Priority==="undefined")k.Priority=0.5;if(b.Priority<0)b.Priority=0;if(k.Priority<0)k.Priority=0;if(b.Priority>1)b.Priority=1;if(k.Priority>1)k.Priority=1;if(b.Priority>k.Priority)return-1;if(b.Priority<k.Priority)return 1;
return b.LoadOrder-k.LoadOrder});for(a in ngAppUnits)if(!ngAppUnits[a].Initialized){ngAppUnits[a].Initialized=true;typeof ngAppUnits[a].OnInit==="function"&&ngAppUnits[a].OnInit()}}};window.ngAppURL=function(a){a=z(a);if(a.indexOf("://")>=0||a=="")return a;if(a.charAt(0)=="/")return y+a;return l+a};window.ngLoadAppCSS=function(a,b){if(!(typeof ngOnAppFileLoad==="function"&&!ngOnAppFileLoad(0,a,b))){b=document.createElement("link");b.setAttribute("rel","stylesheet");b.setAttribute("type","text/css");
b.setAttribute("href",ngAppURL(a));E.appendChild(b)}};window.ngLoadAppScript=function(a,b,k,m){function i(I,M,Q,B){function R(K){var v=typeof console!=="undefined"?console:null;v&&v.error('Script "'+I+'" was not loaded!');L(K)}function L(K,v){if(!S){S=true;if(m){typeof v!=="undefined"&&v!==""&&t(v);typeof Q==="function"&&Q(1,I,M);s(1,I,M)}else{K===true&&s(1,I,M,true);var o=A[0];if(!o.Async){if(K===true)return;A.splice(0,1);typeof o.LoadCallback==="function"&&o.LoadCallback(1,o.URL,o.Data);s(1,o.URL,
o.Data)}for(;A.length;){o=A[0];if(!o.Async){i(o.URL,o.Data,o.LoadCallback,false);break}v=o.code;if(typeof v==="undefined")break;v!==""&&t(v);A.splice(0,1);typeof o.LoadCallback==="function"&&o.LoadCallback(1,o.URL,o.Data);D(1,o.URL,o.Data)}}}}var S=false,T=ngAppURL(I);if(B){var x=new XMLHttpRequest;x.onreadystatechange=function(){if(x.readyState==4)if(x.status==200||x.status==304||x.status==0){if(!m)N.code=x.responseText;L(true,x.responseText)}else{if(!m)N.code="";R(true)}};x.open("GET",T,true);x.send()}else{B=
document.createElement("script");B.onload=L;B.onerror=R;B.onreadystatechange=function(){this.readyState!="loaded"&&this.readyState!="complete"||L()};B.setAttribute("src",T);E.appendChild(B)}}var C=window.XMLHttpRequest&&(typeof ngDEBUG==="undefined"||!ngDEBUG)&&(!O||P>=11.1&&window.location.protocol!="file:")&&(typeof Windows!=="undefined"||d(a)==window.location.hostname&&window.location.hostname!="");if(!(typeof ngOnAppFileLoad==="function"&&!ngOnAppFileLoad(1,a,b))){f++;if(!m){var N={URL:a,Data:b,
Async:C,LoadCallback:k};A.push(N);if(!C&&A.length>1)return}i(a,b,k,C)}};window.ngLoadAppImg=function(a,b,k){if(typeof ngOnAppFileLoad==="function"&&!ngOnAppFileLoad(2,a,b))return null;var m=j[a];if(typeof m==="undefined"){m=new Image;f++;var i=false,C=function(){if(!i){i=true;typeof k==="function"&&k(2,a,b);s(2,a,b)}};m.onload=C;m.onfailure=C;m.onerror=C;j[a]=m;m.src=ngAppURL(a)}return m};var W=setTimeout(function(){clearTimeout(W);if(!e){e=[];if(ngAppFiles)for(var a in ngAppFiles)e.push(ngAppFiles[a]);
if(typeof ngDetectDevice==="function"){if(typeof ngDevice==="undefined")ngDevice=ngDetectDevice();if(typeof ngDevice!=="undefined"&&typeof ngAppDeviceFiles!=="undefined"){var b=ngAppDeviceFiles[ngDevice];if(typeof b!=="undefined")for(a in b)e.push(b[a])}}}e&&h(e);s(-1)},100);return true};function ngDeviceReset(g){if(typeof ngDevices==="object"&&ngDevices)if(typeof g==="undefined"||typeof ngDevices[g]==="object"){var c=window.location.href,e=c.indexOf("?"),h=c.indexOf("#"),d="",q="";if(h>=0){q=c.substr(h);c=c.substr(0,h)}if(e>=0){d=c.substr(e+1);c=c.substr(0,e)}e=d.indexOf("appdevice=");if(e>=0){h=d.indexOf("&",e);h=h>=0?d.substr(h+1):"";d=d.substr(0,e);if(typeof g!=="undefined")d+="appdevice="+g;else if(e>0)d=d.substr(0,e-1);if(h!=""){if(d!="")d+="&";d+=h}}else if(typeof g!=="undefined"){if(d!=
"")d+="&";d+="appdevice="+g}if(d!="")c+="?"+d;c+=q;if(window.location.href==c)window.location.reload();else window.location.href=c}}
function ngGetDeviceInfo(){var g=0,c=0;if(typeof window.innerWidth=="number"){g=window.innerWidth;c=window.innerHeight}else if(document.documentElement&&document.documentElement.clientWidth){g=document.documentElement.clientWidth;c=document.documentElement.clientHeight}else if(document.body&&document.body.clientWidth){g=document.body.clientWidth;c=document.body.clientHeight}var e=window.screen.colorDepth;if(typeof e==="undefined")e=24;var h=screen.width;if(typeof h==="undefined")h=g;var d=screen.height;
if(typeof d==="undefined")d=c;var q=window.orientation;if(typeof q==="undefined")q=h>d?90:0;var z=g>c?90:0,t=z==90,s=Math.abs(q%180)==90;return{ScreenWidth:h,ScreenHeight:d,ScreenOrientation:q,ScreenLandscape:s,ScreenPortrait:!s,Width:g,Height:c,Orientation:z,Landscape:t,Portrait:!t,ColorDepth:e,SupportsTouch:"ontouchstart"in window||window.DocumentTouch&&document instanceof DocumentTouch||navigator.msMaxTouchPoints?true:false}}
function ngDetectDevice(){var g;if(typeof ngDevices==="object"&&ngDevices){var c=ngGetDeviceInfo(),e=0,h=1E4,d,q=navigator.userAgent.toLowerCase(),z=function(u,G){var F,n,f,w,p,l=0,y=0;for(var j in G){f=G[j];y++;w=j.substr(0,3);if(w=="Opt"){j=j.substring(3,j.length);w=j.substr(0,3);F=false}else F=true;if(w=="Not"){j=j.substring(3,j.length);w=j.substr(0,3);n=true}else n=false;p=false;switch(w){case "Min":j=j.substring(3,j.length);if(!n&&c[j]>=f||n&&c[j]<f)p=true;break;case "Max":j=j.substring(3,j.length);
if(!n&&c[j]<f||n&&c[j]>=f)p=true;break;default:switch(j){case "IsMobile":F=false;y--;break;case "IExplorer":f=eval("/*@cc_on!@*/false")==f;if(!n==f)p=true;break;case "FireFox":f=q.indexOf("firefox")!=-1==f;if(!n==f)p=true;break;case "Chrome":f=q.indexOf("chrome")!=-1==f;if(!n==f)p=true;break;case "Safari":f=q.indexOf("safari")!=-1==f;if(!n==f)p=true;break;case "Opera":f=q.indexOf("opera")!=-1==f;if(!n==f)p=true;break;case "UserAgent":f=navigator.userAgent.indexOf(f)!=-1;if(!n==f)p=true;break;case "UserAgentIC":f=
q.indexOf(f.toLowerCase())!=-1;if(!n==f)p=true;break;default:if(!n&&c[j]==f||n&&c[j]!=f)p=true;break}break}if(p)l++;else if(F){l=-10000;break}}if(y){if(l>=0&&(l>e||l==e&&y<h)){e=l;h=y;g=u}}else if(typeof d==="undefined")d=u},t,s;for(var D in ngDevices){t=ngDevices[D];s=false;for(var E in t)if(typeof t[E]==="object"){s=true;z(D,t[E])}s||z(D,t)}if(typeof g==="undefined")g=d}return g}function ngLoadAppDeviceCSS(g,c,e){if(!(typeof ngDevice==="undefined"||ngDevice!=g))return ngLoadAppCSS(c,e)}
function ngLoadAppDeviceScript(g,c,e,h,d){if(!(typeof ngDevice==="undefined"||ngDevice!=g))return ngLoadAppScript(c,e,h,d)}function ngLoadAppDeviceImg(g,c,e,h){if(!(typeof ngDevice==="undefined"||ngDevice!=g))return ngLoadAppImg(c,e,h)};(function(){function g(){if(e<c){e++;var d=document.getElementById("ngLoadProgress");if(d)d.innerHTML=e+" %"}else{clearInterval(h);h=0}}var c=0,e=0,h=0;ngOnAppLoadProgress=function(d){if(c!=d){c=d;d=1E3/(c-d);if(d<10)d=10;h&&clearInterval(h);h=setInterval(g,d)}}})();
